### ISSUE TITLE
The Graph class method get_all_simple_paths isn't in the newest C distribution of python-igraph  

### ISSUE THREAD

**Issue by scramblingbalam** [igraph/igraph#1026]
The package that is built with [this wheel](http://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph) doesn't contain the Class method [get_all_simple_paths](https://github.com/igraph/python-igraph/blob/master/igraph/__init__.py)

**Comment by scramblingbalam** [comment]
I know that the problem could be at multiple places and not necissarily the core C igraph code but Python-igraph Github repo doesn't allow public issue creation. 
Also I'm using Anaconda but building dircley from the wheel with `pip install python_igraph-0.7.1.post6-cp27-none-win_amd64.whl`  tried this with both Python 3.5 and Python 2.7 since some of that code seems to be python 2.

**Comment by ntamas** [comment]
You should be able to create issues for `python-igraph` at https://github.com/igraph/python-igraph/issues (let me know if it still doesn't work).

Note that the wheel was created for version 0.7.1.post6, which did not contain this method yet. The head revision of the library contains `get_all_simple_paths()`, but there was no new release of the Python interface yet. You need to build the package from source if you need this method.

FWIW, the wheel that you mentioned is for CPython 2.7 (that's why it has `cp27` in the filename). It might or might not work with Anaconda Python. [These](https://anaconda.org/marufr/python-igraph) are unofficial versions of Python-igraph that were reported by others to work with Anaconda Python.
