### ISSUE TITLE
modularity_matrix() asks for membership vector but never uses it(?)

### ISSUE THREAD

**Issue by Selbosh** [igraph/igraph#1035]
The function `igraph_modularity_matrix()` demands a vector of memberships be specified. It is not clear why; the definition of the `modularity_matrix()` is given in igraph's R documentation as:

> M[i,j] = A[i,j] – d[i]d[j] / (2m)
> where A[i,j] is the (possibly weighted) adjacency matrix, d[i] is the degree of vertex i and m is the number of edges (or the total weights in the graph, if it is weighed *[sic]*

This definition does not use community memberships, because it corresponds to the *initial* modularity matrix, at the start of most modularity optimisation algorithms when every node is in its own community.
I tried running `modularity_matrix` (via R) with different membership vectors and always get the same result.

It seems to me that the documentation is unclear or the `membership` argument is unnecessary.

I'm not much of a C programmer, but in the source code (lines 960–1001 of `community.c`) it looks like the only time `membership` is used when throwing an error to say the user hasn't supplied it. Maybe I am missing something, however?

**Comment by ntamas** [comment]
Good catch. Note that `igraph_modularity_matrix` in the C layer is undocumented; probably this is one of the reasons why it is not part of the official C API. I have no idea why it has been exposed in the R interface (@gaborcsardi may know; he is the developer of the R interface).

As for the presence of the argument in `igraph_modularity_matrix`, I can only guess that the original intention was to define the elements of the modularity matrix as `A[i,j] - d[i]d[j] / 2m` iff `i` and `j` are in the same community and zero otherwise (so that's why it requires the membership vector), but later the plans have changed and the new definition does not need the membership vector any more.

Anyway, indeed the calcualtion does not depend on the membership vector, so you are free to supply any vector of the correct length here as a workaround.

Depending on what @gaborcsardi's plans are with this function, the argument will either be removed in future releases or the function will be changed to return zero in the modularity matrix where the two vertices in question do not belong to the same community.

**Comment by Selbosh** [comment]
While I'm here...

There is another problem with this function, in that it (as far as I understand the definition of the modularity matrix) doesn't handle graphs with loops.

Using @gaborcsardi's code [here](https://github.com/igraph/rigraph/issues/71), and using `igraph::modularity_matrix`, on such a graph both yield a modularity matrix whose rows and columns do not sum to zero.

For example:
```r
loopy_ring <- add_edges(make_ring(3), c(1,1, 3,3))
modularity_matrix(loopy_ring, 1:3) # NB the second argument is redundant

##      [,1] [,2] [,3]
## [1,] -0.6  0.2 -0.6
## [2,]  0.2 -0.4  0.2
## [3,] -0.6  0.2 -0.6
```

But Newman (2006; [doi:10.1073/pnas.0601602103](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1482622/)) says that the modularity matrix should have row and column sums equal to zero.

**Comment by ntamas** [comment]
I think I know what the problem could be - Newman assumes that the adjacency matrix contains `2` in the i-th diagonal element instead of `1` if the graph has a loop edge incident on vertex i (because there are two _endpoints_ of the vertex incident on the edge):

```
> A <- get.adjacency(loopy_ring, sparse=F)
> diag(A) <- diag(A) * 2
> d <- degree(loopy_ring)
> Q <- A - d %*% t(d) / sum(d)
> Q
     [,1] [,2] [,3]
[1,]  0.4  0.2 -0.6
[2,]  0.2 -0.4  0.2
[3,] -0.6  0.2  0.4
```

This is an easy fix in `igraph_modularity_matrix`; I'll commit a patch soon.

**Comment by Selbosh** [comment]
Very helpful, thanks!

**Comment by ntamas** [comment]
The calculation of the diagonal is now fixed in 1903e2cf.

**Comment by ntamas** [comment]
Proposing removal of the unneeded `membership` argument in 0.8.0. Shout if you have any objections.

**Comment by vtraag** [comment]
Agree.

**Comment by astamm** [comment]
I am running into trouble with `modularity_matrix` again because of the `membership` argument. First, I am confused because, according to this thread, it has been removed but it actually had not. Second, while the function works fine on most OS, I am running into troubles on win-builder which says `unused argument membership`. Can anyone comment on this please?

**Comment by ntamas** [comment]
This repository is for the C core of igraph, where the `membership` argument was indeed removed [here](https://github.com/igraph/igraph/pull/1194/files). However, the last official release of R interface of igraph (which you seem to be referring to) is still on a revision somewhere before igraph 0.8.0, where this argument still exists.

We are currently working on revitalizing the R interface of igraph, and as a first step we will bring it up to igraph 0.8.5, which is still a bit behind the latest release of the C core, but there was a change in the build system of the C core in igraph 0.9.0, which takes a bit more time to port to the R interface.

If you need a version of the R interface wherethe `membership` argument does not exist any more, try installing it from Github with `remotes::install_github("igraph/rigraph@master")`. Incidentally, I have just submitted the current state of the `master` branch to win-builder today and the build went just fine, so I'm pretty sure this will fix your problem.

**Comment by ntamas** [comment]
Just checked, the master branch on Github does not have the `membership` argument any more:

https://github.com/igraph/rigraph/blob/master/R/community.R#L450

**Comment by astamm** [comment]
Thanks. Actually I think that because you sent the newer version to win-builder today it is causing conflicts because R packages rely on the latest CRAN version for their dependencies. Hence, I am still assuming in my code that the membership argument exists. This makes all builds to succeed but on win-builder.

**Comment by ntamas** [comment]
I'm not sure if I understand; the version I sent to win-builder was for testing only and I don't think it got propagated anywhere. (It could not have been, because the maintainer email address was changed from Gábor's address to mine, and I don't think that CRAN would allow random people to hijack a package by submitting a new version with a changed maintainer address to win-builder).

So, by all means, the official version is still 1.2.6 and it still has the "membership" argument. The one that you can install from Github does not have it any more, but it will take some time until it gets to CRAN because we will have to go through a deprecation cycle in order not to break anyone else's code (and there are probably other changes in the C core that we need to watch out for).

I suspect that the compiler on win-builder was not so picky about unused arguments back in the days when igraph 1.2.6 was submitted to CRAN (it was in October 2020). Now it is, and thus it won't compile igraph 1.2.6 any more, and that's why you see a failing build on win-builder.

**Comment by astamm** [comment]
Thanks for following up. I think I should better explain what is going on on my side. I created an R package that relies on the R package **igraph**. When I test whether my package builds on win-builder and r-hub, it works fine on r-hub servers for a variety of OSes, windows included; but when I send it to win-builder, it throws me an error because of unused argument `membership` in the call to `igraph::modularity_matrix()`. I am trying to figure out why would win-builder install the dev version of **igraph** instead of the official CRAN version.

**Comment by ntamas** [comment]
I don't think that win-builder tries to install the dev version of igraph -- if it did, then it would not complain about the unused `membership` argument because the current dev version on Github does _not_ have that argument any more. I think what happens instead is that it probably tries to install the CRAN version, but for some reason it decides that the version on CRAN  is not binary-compatible with the machine (e.g., it might be a 64-bit machine and the CRAN version might be only 32-bit -- pure guesswork, I don't know what's on CRAN), and then it tries to compile igraph from source. Since it tries the official source of 1.2.6, which _does_ have a `membership` argument, _and_ the compiler is picky about unused arguments for some reason, the compilation fails.

We can probably find out more by looking at the detailed compilation logs from win-builder.

**Comment by astamm** [comment]
The compilation logs do not say much because it compiles just fine. The problem occurs at a call to `modularity_matrix()` from my package, in which case an error is thrown: `unused argument (membership = rep(1, igraph::gorder(network)))`. I do not understand why win-builder seems to install a version of **igraph** in which the argument `membership` does not exist anymore. I found a workaround by checking whether the function `modularity_matrix()` takes on 2 or 3 arguments and, in case it takes only two arguments (then it will be graph and optional weights), I do not call it with the `membership` argument. That way, it works fine on win-builder and r-hub.

**Comment by szhorvat** [comment]
> The compilation logs do not say much because it compiles just fine. The problem occurs at a call to `modularity_matrix()` from my package

It looks like this a pure R issue that has nothing to do with igraph's C core. Therefore it should be discussed in the rigraph repo.

**Comment by ntamas** [comment]
> The problem occurs at a call to `modularity_matrix()` from my package, in which case an error is thrown: `unused argument (membership = rep(1, igraph::gorder(network)))`

Hmm, okay, then I misunderstood, I though that it was the C compiler that threw an `unused argument` warning while compiling igraph, and that this somehow prevented the compilation of your package (e.g., because of a `-Werror` flag passed to the compiler). In this case, there's one thing I can do: I can update the version on Github to accept (but ignore) the `membership` argument again so we don't break API between 1.2.6 and the next version, and upload that to win-builder for testing. If win-builder is indeed working from a cache or from the dev version, this should do the trick.

If you are still having problems, please open an issue in [igraph/rigraph](https://github.com/igraph/rigraph) as this seems to be R-related only. Thanks.
