### ISSUE TITLE
Closeness centrality and disconnected graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1053]
Currently, this is what `igraph_closeness` does for disconnected graphs:

> If the graph is not connected, and there is no path between two vertices, the number of vertices is used instead the length of the geodesic. This is always longer than the longest possible geodesic.

Whether this is useful is debatable. It does this also for weighted graphs, where the reasoning that "This is always longer than the longest possible geodesic" does not apply.

Arguably, *closeness* just doesn't make much sense for disconnected graphs. If someone is calculating it for a disconnected graph, it may be unintentional (they didn't notice it's disconnected) or due to a lack of proper understanding of the concept.

Therefore it may be useful to issue a warning in this situation.  Consider this a feature suggestion.

----

This is what some other systems do:

 - Mathematica computes it per connected component
 - networkx seems to compute it per connected component, then weight it by the component size (unless I misunderstood—I haven't tested) https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.closeness_centrality.html

**Comment by vtraag** [comment]
Reopened, because this issue also touches on the estimation of closeness centrality for large graphs (cf. #1197).

**Comment by Silmathoron** [comment]
To give some update on this issue, I'll summarize here [a discussion on discourse](https://igraph.discourse.group/t/user-defined-distance-for-unconnected-node-in-closeness-and-harmonic-centrality/183) on this issue.

The arithmetic definition of the closeness centrality leads to significant "awkwardness" regarding how to compute it for graphs where the in- or out-component of some nodes does not contain all other nodes in the graph.

One way to alleviate the issue is related to the convention used for the distance between nodes ``i`` and ``j`` when there is no path linking ``i`` to ``j``.
Currently, igraph uses the convention ``d_{ij} = N``, with N the number of nodes in the graph.
Other graph libraries (graph-tool and networkx) use the convention ``d_{ij} = 0`` so that the distance does not appear in the sum.

To the best of my knowledge, this second convention is the least problematic because it can be combined with another convention for the normalization, which is to use ``n - 1``, with ``n`` the number of nodes in the in- or out-component of node ``i``.
This can be further improved using the Wasserman and Faust formula (by default in networkx).

I acknowledge that these definitions can seem convoluted and I would actually recommend using the harmonic definition of closeness centrality by default (see #1373) to avoid all these issues; however, I think the combination of the zero distance and WF formula are currently the best way of using arithmetic closeness on "disconnected" graphs.

**Comment by Silmathoron** [comment]
Here is an illustration for a graph where one node has zero out-degree
![graph](https://user-images.githubusercontent.com/8523051/79570122-279b0f80-80b9-11ea-8594-67d58485be03.png)

| Definition / Lib | Networkx                     | Graph-tool                   | IGraph                     |
|------------------|------------------------------|------------------------------|----------------------------|
| Arithmetic       |      [0.8, 0.6, 0, 1, 1]     |     [0.8, 0.6, NaN, 1, 1]    | [0.8, 0.4, 0.2, 1/3, 0.25] |
| Arithmetic (WF)  |   [0.8, 0.45, 0, 0.5, 0.25]  |               x              |              x             |
| Harmonic         | [0.875, 0.5, 0.0, 0.5, 0.25] | [0.875, 0.5, 0.0, 0.5, 0.25] |              x             |

To me, the most consistent definition is the harmonic, then the arithmetic definition corrected using the WF formula and the consistent use of the zero distance by havin ``c(2) = NaN`` (nobody is doing that so far).

**Comment by Silmathoron** [comment]
And here are the results for a "fully disconnected" undirected graph
![graph](https://user-images.githubusercontent.com/8523051/79571326-50240900-80bb-11ea-996a-37434d166851.png)

| Definition           | Closeness                                        |
|----------------------|--------------------------------------------------|
| Arithmetic (d=0)     |        [1, 1, 1, 2/3, 2/3, 2/3, 2/3, 2/3]        |
| Arithmetic (d=0, WF) | [0.29, 0.29, 0.29, 0.38, 0.38, 0.38, 0.38, 0.38] |
| Harmonic             |   [0.5, 0.5, 0.5, 0.75, 0.75, 0.75, 0.75, 0.75]  |

Again, I think the harmonic definition is best, then the arithmetic definition using the convention d=0 and the WF formula
