### ISSUE TITLE
igraph_contract_vertices() - maintaining edge ordering

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1057]
This is sort of a "feature request".

I noticed that `igraph_contract_vertices()` maintains edge ordering.  The `k`th edge in the result is derived from the `k`th edge in the input graph.  There is no formal guarantee given in the documentation though.

Would it be possible, and reasonable, to give such a guarantee? (I.e. document it and maintain it in future versions.)

This would make it easy for me to match up edge weights between the input and output graphs.

Perhaps the Python and R interfaces already assume this, but I am not familiar with attribute handling in those interfaces.

**Comment by ntamas** [comment]
The Python and R interfaces handle this in their attribute handlers. Basically, when the new, contracted graph is created, igraph first copies over all the graph and edge attributes by calling the `copy()` function in the attribute handler table. The attribute handler then takes care of updating the R- or Python-specific data structures that store the attributes. Then, igraph calculates the new vertex attributes, which might involve executing "contracting" functions that derive the new vertex attribute value from the values of the same attribute on the original vertices that were contracted into the new one. This is done by calling the `combine_vertices()` function in the attribute handler table.

The attribute handler table also contains functions like `permute_vertices()` and `permute_edges()`. If we ever decided to re-order edges in the contracted graph, this would happen by _not_ copying over the edge attributes in the first step but calling the `permute_edges()` function of the attribute handler table instead. So, when you are developing the higher-level Mathematica interface, you only need to implement these functions properly in the attribute handler table and you can forget worrying about how igraph implements the vertex contraction internally - you can simply trust igraph to call the appropriate attribute handler table functions to tell you how the edge weights should be mapped from the old graph to the new graph.

I believe that due to the above mechanism there is no need for `igraph_contract_vertices()` to guarantee that the edge ordering stays the same (even though it does so and I see no reason why it should change in the future). I can nevertheless add a formal guarantee in the documentation if that makes things easier for you in the long run, but then I wonder why the attribute handler functions are not enough.

**Comment by szhorvat** [comment]
It sounds reasonable—thus closing the issue.
