### ISSUE TITLE
Degree mixing matrix

### ISSUE THREAD

**Issue by briatte** [igraph/igraph#1061]
Dear `igraph` authors,

I would like to know if there are (or has been) any plans to include a [degree mixing matrix](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.assortativity.degree_mixing_matrix.html) function in `igraph`.

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by ntamas** [comment]
There are no plans to include such a function, but pull requests are welcome.

**Comment by szhorvat** [comment]
Some notes:

 - This is called the *joint degree matrix* in graphs theory (when not normalized), and sometimes studied similarly to degree sequences. This names should be at least mentioned, or perhaps used for the function.
 - It is beneficial to return a _sparse matrix_ result for efficiency (think scale-free degree distribution)
 - In view of the above (and of the simplicity of implementation), it may be a better idea to implement it directly in the higher level interfaces (R/Python) and use the native or common sparse matrix type of the language. IGraph/M (Mathematica) already has it, and C implementation probably wouldn't be noticeably more performant.

**Comment by ntamas** [comment]
We have a sparse matrix data type in the C layer as well, so we can make use of that if we decide that it should be implemented in the C layer. But, at least in Python, there is no direct dependency between the Python-C glue code and NumPy, and I want to keep it that way, so the best that the Python-C glue code can do (without depending on NumPy) is to return a list of `(outdeg, indeg, count)` triplets that can then be fed into a sparse matrix constructor. The Python interface can then import `numpy` dynamically at runtime and convert it into a NumPy sparse matrix if it is installed (and throw an `ImportError` otherwise).

**Comment by szhorvat** [comment]
If this is implemented, it should have an option to (optionally!) set the maximum degree for the result. This is useful when generating joint degree matrices for several graphs, and we want them to be of compatible size so they can operated (e.g. added) together.

If the maximum degree of the graph is smaller than what is requested, the result will simply be padded with zeros.

This advice is based on practical experience from using a joint degree matrix function.

**Comment by szhorvat** [comment]
[This was implemented in 0.10.8](https://github.com/igraph/igraph/blob/master/CHANGELOG.md#0108---2023-11-17), thanks @larah19 !

See `igraph_joint_degree_matrix()` and `igraph_joint_degree_distribution()`.

@briatte If you are still interested in this, I suggest opening [an R/igraph issue](https://github.com/igraph/rigraph/issues) and request exposing the functionality in R. There are still a lot functions that haven't been exposed in R, and this issue would help with prioritization.
