### ISSUE TITLE
Does not build with musl

### ISSUE THREAD

**Issue by flying-sheep** [igraph/igraph#1066]
<details>

Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

</details>

here you define `OFF_T` as `__off64_t` when building under linux, but when building with musl, it doesn’t exist:

https://github.com/igraph/igraph/blob/02005680aebb4281f2964c6d2d8d98851fce63b9/src/f2c/sysdep1.h#L16-L18

musl [defines](https://github.com/runtimejs/musl-libc/blob/master/include/sys/types.h#L83) `off64_t` instead of `__off64_t`, so the check needs to be different than `__linux__` or `__sun__`.

**Comment by ntamas** [comment]
That file is vendored from `f2c`; the problem is that the original author of that file was relying on platform-specific macros such as `__linux__` to determine whether `off64_t` exists or not, incorrectly assuming that on Linux, `__off64_t` will always exist. Unfortunately fixing this properly would mean incorporating some checks in our `configure` script for the presence of `off64_t` and then re-writing some of the makefiles to ensure that we include igraph's generated `config.h` when building `f2c` during the `igraph` build process.

A quick workaround for the time being could be to run the `configure` script on your machine as follows:

`CFLAGS=-D__off64_t=off64_t`

This would make `__off64_t` an alias to `off64_t`.

**Comment by flying-sheep** [comment]
Unfortunately I don’t manually compile it but use the Python bindings: [build log here](https://hub.docker.com/r/fastgenomics/scanpy/builds/b93gdrvkygwd2dakirnf8kh/).

I’m not sure how it works then: Is the C library bundled with the Python bindings? Can I just set CFLAGS as environment variable?

**Comment by flying-sheep** [comment]
OK, I circumvented it with the hacky ` CC='gcc -D__off64_t=off64_t' pip3 install python-igraph`. Now I run in the second assumption problem:

    f2c/uninit.c:276:25: fatal error: fpu_control.h: No such file or directory

**Comment by ntamas** [comment]
Basically the patch proposed there simply excludes `uninit.c` from compilation, hoping that it does not contain anything that would be needed by `clapack`. You can try the same trick with igraph and then report whether it works or not.

I guess that due to these patches, you'll need to fall back to a more complicated installation method for `python-igraph`:

1. Get its source code from PyPI and extract it directly to a folder.
2. Enter the folder, run `python setup.py build` and watch the compilation fail because of the `off64_t` issue. As a side-effect, it will download and extract the C core of igraph in a subfolder named `igraphcore`.
3. Apply the necessary patches in `igraphcore`.
4. Run `python setup.py build` again - this will now pick up the already-downloaded C core and use the patched version instead of downloading it again.
5. Rinse and repeat from step 3 until the compilation succeeds.

If you encounter any more issues apart from the `uninit.c` part and `off64_t`, let me know. Once you succeed, I'll try to create a comprehensive patch for the trunk.

**Comment by flying-sheep** [comment]
Thanks again! I think I can stave that off one more time:

I think that excluding `uninit.c` can be done with a simple `-DIEEE0_done=`, as this will cause the preprocessor to reduce the file’s contents to nothing. And If nothing uses the single function defined in there, the compilation will succeed.

So if this works:

```py
CC='gcc -D__off64_t=off64_t -DIEEE0_done=' pip3 install
```

And preferable (once https://github.com/igraph/python-igraph/pull/163 is in a release):

```py
CFLAGS='-D__off64_t=off64_t -DIEEE0_done=' pip3 install
```

**Comment by flying-sheep** [comment]
[Here](https://github.com/iXit/Mesa-3D/issues/213) are people talking about replacing fpu_control.h with musl stuff.

[the fix](https://github.com/iXit/Mesa-3D/pull/214/files) is a bit too magic though
