### ISSUE TITLE
degree_sequence_game: what does SIMPLE_NO_MULTIPLE do?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1072]
[The documentation](http://igraph.org/c/doc/igraph-Generators.html#igraph_degree_sequence_game) clearly explains what the `SIMPLE` method of `degree_sequence_game` does.  However, it does not explain the algorithm behind `SIMPLE_NO_MULTIPLE`.  My impression from reading the documentation was that `SIMPLE_NO_MULTIPLE` does the same thing as `SIMPLE`, except that when a loop or multi-edge is generated, it throws away the result and starts again from scratch.

> This method is similar to `IGRAPH_DEGSEQ_SIMPLE` but tries to avoid multiple and loop edges and restarts the generation from scratch if it gets stuck.

However, if it did this, then I believe it *would* sample uniformly, which it doesn't (as the documentation states, and as I found by experiment). Also, while I did not take the time to fully understand the code, it seems clear that [it won't throw away the result if it finds a loop or multi-edge](https://github.com/igraph/igraph/blob/bbb00935104bda9e76da8a288e4fc56379c7bc65/src/games.c#L996).

Thus my questions are:

 - What does `SIMPLE_NO_MULTIPLE` do, in simple terms?  This should be documented. Otherwise, it should be made clear that this method gives absolutely no guarantees and the user shouldn't care about the algorithm. This is already suggested, but I found it confusing ...

 - Why isn't there a method that does the same as `SIMPLE`, but keeps retrying until it gets a result that is a simple graph?  This would be useful because the sampling would be uniform (consider this a feature request).  While the user can filter non-simple results manually after they have been fully generated, a function that does this internally could in principle be faster.

**Comment by ntamas** [comment]
Not sure if this is a simple explanation, but here it is. Basically, the `SIMPLE_NO_MULTIPLE` method works as follows:

1. Generate a long vector `v` where vertex _i_ appears as many times as its desired degree.
2. Shuffle the vector `v` and create an empty vector `w`.
3. Start creating edges between `v[0]` and `v[1]`, `v[2]` and `v[3], `v[4]` and `v[5]`, and so on. Whenever an edge would be created between vertices that are already connected, put the involved vertices aside in another vector `w`.
4. If there were no edges created in the previous step, it means that we've reached a dead end. Start again from scratch.
5. Otherwise, if `w` is empty, we are done.
6. Otherwise, let `v` equal to `w` and go back to step 2.

So, this is basically the same as the "bag"-algorithm for `IGRAPH_DEGSEQ_SIMPLE` with the added twist that it simply skips over pairs of vertices that would create a multiple or loop edge and then keeps on trying with the residual edge stubs.

This method probably does not sample uniformly but I can neither prove nor disprove it. I'll update the docs soon to clarify this.

> Why isn't there a method that does the same as SIMPLE, but keeps retrying until it gets a result that is a simple graph?

I guess it's mostly because you can create it fairly easily. E.g., in Python:

```python
def generate(degs):
    while True:
        g = Graph.Degree_Sequence(degs, method="simple")
        if g.is_simple():
            return True
```

But feel free to submit a PR if you think it would be useful. (You can call it, say, `SIMPLE_NO_MULTIPLE_UNIFORM`).

**Comment by szhorvat** [comment]
I'll submit a PR eventually.  Feel free to assign me to this bug (to make it easy to keep track of it).

**Comment by szhorvat** [comment]
Note to self: `k_regular_game()` currently uses `degree_sequence_game()` with `SIMPLE_NO_MULTIPLE`. It should also be updated and the documentation should discuss whether/when sampling is uniform.

**Comment by szhorvat** [comment]
Does anyone know where this algorithm (`degree_sequence_game` with `SIMPLE_NO_MULTIPLE`) originally came from?  Is it an ad-hoc made up thing, or is there a reference that analyses the properties of this sampler? @gaborcsardi do you remember?

**Comment by gaborcsardi** [comment]
https://github.com/igraph/igraph/blame/952241efc6ce2db5a3eba111591c0426758951a3/src/games.c#L1440 says that I did not write that

**Comment by ntamas** [comment]
I'm quite sure it's an ad-hoc made up thing. I think the documentation even mentions that there are no theoretical guarantees about this method.
