### ISSUE TITLE
More general rewiring

### ISSUE THREAD

**Issue by arivero** [igraph/igraph#1075]
Make sure that these boxes are checked before submitting your issue -- thank you!

- [ X ] This issue is for the C core of igraph.
- [ X  ] This issue is a bug report or a feature request, not a support question.

From https://github.com/igraph/igraph/issues/999 and some variations in the R API I am wondering if a wider rewire function is in the blueprints of the next version.

If so, I would like to add a feature request: to allow for a general function as "rewire probability". This could be useful to implement rewiring while keeping weight, or keeping multiple dimensions of weights and node labels, or even to implement a MonteCarlo "temperature" to accept or reject a rewire depending of node similarity.

**Comment by szhorvat** [comment]
Can you formulate this feature that you are asking for in a mathematically precise way?

I do not understand at all what you mean.

**Comment by arivero** [comment]
I was thinking a generalisation:

```
int igraph_rewire_edges(igraph_t *graph, igraph_real_t (*prob_function)(   igraph_integer_t, igraph_integer_t), 
			igraph_bool_t loops, igraph_bool_t multiple) {
```

and something similar in igraph_rewire_core. The prob_function should get as input two edges (or two vertices in the _core case) and return 1 if the rewiring is to be done, 0 if not. Perhaps also some extra input to allow for global parameters.

In this way acceptance would be very general, Metropolis–Hastings or whatever algorithm.  

Of course, the problem here is to implement it in a way compatible with the python and r APIs.

**Comment by szhorvat** [comment]
Thanks for the clarification.

I am not very familiar with the architecture of the Python and R interfaces, but I can tell you that with [the Mathematica interface](https://github.com/szhorvat/IGraphM/) (which I'm working on, and which is less well integrated that the Python & R ones) it can be done. However, it probably would not be particularly useful, as calling back to the Mathematica evaluator would slow things down significantly. Very likely, the slowdown would be bad enough that a pure Mathematica implementation (no C code) would have worked just as well.

There are additional difficulties/limitations too:

 - It would be necessary for the function to also access the whole graph, to decide e.g. if an edge-swap would create multi-edges (typical use case) or whether the graph remains connected (e.g. the Viger-Latapy method in `degree_sequence_game`)

 - Such an implementation would limit the performance of even the C interface, not only because of the non-inlineable function calls, but also by preventing optimizations such as converting the graph to a different storage format before rewiring.  E.g. the current implementation can use an adjacency-list based implementation.

 - There are important use cases which require three-edge-swaps instead of two-edge-swap. (E.g. [uniform sampling of directed graphs with given degree sequence](https://arxiv.org/pdf/0905.4913.pdf).)

Thus personally I'm skeptical about the value of such a generalization. I'm not sure that it would add much over implementing the whole thing from scratch (either in a high-level language or in C). Of course, that's just a personal opinion, and I have no say in what goes into igraph ;-)

**Comment by arivero** [comment]
Hmm I see. And worse, once the function needs to access the whole graph, surely also some thread-safety is going to be needed :-(

**Comment by ntamas** [comment]
@szhorvat has made very good points here. However, there are several cases in the library where the native igraph function accepts a callback function that can be implemented in the host language (for instance, the VF2 isomorphism algorithm accepts a callback that lets the user decide whether two vertices are "compatible"), so this is not a show-stopper on its own, and the other limitations could also probably be worked around.

My problem with the proposal is more with the fact that it has arbitrarily picked one part of the rewiring process that can be customized and ignored the rest; for instance, what if I want to customize the edge _selection_ process instead (e.g,. by favouring particular types of edges for rewiring rather than others), and just stick to standard double edge swaps once the edges are selected for rewiring? So, a more general approach would probably allow the user to specify an "edge selection callback" that takes the graph and returns two (or three?) edge IDs to rewire (two for a two-edge-swap, three for a three-edge-swap), and an "edge rewiring callback" that tells whether the rewiring is allowed or not. And actually, there are sometimes two ways to perform a two-edge-swap for the same pair of edges, so this should be taken into account as well. The generic function would probably not be too performant due to the callbacks back into the host language, but it would probably be useful for experimentation and quick prototyping.

Re thread safety: it depends on the host language; for instance, the Python interpreter has a global interpreter lock, so only one bit of Python code can mess around with the graph at the same time anyway.

At this stage I am voting against the idea (also considering that I lack the spare time to implement it), but feel free to continue the discussion and/or re-open the issue if there are new arguments to consider.
