### ISSUE TITLE
Failure in igraph_all_st_cuts

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1102]
I'm not quite sure what is going on here.  Here's an example, demonstrated using the R interface:

```
g<-make_graph(c(1, 2, 1, 5, 1, 7, 1, 8, 2, 1, 2, 4, 3, 10, 4, 2, 4, 6, 4, 8, 5, 1,  5, 2, 5, 6, 5, 10, 6, 8, 7, 1, 7, 6, 9, 3, 9, 5, 9, 10))

stCuts(g,1,6)
```

It fails with:

```
Error in stCuts(g, 1, 6) : 
  At st-cuts.c:415 : Invalid root vertex id for dominator tree, Invalid value
```

**Comment by szhorvat** [comment]
Shorter example:

```
g<-make_graph(c(1, 2, 1, 3, 2, 3, 3, 4))
stCuts(g,1,3)
```

The graph looks like this:

![image](https://user-images.githubusercontent.com/1212871/40611544-fe5736a6-6276-11e8-813d-6ec958f15a9f.png)

**Comment by ntamas** [comment]
I was looking at this part of the code for quite a while tonight but I couldn't figure out what's going on. I think it was @gaborcsardi who wrote this part of the code and I am not familiar with the algorithm implemented there.

Other examples where the same problem happens:

```
> g<-make_graph(c(1,2, 2,3, 3,4))
> stCuts(g, 1, 3)
```

(the above has one less edge than the one found by @szhorvat)

This one has a path of length 4 instead of 3:

```
> g<-make_graph(c(1,2, 2,3, 3,4, 4,5))
> stCuts(g, 1, 3)
```

However, note that this one works (same graph but different vertex pair):

```
> g<-make_graph(c(1,2, 2,3, 3,4, 4,5))
> stCuts(g, 1, 3)
```

But this one fails again:


```
> g<-make_graph(c(1,2, 2,3, 3,4, 4,5))
> stCuts(g, 2, 4)
```

For a path of length 9, the following combinations fail: 1-3, 1-4, 1-5, 1-6, 2-4, 2-5, 2-6, 3-4, 3-5, 3-6, 3-7, 4-6, 4-7, 5-7. There seems to be some kind of regularity here.

**Comment by szhorvat** [comment]
I think that one of the lessons is that we should try to document algorithms better.  Perhaps provide a summary of the theory background, as well as the algorithm, in a long comment before the implementation.  The goal would be to make it easier for someone other than the original author to fix problems.

I'll try to update my outstanding PRs with more comments on how things are implemented.

Hopefully, this would also make igraph a bit more attractive for potential contributors.  For some reason, very few people contribute (compare [networkx](https://github.com/networkx/networkx/pulls)).  I can imagine several reasons, and this could be one of them.

What's nice about [Sage](http://www.sagemath.org/) is that its source code often has a clear discussion of the math involved before jumping into the implementation.

**Comment by szhorvat** [comment]
Not the right place to discuss the details, but I am getting quite concerned about the future of igraph due to the lack of contributors.

**Comment by szhorvat** [comment]
Here's a link to a complaint about the same on the mailing list:

http://lists.nongnu.org/archive/html/igraph-help/2018-11/msg00000.html

**Comment by szhorvat** [comment]
Possibly related? https://github.com/igraph/igraph/issues/204
