### ISSUE TITLE
biconnected_components: isolated vertices are ignored

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1104]
`igraph_biconnected_components` does not return any isolated vertices.  E.g., for this graph:

![image](https://user-images.githubusercontent.com/1212871/40971426-da8e3c0e-68bd-11e8-9042-fe5bb0d7fe7a.png)

we get `{{3, 2, 1}, {4, 1}}` instead of `{{3, 2, 1}, {4, 1}, {5}}`.

This is not unreasonable considering that the biconnected components are better defined by edges than vertices: each edge belongs to precisely component but a vertex may belong to multiple.

Now the question is: how should this be fixed?

 - document it?
 - fix the computation of the `components` argument?

Considerations:

 - The function also returns the number of components (`no` argument), which would differ for edge-components and vertex-components if isolated vertices are considered.

 - The current behaviour is somewhat confusing, and people may try to test if a graph is biconnected by `no == 1`

What other systems do:

Mathematica returns isolated vertices as individual components.

Maple also returns them.

Sage also returns them.

Magma does *not* return isolated vertices.

networkx also does not return them.

LEMON and BGL only returns edge-components.

**Comment by szhorvat** [comment]
Given that igraph development is already starved for resources I propose we amend the docs and be done with it.

However, I do think that given the target audience of the high-level interfaces this is not the most user-friendly document.

**Comment by ntamas** [comment]
Personally, I have always considered the set of biconnected components as a partition of the edges of the graph such that each edge is in exactly one of the biconnected components, but you are right, there are multiple ways to think about it - especially if you consider that `igraph_is_connected()` returns true for an empty graph; in that sense, a graph with a single vertex is biconnected because removing that single vertex would not disconnect the graph.

However, given my limited resources, I will simply update the documentation now and leave this open as a potential improvement direction in case igraph's development will be picked up by someone again.

**Comment by ntamas** [comment]
Added in c517ad26
