### ISSUE TITLE
Failed to build igraphtest in vs2017

### ISSUE THREAD

**Issue by ghGYR** [igraph/igraph#1169]
I get the vs project as following the instruction  in "INSTALL.WINDOWS". 
There are always some Invalid file paths such as "src\make[1]:" in the “igraph.vcproj”
I have to remove them  before upgrading the project to vs2017 .
Then I build  the static library "igraph.lib" successfully in vs2017.
But errors happen when build the igraphtest ,such as"error link2019  __imp__igraph_destroy".
It seems that every function failed to link with "igraph.lib".
So I think there may be some bugs when create vs project  from cygwin ,
or it isn`t compatible with vs2017?

**Comment by ntamas** [comment]
The missing functions (like `igraph_destroy`) were probably in the files that you removed from `igraph.vcproj`. Sorry, I can't help you further here as I don't use Windows myself and have never tried to compile igraph on Windows. It could be the case that the project file is not suitable for VS2017. The CI environment builds igraph with Visual Studio 9 (that is from 2008 IIRC) and it seems to work. Let us know if you figure out what's wrong with the project file under VS2017.

**Comment by szhorvat** [comment]
Since I did not have much success with VS, I build igraph with mingw/msys2 on Windows, then use the resulting library from VS.  This is _far from ideal_, but it works.  The caveat is never to mix `free`/`malloc` from VS with those from MinGW.  When you need to allocate something that will be deallocated by igraph, use `igraph_malloc` in VS (never `malloc`). When you need to free things allocated by igraph, use `igraph_free` (never `free`).

I keep personal notes for compiling with MinGW here:

https://github.com/szhorvat/IGraphM/blob/master/Development.md#windows

Something not mentioned there is that I needed to remove `libgmp.la`, otherwise it'd refuse to link with GMP.

I hope this will be of some help.

If you manage to compile it with VS2017, please do make detailed notes and let us know how you did it.
