### ISSUE TITLE
Wishlist: triad_census() - save results to make it possible to color the found triads

### ISSUE THREAD

**Issue by Marmeladenbrot** [igraph/igraph#1246]
I have a graph where I want to find the number of 030T triads AND color them accordingly (nodes not part of a 030T triad = grey, 030T triads = red).

triad_census() counts the different triad types but does not save the information in the igraph object so that I can't plot it by color.

Please make it possible to do so.

**Comment by szhorvat** [comment]
Take a look at the subgraph isomorphism functions. They can do this.

**Comment by szhorvat** [comment]
I am going to close this because it is already implemented as `igraph_motifs_randesu_callback`, which calls a function for each motif. If I misunderstood your request, please clarify. If your request is for a specific high-level interface which does not expose this functionality, please open an issue for that interface instead.
