### ISSUE TITLE
Incompatible Library Version

### ISSUE THREAD

**Issue by YasirKusay** [igraph/igraph#1282]
I've recently installed igraph and wrote a small program from it, successfully compiling it but upon executing the program, I am greeted with this message:

dyld: Library not loaded: @rpath/libxml2.2.dylib

  Referenced from: /usr/local/lib/libigraph.0.dylib

  Reason: Incompatible library version: libigraph.0.dylib requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0

Abort trap: 6

I am not sure as to why I am getting this error, I made sure that libxml2 and igraph is up to date (using homebrew on mac) but I am still facing this issue. What should I do?

**Comment by vtraag** [comment]
You probably have an older version of `libxml2` installed in another location. You can remove the older installation or adjust `LD_LIBRARY_PATH` to ensure that the proper library is found.

**Comment by szhorvat** [comment]
Can you give more details about how you installed igraph and how you are compiling?

@vtraag  I think OP is on macOS, where we have `DYLD_LIBRARY_PATH` instead, but I am not intimately familiar with the working of this environment variables and the specific differences between Mac/Linux.

**Comment by iosonofabio** [comment]
For full disclosure, Yasir is a student who recently contacted me to contribute to igraph, so he's interested in compiling the git bleeding edge rather than just installing production igraph from MacPorts.

I am meeting with him to help and would appreciate OSX folks expertise as I'm most familiar with linux.

Thank you all,
Fabio

**Comment by ntamas** [comment]
@vtraag is correct; this typically happens when you have multiple versions of `libxml2` lying around on your machine. The most plausible explanation is that when you compiled igraph, it linked to one of these libxml2 versions - the one whose interface is versioned as 12.0.0. Then, when you try to _run_ your program that links to igraph, the linker picks up _another_ of these libxml2 libraries - the one with version 10.0.0.

Another variant of this problem manifests itself when you have multiple versions of _igraph_ lying around, one linked with an older libxml2 and one with a newer version. Then, it can also happen that during compilation, the linker finds the newer igraph, while during execution, it finds the older one.

A great tool for debugging these kinds of problems on macOS is `otool -L`. You can run it on an executable or a dynamic library and it tells you which other libraries the library is trying to link to. Ideally, if you have a well-behaved igraph library on your system, it should link to `/usr/lib/libxml2.so.*` instead of `some-other-folder/libxml2.so.*`. For instance, this is the output for the Homebrew-installed `igraph` on my machine:

```sh
❯ otool -L /usr/local/Cellar/igraph/0.7.1_6/lib/libigraph.0.dylib
/usr/local/Cellar/igraph/0.7.1_6/lib/libigraph.0.dylib:
	/usr/local/opt/igraph/lib/libigraph.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 62.1.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	/usr/local/opt/glpk/lib/libglpk.40.dylib (compatibility version 44.0.0, current version 44.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

and here's another one that I compiled from source right now (with internal LAPACK / BLAS / GLPK):

```sh
❯ otool -L libigraph.0.dylib
libigraph.0.dylib:
	/Users/tamas/lib/libigraph.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 62.1.0)
	/usr/local/opt/gmp/lib/libgmp.10.dylib (compatibility version 14.0.0, current version 14.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

As you can see, the ABI version of `libxml2.2.dylib` that comes with a stock macOS is 10.0.0, so this is what your `libigraph.0.dylib` should be linking to.

**Comment by ntamas** [comment]
Incidentally, the version of `libxml2` from Homebrew is at ABI version 12.0 on my Mac so that could be the culprit:

```sh
/usr/local/Cellar/libxml2/2.9.10/lib/libxml2.2.dylib:
	/usr/local/opt/libxml2/lib/libxml2.2.dylib (compatibility version 12.0.0, current version 12.10.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
```

I guess that the compiler picked up libxml2 from Homebrew when compiling the test app, but then it tries to link to libxml2 from macOS when running the app. In theory, `libxml2` is installed by Homebrew in a way that compilers don't pick it up accidentally:

```sh
❯ brew info libxml2
[...snip...]
==> Caveats
libxml2 is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have libxml2 first in your PATH run:
  echo 'export PATH="/usr/local/opt/libxml2/bin:$PATH"' >> ~/.zshrc

For compilers to find libxml2 you may need to set:
  export LDFLAGS="-L/usr/local/opt/libxml2/lib"
  export CPPFLAGS="-I/usr/local/opt/libxml2/include"

For pkg-config to find libxml2 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
```

**Comment by YasirKusay** [comment]
I apologise for replying a bit late as I had work and didnt get a chance to code until now. Thank you all for your replies! @vtraag and @ntamas you are correct! There is another version of libxml2 and it appears that it comes with the computer so I cannot simply delete it. I have tried to change the library linkage of igraph by running the command:

install_name_tool -change /usr/lib/libxml2.2.dylib @executable_path/usr/local/Cellar/libxml2/2.9.10/lib/libxml2.2.dylib /usr/local/Cellar/igraph/0.7.1_6/lib/libigraph.0.dylib

Unfortunately, running otool -L on libigraph, the updated version is still version 10 and not the expected version 12, even though it is now linked to the correct location and I still cannot run my C file. I apologise for repeating this question but what do you think I should do now?

**Comment by ntamas** [comment]
`install_name_tool` simply changes the _path_ where the library is looking for its dependencies, but it does not change the ABI version that it is looking for. You need to recompile igraph from scratch to fix this, and make sure that it finds the "right" libxml2 during compilation.

> There is another version of libxml2 and it appears that it comes with the computer so I cannot simply delete it.
That shouldn't be the case - even on a fully updated Mac, the only version of libxml2 that comes preinstalled with the OS is at `/usr/lib/libxml2.2.dylib` and it is at ABI version 10. Where is your other copy of libxml2 located at?

**Comment by YasirKusay** [comment]
The other copy (the one I installed from brew) is located in
/usr/local/Cellar/libxml2/2.9.10/ 
How can I recompile to make sure it locates the correct libxml2 (the one above)

**Comment by szhorvat** [comment]
> Can you give more details about how you installed igraph and how you are compiling?

Can you show the exact steps you used to compile & install igraph, then to compile your program? We can start from there.

**Comment by ntamas** [comment]
Also, igraph's configure script typically uses `pkg-config --cflags --libs xml2` to find libxml2, falling back to sane defaults if `pkg-config` is not installed or if it does not know about libxml2. Try running `pkg-config --cflags --libs xml2` on the command line; it should either say that `pkg-config` is not found or that `libxml2` was not found on the pkg-config search path. Manually symlinking `libxml2` from Homebrew to `/usr/local/lib` could also be the source of confusion.

**Comment by iosonofabio** [comment]
Thanks guys for helping Yasir. Happy to include whatever comes out in the FAQs if you feel like it'd be useful for the general public

**Comment by YasirKusay** [comment]
Thats ok but thank you very much. After playing around for a bit, I have managed to fix the problem!

**Comment by iosonofabio** [comment]
Awesome! What was the fix?

**Comment by YasirKusay** [comment]
The solution is a bit anti climactic. I decided to simply brew uninstall igraph and reinstall again and compile normally. It worked and now the program works. Im certain that it has to do with conflicting files, uninstalling/reinstalling seemed to have solved this.
