### ISSUE TITLE
Upgrade igraph to 0.8 in package managers

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1284]
This is a TODO item (so we don't forget).

After the 0.8 release, we need to make sure that igraph and python-igraph are upgraded quickly in:

 - [x] MacPorts (@szhorvat)
 - [x] Homebrew (@ntamas)
 - [ ] `conda` (@vtraag)

**Comment by ntamas** [comment]
We should probably do the same with Mac Homebrew as well (which I am happy to do).

**Comment by vtraag** [comment]
Perhaps we can make this: "Upgrade `igraph` to 0.8 in package managers"? There is also a `conda` package of `igraph` (i.e. of the the C core), I'd be happy to make sure that it is properly updated (and also supported on Windows). 

What did we agree on for Debian? I believe somebody else could pull the release source and create a new Debian package, but I don't remember the details, hopefully you do @ntamas?

Perhaps there are other package manager still?

**Comment by szhorvat** [comment]
If anyone volunteers to take care of a specific package manager, please
just edit the issue and add a checkbox

--
sent from a phone

**Comment by ntamas** [comment]
> What did we agree on for Debian?
The Debian-Med team manages the packaging of igraph for Debian; see [this repo](https://salsa.debian.org/med-team/igraph). I believe that the easiest is to contact @tillea once we've made a release and discuss with him what needs to be done to make the packaging as smooth as possible.

It might also be worth looking into the repo now to see if there are any patches they apply to upstream in 0.7.1, and merge those if it makes sense.

**Comment by tillea** [comment]
On Tue, Jan 21, 2020 at 08:44:53AM -0800, Tamás Nepusz wrote:
> > What did we agree on for Debian?
> The Debian-Med team manages the packaging of igraph for Debian; see [this repo](https://salsa.debian.org/med-team/igraph). I believe that the easiest is to contact @tillea once we've made a release and discuss with him what needs to be done to make the packaging as smooth as possible.
> 
> It might also be worth looking into the repo now to see if there are any patches they apply to upstream in 0.7.1, and merge those if it makes sense.
There are definitely some patches that are not Debian specific.  Feel free to ask me if you need any assistance.  Kind regards, Andreas.

**Comment by ntamas** [comment]
@tillea I have checked the patches now and all of them are merged into upstream so there should be no need for any of them with the next release.

I am a bit uncertain about [this one](https://salsa.debian.org/med-team/igraph/blob/master/debian/patches/skip_tests_accessing_remote.patch), though. According to the description of the patch, it was needed to disable certain tests that require "remote access", but as far as I know neither the PageRank nor the centralization tests require access to any remote resource.

**Comment by tillea** [comment]
On Wed, Jan 22, 2020 at 12:21:53AM -0800, Tamás Nepusz wrote:
> @tillea I have checked the patches now and all of them are merged into upstream so there should be no need for any of them with the next release.

Great!
 
> I am a bit uncertain about [this one](https://salsa.debian.org/med-team/igraph/blob/master/debian/patches/skip_tests_accessing_remote.patch), though. According to the description of the patch, it was needed to disable certain tests that require "remote access", but as far as I know neither the PageRank nor the centralization tests require access to any remote resource.

Hmmm, may be I was wrong here.  The Debian build system is using a chroot that is disconnected from the internet.  I guess if the tests are disabled I have suspected signs that these tests might be directly or indirectly to some downloading.  But I might have been wrong.  Feel free to skip this patch and I try again with the new version.

Thanks a lot for your cooperation.  Its very helpful to get rid of patches inside Debian!  Andreas.

**Comment by ntamas** [comment]
@tillea We have a `debian/` folder in our own source tree, but it is unmaintained - would it cause any disruption on your end if we removed it from our repo?

**Comment by tillea** [comment]
On Wed, Jan 22, 2020 at 02:52:03AM -0800, Tamás Nepusz wrote:
> @tillea We have a `debian/` folder in our own source tree, but it is unmaintained - would it cause any disruption on your end if we removed it from our repo?
We actually recommend that upstream should not provide a debian/ folder due to several reasons.  So please remove it if you want to do me a favour. :-)

**Comment by ntamas** [comment]
Just adding a note here that I need to wait for the final 0.8.0 tarball before updating the Homebrew recipe for igraph because the recipe needs to include the hash of the tarball.

**Comment by szhorvat** [comment]
Same with MacPorts.

**Comment by ntamas** [comment]
@tillea igraph 0.8 is now released and it should build out-of-the-box on Debian. What can we do to speed up the process of getting this version into Debian?

**Comment by tillea** [comment]
On Wed, Jan 29, 2020 at 11:33:29AM -0800, Tamás Nepusz wrote:
> What can we do to speed up the process of getting this version into Debian?

Just confirming that
  https://github.com/igraph/igraph/releases
is now the authoritative source to download the source.  The Debian watch file currently says:

    http://igraph.org/c/ .*/nightly/get/c/igraph-(\d[\d.-]+)\.tar\.gz
    # Upstream advises to NOT use Github releases
    # https://github.com/igraph/igraph/releases .*/archive/(\d[\d.-]+)\.(?:tar(?:\.gz|\.bz2)?|tgz)

I'd prefer github directly and https://igraph.org/c/#downloads is pointing to this location anyway.

**Comment by ntamas** [comment]
I can confirm that Github releases is the authoritative download source now. (The main homepage is hosted on Github Pages so it would be pointless to copy the tarballs there - they would probably end up in the same server farm anyway).

**Comment by tillea** [comment]
On Wed, Jan 29, 2020 at 11:33:29AM -0800, Tamás Nepusz wrote:
> @tillea igraph 0.8 is now released and it should build out-of-the-box on Debian.
OK, package builds and build time test suite passes.

> What can we do to speed up the process of getting this version into Debian?
I have added a [symbols file](https://salsa.debian.org/med-team/igraph/blob/master/debian/libigraph0v5.symbols) to the packaging which is helpful to track ABI changes of libraries.  Since from version 0.7.1 to version 0.8.0 there are a lot of '#MISSING:' symbols - so I guess we need to bump the SOVERSION from 0 to 1.

Is it correct that version 0.8.0 is not ABI-compatible with version 0.7.1?

Kind regards, Andreas.

**Comment by szhorvat** [comment]
> Is it correct that version 0.8.0 is not ABI-compatible with version 0.7.1?

Yes.

Furthermore, python-igraph 0.7.1 (last released version) won't build with igraph 0.8. I have no idea if this is an issue for Debian—mentioning it just in case.

For MacPorts it appears to be an issue. https://github.com/macports/macports-ports/pull/6271

**Comment by ntamas** [comment]
Just my two cents re the ABI compatibility: @szhorvat is correct, 0.8 is not ABI-compatible with 0.7.1 and it is likely that we will break API again between 0.8 and 0.9. The reason for this is that we have recently revived the development of igraph, and we would like to get rid of a few mistakes that we've made years ago with the current API. Personally, I do not plan any ABI changes from 0.9 onwards (unless there's a very good reason to do so of course), just new functionality. A few weeks after the release of 0.9, we will probably transition to 1.0 without any API breakage and commit ourselves to maintaining API compatibility with whatever we have accepted at 1.0. But right now we are still at 0.x, and in [semver](https://semver.org/) sense everything is allowed at 0.x.y. I also plan to commit ourselves officially to semantic versioning from 1.0.

I don't know whether this complicates things for the Debian packaging or not as I am not familiar with Debian policies. How shall this be handled on the Debian side? Will we have to rename `libigraph0` to `libigraph1` and then `libigraph2` and so on until we reach API stability?

**Comment by orlitzky** [comment]
I was looking at an upgrade in Gentoo, but the practice of bundling every library you use makes it impossible. Our users already have these libraries installed, and we have to link against the ones they have installed (and not the ones in your tarball) because those are the ones that get upgraded, and get security fixes. For v0.7.1, someone went to a lot of trouble to edit your build system and un-bundle all of the libraries... but that's not a feasible long-term strategy (i.e. I'm not going to take over the package and upgrade it knowing that I'll have to spend an entire day fixing it whenever there's a release). Some packages have a `--with-external-foo` configure option, but many don't.

Debian and the other distributions generally have the same policy. If they've allowed it in the past, it was most likely because nobody noticed.

**Comment by ntamas** [comment]
> that's not a feasible long-term strategy (i.e. I'm not going to take over the package and upgrade it knowing that I'll have to spend an entire day fixing it whenever there's a release)

Fair enough. But in the ideal case, it should only be a matter of running `./configure --with-external-f2c --with-external-blas --with-external-lapack --with-external-arpack --with-external-glpk` - it should ensure that igraph links to the system-wide versions of these libraries instead of the bundled ones. If it does not work on Gentoo (or any other major Linux distribution), that's definitely a bug and it should be fixed on our side. Can you point me in the right direction regarding the state of the current Gentoo build and the modifications that the maintainer had to make in order to include it in Gentoo? We are happy to help and streamline the process as long as it does not compromise the Windows builds. (One of the reasons why these libraries are bundled with igraph is to make it easier to compile a version of igraph on Windows that does not lack too much of functionality).

**Comment by tillea** [comment]
Hi,
I can confirm that Debian builds with

    CONF_FLAGS=\
        --enable-gmp \
        --disable-tls \
        --with-external-arpack \
        --with-external-blas \
        --with-external-lapack \
        --with-external-f2c \
        --with-external-glpk

BTW, I've uploaded the package but it resided in the new queue due to the name change that was needed due to the soversion bump.
Thinking about it ftpmaster might reject my upload since I did not specify the copyright information about the (not used) third party code.
Kind regards, Andreas.

**Comment by orlitzky** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/igraph/files/igraph-0.7.1-unbundle.patch

Presumably, the `--with-external-foo` options still work, but there are no options for most bundled libraries:

 * AMD
 * bliss
 * CHOLMOD
 * cliquer
 * COLAMD
 * cs
 * plfit
 * prpack

We have amd, bliss, cholmod, colamd, and cliquer, and cxsparse packages on gentoo. The other two could easily be packaged.

**Comment by szhorvat** [comment]
Several of these libraries had to be modified to make them usable by igraph. This is certainly the case with bliss and cliquer, which I integrated myself. They cannot be just linked to.

These are scientific libraries created by academics, not software engineers. Their authors often don't have the technical expertise and the time to make them into a polished library that is easy to re-use and to compile on any platform.

It is also true for igraph that the target audience is academics, not software engineers. Many (I would say most) do not have the expertise to compile countless dependencies. Bundling even those which are detachable (such as glpk and lapack) provides our users a very important service.  I certainly would not be here today if igraph weren't as easy to build as it is, thanks to bundling all essentials.

Therefore, I do not think what you are asking is a reasonable thing to attempt for igraph.

**Comment by szhorvat** [comment]
Of course, in the case of those pieces of code which come in the form of true libraries, and are well maintained, it would be preferable to make it easy to just link to them. That saves the trouble of updating them. This would be the case with e.g. SuiteSparse, which most of what you mention is actually a part of.

However, here we have another problem: manpower. It is difficult to keep igraph easy to build on all platforms, including Windows. As I said, keeping the package very easy to build is an essential service for our target users, so this must not be compromised.

If you'd be willing to help with detaching some libraries, where that is feasible, without compromising the Windows build or the self-contain build, that would be welcome.

**Comment by szhorvat** [comment]
> https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/igraph/files/igraph-0.7.1-unbundle.patch

It seems the only thing here that we don't already have a configure flag for is the SuiteSparse stuff.

@ntamas I don't have the expertise to judge why changes were needed for the stuff that we already have a `--with-external-xxx` option for.  See the linked patch. Opinions?

Linking to bliss and cliquer is a no-go.

prpack and plfit: I don't know. prpack is no longer being developed. We control plfit fully. Therefore, if we add more `--with-external-something` options, the biggest gains would be from SuiteSparse, as this one is still being improved.

**Comment by ntamas** [comment]
> I don't have the expertise to judge why changes were needed for the stuff that we already have a --with-external-xxx option for. See the linked patch. Opinions?

I think the key difference is that igraph's current configure script simply assumes that the external library can be found by passing a certain linker option (e.g., `-llapack`), and it uses that linker option only. It even attempts to use the linker option if for some reason the configure script reports that a naive compilation attempt won't work (in the hope that the makefile machinery would solve this later).

In contrast, the Gentoo scripts use a more principled approach where it simply asks `pkg-config` for the required compiler and linker flags. The upside is that it works even if the library we depend on is present but requires some additional flags. The downside is that the user needs `pkg-config` for this to work.

I think that when we initially wrote this part of the configuration script, `pkg-config` was not that ubiquitous as it is now, so we did everything by hand. Nowadays it's pretty much present on all Linux systems that developers use, but it's still not a default on macOS. So, switching to `PKG_CHECK_MODULES` would break things for users on macOS. Additionally, it would not be possible to force igraph use a local version of a library by running `LDFLAGS=-L/path/to/my/custom/arpack ./configure --with-external-arpack` because `pkg-config` does not look at `LDFLAGS` - but that's an esoteric use-case and could maybe also be worked around with `PKG_CONFIG_PATH` once we make it documented that igraph uses `pkg-config` for the discovery of third-party dependencies.

So, all in all, I'd love to make this work with less code bloat, and it would be a good idea to go through the Gentoo patch and see whether there are changes that we could upstream. (The usage of `AC_SUBST` for substituting certain lib variables is a good idea, for example). But at the same time we also need to support macOS and `pkg-config` is not an option there in the default installation -- we would need to force users to install Homebrew and then install `pkg-config` from there first.

`--with-external-suitesparse` would also be a nice addition.

**Comment by vtraag** [comment]
On a related note: is this something that we would need/like to address now in the current `autotools` build system, or could we leave it until we switched to a `CMake` build system?

**Comment by ntamas** [comment]
It would be nice to address this now so igraph can be updated in Gentoo.  Right now AFAIK it's stuck at 0.7.1.

**Comment by vtraag** [comment]
OK, that is true. But then strictly speaking we should also create `--with-external-*` options for `amd`,  `cholmod` and `colamd`, right? As @szhorvat said, `bliss` and `cliquer` are no-go's. If we solve the issue for `suitesparse` only (and not for `amd`,  `cholmod` and `colamd`) would that satisfy Gentoo policy so that it could be updated there? Or would the difficulty with `bliss` and `cliquer` prevent it from being included in Gentoo anyway? Could you perhaps clarify @orlitzky?

**Comment by szhorvat** [comment]
> If we solve the issue for `suitesparse` only (and not for `amd`, `cholmod` and `colamd`)

Those are all parts of SuiteSparse

**Comment by szhorvat** [comment]
> Or would the difficulty with `bliss` and `cliquer`

I would not say that there is any difficulty. It was merely a misunderstanding about how these programs can be used as part of another tool.

**Comment by vtraag** [comment]
> Those are all parts of SuiteSparse

Ah, right, sorry, I did not realise that! That clarifies it, thanks.

>>Or would the difficulty with `bliss` and `cliquer` 

>I would not say that there is any difficulty. It was merely a misunderstanding about how these programs can be used as part of another tool.

From the earlier [comment](https://github.com/igraph/igraph/issues/1284#issuecomment-592193150) by @orlitzky 
> We have amd, bliss, cholmod, colamd, and cliquer, and cxsparse packages on gentoo. The other two could easily be packaged.

This refers to `bliss` and `cliquer` as well, right? There is no reply yet by @orlitzky to your explanation that `bliss` and `cliquer` cannot be linked to, so I am wondering if this will not pose a problem when including it in Gentoo.

**Comment by szhorvat** [comment]
As I understand, there is no hard *technical* problem, merely a preference to reduce duplication.

**Comment by vtraag** [comment]
I understand there is no technical problem. 

I mean, it might be a waste of time to fix using SuiteSparse as an external dependency, if it turns out that Gentoo is not willing to accept `igraph` with a bundled version of `bliss` and `cliquer`. Perhaps you find it sufficiently useful to introduce `--with-external-suitesparse` now (i.e. before switching to `CMake`), in which case go for it. But if the only reason to do so now is to get it in Gentoo, it might be worth double-checking whether it will be accepted if `--with-external-suitesparse` is introduced.

**Comment by orlitzky** [comment]
What problem is there with using the system copies of bliss and cliquer? I don't know about bliss personally, but SageMath is able to link against the system cliquer without problems -- that's why we have cliquer in the first place.

Since we already have packages for bliss and cliquer, it looks especially bad if you've bundled _those_ libraries, because the hypothetical "what if `sci-libs/bliss` gets an update?" stops being hypothetical. It's probably possible to undo the bundling (pending an answer to my question above), but then we're back at the bottom line: how much time is someone willing to spend on this whenever there's a release?

**Comment by szhorvat** [comment]
> how much time is someone willing to spend on this whenever there's a release?

This is one of the major problems. We don't have the resources to spend on something like this.  As a maintainer for Gentoo, please consider igraph to stay in the current state for a while.

Do note that most libraries which make sense to be unbundled already *can* be, with the above mentioned configure flags.  If we are going to tackle more of these, I think it makes sense to start with SuiteSparse. This is the only library which gets regular updates, and where those updates would bring tangible benefits to users. This is also the only one which the existing patch in Gentoo touches on.  That said, personally I would not prioritize this over other, more pressing tasks, *at this moment*. However, if you can offer any help, it would be welcome.



> What problem is there with using the system copies of bliss and cliquer?

I don't think this is the best place to discuss the details of why cliquer is bundled, but I hope you'll trust me that it was not an arbitrary decision.

A few points:

 - It's not a real library; It's just a collection of .c files, set up to build a command-line tool.
 - It prints errors to the terminal. This is not acceptable for igraph.
 - It calls `abort()` when things go wrong. Also not acceptable. 
 - We needed to make it interruptible, after all clique finding has exponential complexity.
 - Other modifications were also needed such as supporting thread-local storage. I don't recall every detail.

Thus, as I said in my previous posts: many small modifications are needed before this code becomes suitable for integrating into igraph.

The same applies to bliss.

**Comment by orlitzky** [comment]
> Thus, as I said in my previous posts: many small modifications are needed before this code becomes suitable for integrating into igraph.

Several of those improvements look useful generally. To beat a dead horse: the fact that you've bundled them in igraph rather than sending them "upstream" prevents us from sharing the benefits. The first step should be to try to send the fixes the original authors. If they're no longer interested in maintaining the project, then a fork is an eventual plan (b). That's what happened with cliquer to turn it into a real library with a test suite: https://github.com/dimpase/autocliquer

I'm sure the thread-local storage, `abort()`, and interruptibility patches in particular would be welcome PRs. We all have similar needs and it saves a lot of time in the long run if we work together.

**Comment by szhorvat** [comment]
@vtraag The one blocker on this was conda. Is it done now and can this issue be closed?

**Comment by vtraag** [comment]
Yes, sorry, it is [upgraded](https://anaconda.org/conda-forge/igraph) and this can be closed.
