### ISSUE TITLE
Functions that have documentation but are not included in the docs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1297]
edits by Fabio: some updates

The following is a list of functions that have their documentation written up, but it is not included in the generated documentation pages.

If you include one, tick the box. Feel free to add more that you find. If there is a reason *not* to include one, please comment here.

**in R** marks those that are included in the R interface, which shows that they were not meant for internal use only. Lack of marking does not mean that the function is not included in a higher level interface.

 - [x] igraph_modularity_matrix **in R**
 - [x] igraph_laplacian_spectral_embedding **in R**
 - [x] igraph_dim_select **in R** — <del>this one is present in `embedding.xxml` but doesn't show up in the generated docs for some reason</del> Update: fixed.
 - [x] igraph_gomory_hu_tree **in Py**
 - [x] igraph_lastcit_game **in R**
 - [x] igraph_simple_interconnected_islands_game **in R**
 - [ ] igraph_set_... (let's skip these - see below)
    * igraph_set_init
    * igraph_set_destroy
    * igraph_set_inited
    * igraph_set_reserve
    * igraph_set_empty
    * igraph_set_clear
    * igraph_set_size
    * igraph_set_add
    * igraph_set_contains
    * igraph_set_iterate
 - [x] math (maybe not - see below)
    * igraph_almost_equals
    * igraph_cmp_epsilon
 - [x] igraph_maximal_cliques_subset — incomplete doc comment
 - [x] igraph_rng_get_gamma
 - [ ] igraph_even_tarjan_reduction — incomplete doc comment
 - [ ] igraph_vector_order — Note: only for `vector_t`, not for `vector_int_t`, etc.
 - [x] igraph_local_scan_... [**in R**](https://igraph.org/r/doc/local_scan.html)
   - [x] igraph_local_scan_0
   - [x] igraph_local_scan_1_ecount
   - [x] igraph_local_scan_0_them
   - [x] igraph_local_scan_1_ecount_them
   - [x] igraph_local_scan_k_ecount
   - [x] igraph_local_scan_k_ecount_them
   - [x] igraph_local_scan_neighborhood_ecount

**Comment by ntamas** [comment]
Re `igraph_set_*`: I think these functions were not mature enough to be part of the public interface - I added them a long while ago simply because I needed a set data type for some algorithm. They are probably not optimized enough yet.

Re `igraph_maximal_cliques_subset` and `igraph_even_tarjan_reduction`: these functions lack proper documentation, only the headings are there.

**Comment by iosonofabio** [comment]
`igraph_set_*` is the topic of PR #1429. Basically there's a general discussion as of which data types that are currently internal (like this one) should become public instead.

Since that discussion is likely to take a little while until convergence, let's ignore those functions for now: they are documented, but we won't add them to the generated documentation in this round.

**Comment by iosonofabio** [comment]
The two functions in `math.c` are also a special case, because
1. we don't have a math section in the docs (should we??)
2. no other math functions are documented

So basically let's either create a math section in the docs and document a bunch of those, or skip them. Preferences?
