### ISSUE TITLE
igraph_random_sample.c test failure

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#1302]
The test case in `examples/simple/igraph_random_sample.c` [failed on Appveyor today](https://ci.appveyor.com/project/ntamas/igraph/builds/30377785/job/0gopxk7j21tfaut4). Upon closer investigation, I don't even have an idea about how the test case is supposed to work anyway.

The faiing test case is case #2 in `error_test()`, where we apparently draw two random numbers from the range [-1000; 1000], and then call `igraph_random_sample()` between these two random numbers as lower and upper bounds, and a desired random sequence length that is equal to `(high - low)` * `(high-low)`, assuming that the test should always fail with `IGRAPH_EINVAL`. However, I think this is not the case; in particular, if `high = low + 1`, the desired random sequence length is 1, which is totally feasible.

Can someone (@vtraag or @szhorvat) please take a look at `igraph_random_sample.c` between lines 66 and 81 to see if I am interpreting things correctly?

Might also be related to #596 (closed recently) and the failure noted by @szhorvat [here](https://ci.appveyor.com/project/ntamas/igraph/builds/30228621/job/xxahc4hl3x81hb75).

**Comment by vtraag** [comment]
I think you are right @ntamas. If `high=low + 1`, then `length = 1`, which is identical to the candidate pool size.

Frankly, I would prefer to have deterministic tests, not random tests. Otherwise, when a test fails, we are debugging the test, rather than the underlying problem.

I would therefore suggest to change this test. The tests are simple: (1) pass an impossible interval, where the upper bounds is lower than the lower bound; (2) pass a requested sample size that is larger than the pool from which can be sampled. This is easy to make deterministic, and I don't understand what the use of the random lower and upper bounds adds here. I'll push this shortly.
