### ISSUE TITLE
Implement "harmonic centrality"

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1373]
The harmonic centrality of a vertex is the average inverse distance to all other vertices.

https://en.wikipedia.org/wiki/Closeness_centrality#In_disconnected_graphs

https://igraph.discourse.group/t/user-defined-distance-for-unconnected-node-in-closeness-and-harmonic-centrality/183

**Comment by Silmathoron** [comment]
To give a bit of context, the harmonic definition of closeness centrality (sometime only called "harmonic centrality") provides a slightly different formula by taking the sum of the inverse distances instead of taking the inverse of the sum.

This definition is associated to the convention of infinite distance between non-connected nodes such that the inverse distance is zero.

Contrary to the arithmetic definition of the closeness centrality which has issues when the out- or in-component of all nodes is not the whole graph (see #1053), the harmonic version is well defined in all cases.

This version of the closeness centrality is present [in graph-tool](https://graph-tool.skewed.de/static/doc/centrality.html#graph_tool.centrality.closeness) via the ``harmonic`` keyword and is implemented separately as [``harmonic_centrality`` in networkx](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.harmonic_centrality.html)

**Comment by szhorvat** [comment]
This is now implemented (#1583) and will be part of the 0.9, planned for later winter.
