### ISSUE TITLE
CI tests with x87 math

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1387]
Given the problems we had with the test suite on Debian running on non-common platforms, it would be useful to add CI tests that use x87 math (not SSE). This can be done in 64-bit mode, using the compiler flag I showed in #1371 (`-mfpmath=387`). @ntamas, opinions?

**Comment by ntamas** [comment]
Seems OK to me, although the CI tests are taking a lot of time now even without this, and I'm not sure whether there are any time limits on Travis that we should obey.

It would be great if we could cut down the time it takes for CI tests to run (also because of faster feedback during development). This also connects to my other suggestion in the forum (in the CMake-related topic) where I proposed dropping vendored libraries from igraph and just relying on whatever versions the host OS provides. This would mean that we don't need to compile GMP, GLPK, BLAS, LAPACK et al during CI tests, saving some time that we could then spend on testing x87 math instead.

**Comment by vtraag** [comment]
>  I proposed dropping vendored libraries from igraph and just relying on whatever versions the host OS provides.

I believe you mentioned the suggestion to drop vendored libraries [here](https://github.com/igraph/igraph/pull/1384#issuecomment-632614860). I think it is an important topic that should be discussed. It is not yet on our [forum](https://igraph.discourse.group/), perhaps you could open a new topic for that under the Development category? That way everybody can chip in. I think there are good arguments in favour of it, but there may also be some good arguments against it.

**Comment by ntamas** [comment]
You are right; I wanted to start a thread but forgot to do it in the end -- here's the [topic](https://igraph.discourse.group/t/dropping-vendored-libraries-from-the-igraph-source-tree/240) on the forum now that I finally managed to create it.

**Comment by szhorvat** [comment]
> Seems OK to me, although the CI tests are taking a lot of time now even without this, and I'm not sure whether there are any time limits on Travis that we should obey.

The time limit is 50 minutes per job, but there is no time limit per build:

https://docs.travis-ci.com/user/customizing-the-build#build-timeouts

We can add it as separate job. It will run in parallel to the other jobs, so it won't slow anything down.

We should also make the documentation build not a stage, but a job, so that it can run in parallel, and we do not need to bother with it.

I sort of got this working in my own fork. Should I send a PR or just go ahead and commit the change?

One problem is that with x87, one test fails again 😠
