### ISSUE TITLE
igraph_modularity: special handling of directed graphs in R

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1389]
`igraph_modularity` handles directed graphs differently when compiling for R (`USING_R`) than otherwise.

See here:

https://github.com/igraph/igraph/blame/master/src/community.c#L920

Normally, it throws an error. In R, it effectively shows a warning (`REprintf`).

It would be good to get rid of the special behaviour for R.

Which solution should we choose then?

 1. Change the error into a warning? (What R does now.)
 2. Keep it as an error? (What everything else does now.)

@gaborcsardi, any opinions on this?

Personally, I think we should go with 1. if there are any community detection methods that ignore edge directions. Otherwise, we should go with 2. to protect users from errors.

**Comment by gaborcsardi** [comment]
2. is a breaking change, so I don't think I'll do that.

**Comment by szhorvat** [comment]
It looks like `igraph_community_edge_betweenness` has a `directed` argument. If true, directed edge betweenness is computed. But this function also calls `igraph_modularity`, many times. If `modularity` errors for directed graphs, that makes the `directed` argument of  `community_edge_betweenness` pointless.

Based on this, only 1. would make sense.

It does have an unpleasant effect of producing many warnings, but not showing repeated warnings is something that the high-level interfaces should deal with (Python does, I think):

```
> g<-erdos.renyi.game(10,20,'gnm',directed = T)
> plot(g)
> cluster_edge_betweenness(g)
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
IGRAPH clustering edge betweenness, groups: 2, mod: 0.049
+ groups:
  $`1`
  [1]  1  2  4  6  8  9 10
  
  $`2`
  [1] 3 5 7
```

However, I do wonder if the Girvan–Newman approach makes any sense for directed graphs at all. @vtraag are you aware of any prior work on this (or any opinions)?

**Comment by szhorvat** [comment]
Related: https://github.com/igraph/igraph/issues/1358

But we can turn that error into a warning before directed modularity is properly implemented.

**Comment by vtraag** [comment]
Please note that in https://github.com/igraph/igraph/pull/1386/commits/fc9320ea990ea01cf6f6d2b936b1899f9c1b7ed8 (part of PR #1386) I actually already started to simply raise an error (I didn't give it much thought). We need to make sure to correct that then (perhaps already before we merge that PR).

>  I do wonder if the Girvan–Newman approach makes any sense for directed graphs at all. 

You mean for using the directed betweenness in order to find a sensible split? I think that would make sense in general. Clearly, the modularity values are not in agreement in that case, which makes sense. Throwing a warning for now in `igraph_modularity` is the best option I think, until we (I) have fixed #1358.

**Comment by szhorvat** [comment]
@vtraag I'll push to that PR then.

**Comment by vtraag** [comment]
@szhorvat, OK, I will wait for your commit and then review + merge.

**Comment by AprilSong0323** [comment]
Hi,

I am having the same issue with directed graphs and following is the code and the results I get.

For directed graph:

g <- sample_pa(100, m = 2, directed = TRUE)
eb <- cluster_edge_betweenness(g)

it returns:

Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.
Modularity is implemented for undirected graphs only.

Anyone could help with this?

**Comment by ntamas** [comment]
This is not a support forum but an issue tracker; if you have support questions, please ask them in our [discussion forum](https://igraph.discourse.group) where you are more likely to get help.

In this particular case, you need to use `eb <- cluster_edge_betweenness(g, modularity=FALSE, membership=FALSE)`. This is because edge betweenness clustering is a _hierarchical_ method, i.e. it produces a dendrogram by default and not a single clustering. In order to obtain an optimal clustering from the dendrogram, igraph turns to the modularity score and looks for a place in the dendrogram where the current partition yields the highest modularity score. However, modularity is not implemented for directed graphs (and there are several competing variants in the literature, none of them were ever tested with the edge betweenness clustering algorithm as far as I know), so that's why you see tons of warnings in the output. Setting `modularity=FALSE, membership=FALSE` prevents igraph from calculatng the modularity scores so you only get the dendrogram. You can then evaluate the merge matrix of the dendrogram with `merges(eb)` or turn it into an R dendrogram with `as.dendrogram()`. See [this page](https://igraph.org/r/doc/communities.html) for more details about the object returned from `cluster_edge_betweenness`.
