### ISSUE TITLE
Documentation system does not tolerate spaces in macro arg list

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1414]
If a macro is defined with spaces in its argument list, e.g.

```
#define IGRAPH_OTHER(graph, eid, vid) ...
```

then the definition will be cut off at the first space in the documentation. With the above, we get the following in the docs:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/1212871/84431876-53a3be80-ac2c-11ea-888f-7d34607a6d5d.png">

The workaround is to remove spaces:

```
#define IGRAPH_OTHER(graph,eid,vid) ...
```

Low priority, as it's only cosmetic.

**Comment by ntamas** [comment]
This is the regex in `doc/c-docbook.re` that takes care of parsing the macro:

```
REPLACE ----- \define ---------------------------------------------------------
(?P<before>\A.*?)                 # head of the comment
\\define\s+                       # \define command
(?P<name>(?P<pre>(igraph_)|(IGRAPH_)|())(?P<tail>\w+))
[\s]*(?P<brief>[^\n]*?)\n         # brief description
(?P<after>.*?)\*\/                # tail of the comment
\s*                               # whitespace
(?P<def>\#define\s+[\w0-9,()]+)           # macro
.*\Z                              # drop the remainder
WITH --------------------------------------------------------------------------
...
```

(Python regex syntax).

As you can see, the problem is that the macro is parsed like this:

```
(?P<def>\#define\s+[\w0-9,()]+)
```

where the macro is basically defined with `[\w0-9,()]`, so no spaces allowed. The upside is that we can easily separate the "body" of the macro because that's what comes after the second space.

I'll try to find a workaround but no promises.
