### ISSUE TITLE
Implicit function declarations for lapack and blas and community_leiden.c

### ISSUE THREAD

**Issue by epsilon-0** [igraph/igraph#1471]
When compiling I get the following warnings on Gentoo

```
 * community_leiden.c:428:17: warning: implicit declaration of function ‘igraph_i_vector_binsearch_slice’; did you mean ‘igraph_vector_binsearch2’? [-Wimplicit-function-declaration]
 * ./igraph_lapack_internal.h:86:29: warning: implicit declaration of function ‘dsyrk_’ [-Wimplicit-function-declaration]
 * ./igraph_lapack_internal.h:120:29: warning: implicit declaration of function ‘dpotrf_’; did you mean ‘zpotrf_’? [-Wimplicit-function-declaration]
 * ./igraph_blas_internal.h:50:29: warning: implicit declaration of function ‘dtrsm_’; did you mean ‘ztrsm_’? [-Wimplicit-function-declaration]
 * ./igraph_blas_internal.h:51:29: warning: implicit declaration of function ‘dtrsv_’; did you mean ‘ztrsv_’? [-Wimplicit-function-declaration]
 * ./igraph_blas_internal.h:50:29: warning: implicit declaration of function ‘dtrsm_’; did you mean ‘ztrsm_’? [-Wimplicit-function-declaration]
```

The full build log is present at https://openpgpkey.epsilonknot.xyz/igraph_implicit.error

If I can provide any more information, I'd be happy to help!

---
Make sure that these boxes are checked before submitting your issue -- thank you!

- [x] This issue is for the C core of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

**Comment by szhorvat** [comment]
The first one is already fixed.

The rest is still present, I can see them when building with external blas/lapack only: https://travis-ci.org/github/igraph/igraph/jobs/728639682

**Comment by szhorvat** [comment]
Personally, I don't think it's worth spending time on these right now because:

 - The library compiles correctly (they're merely warnings)
 - We are transitioning to a cmake-based build system an on the cmake branch, I do not see the warning (though I don't know if they have simply been silenced)
 - Implicit declarations are a danger only when modifying code. There is a risk of accidentally calling the functions with the wrong arguments. These warnings are all from bundled libraries (SuiteSparse) in which we don't normally touch code. The `igraph_i_vector_binsearch_slice` is different, as that's in the main igraph code, but that one is already fixed (the fix will be in the soon-to-be released version 0.8.3).

**Comment by epsilon-0** [comment]
Ah, thats fine.
Just confirming that these are actual warnings and not because of my mistake is good enough :)

**Comment by szhorvat** [comment]
Yes, these are warnings and do not impact the functionality of the package. You can safely ignore them.
