### ISSUE TITLE
CMake: when building a shared library, tests don't run on MSYS2

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1501]
When building a shared library, tests don't run on MSYS2 due to `libigraph.dll` not being present on the `PATH`.

@vtraag I thought you mentioned fixing this recently, but maybe I misremembered.

**Comment by vtraag** [comment]
This is one of those things that was restricted to `MSVC` (cf. https://github.com/igraph/igraph/issues/1495), I didn't expect this to be necessary also MinGW compilations. I'll fix it.

**Comment by vtraag** [comment]
Hm, it seems that the situation is a bit more complicated than simply replacing `MSVC` with `WIN32`. The path still does not get set correctly because CMake produced the path with forward slashes, which seems to be incorrectly interpreted when running the tests. I now also explicitly added the relevant directory to the path, but it then still does not run with `ctest`:

```
1: Test command: C:\msys64\home\traagva1\build\igraph-shared\tests\test_igraph_version.exe
1: Environment variables:
1:  PATH=C:/msys64/home/traagva1/build/igraph-shared/src
1:  C:\msys64\home\traagva1\build\igraph-shared\src;C:\msys64\mingw64\bin
1:  C:\msys64\usr\local\bin
1:  C:\msys64\usr\bin
1:  C:\msys64\usr\bin
1:  C:\Windows\System32
1:  C:\Windows
1:  C:\Windows\System32\Wbem
1:  C:\Windows\System32\WindowsPowerShell\v1.0;C:\msys64\usr\bin\site_perl
1:  C:\msys64\usr\bin\vendor_perl
1:  C:\msys64\usr\bin\core_perl
1: Test timeout computed to be: 1500
1/1 Test #1: igraph_version ...................Exit code 0xc0000135
***Exception:   0.01 sec
```
The strange thing is that is is run correctly when running the actual binary (i.e. the DLL is then correctly found).

**Comment by vtraag** [comment]
Even manually copying the binary DLL to the test directory does not work.

**Comment by vtraag** [comment]
Have you are managed to run tests using `ctest` under these conditions @szhorvat?

**Comment by vtraag** [comment]
OK, finally figured it out I think: `ctest` launches tests inside a Windows environment, not within an msys2 environment. It is then missing DLLs from the `/mingw64/bin` directory. Hence, the path (usually something like `C:\msys64\mingw64\bin`) should be added to the Windows path. I am not sure if we should try to add this path in CMake?

**Comment by ntamas** [comment]
Can we detect the path (i.e. `C:\msys64\mingw64\bin`) reliably somehow without using educated guesses? If so, we should try to do everything that we can to make sure that `ctest` runs without the user having to manipulate the PATH explicitly (probably by making sure that the PATH is extended before `ctest` is called). If there is no way to detect this path (e.g., from envvars), then let's just leave it.

**Comment by vtraag** [comment]
Hmm, setting explicitly the path also does not solve the issue, it almost seems as if the `PATH` used by `ctest` is not properly set (or uses incorrect PATHS, i.e. it should use unix-style pathnames).

**Comment by szhorvat** [comment]
Yet if I run `ctest --verbose`, it does print the path I expect. I don't understand what goes wrong.

**Comment by vtraag** [comment]
I understand the problem now I think: it takes the `PATH` from the Windows environment, which has `;` as a path separator. Is is then interpreted by `CMake` as a list, instead of as a single `PATH` or something like that. It seems that for MinGW we need colon (`:`) style separation, I will try to implement this.

Indeed I also see the correct paths, but they are printed on different lines. Using different path separators results in a single continuous line with the path separators visible.

**Comment by vtraag** [comment]
OK, this was more complicated than I imagined. When using `SET_TESTS_PROPERTIES( ${NAME} PROPERTIES ENVIRONMENT "PATH=${IGRAPH_LIBDIR};$ENV{PATH}" )` CMake interprets `"PATH=${IGRAPH_LIBDIR};$ENV{PATH}"` as a list, separated by `;`. Hence, it considers the different items as separate arguments to `SET_TESTS_PROPERTIES`. Only the first items is considered an argument for `PATH`, and the others paths are hence used as properties for the environment, without any effect on `PATH`. Unfortunately, making `$ENV{PATH}` into a colon-separated argument (and adding `${IGRAPH_LIBDIR}`) is also misinterpreted, apparently because it *needs* a semicolon-separated argument. The solution is to use escaped semicolons it seems (`\;`).

Additionally there was yet another error: the "native" path was still interpreted to need forward slashes, but unfortunately `ctest` requires backslashes in this case (presumably because it is run inside a Windows shell, `cmd.exe`). Hence `file(TO_NATIVE_PATH ...)` didn't work correctly, and I now manually corrected the path using a `REPLACE`.

**Comment by ntamas** [comment]
Great, I'm glad to hear that.

The issue with the semicolons is a common CMake problem; CMake lists were probably added to the "language" as an afterthought and that's why they are essentially glorified strings that use semicolons as a separator. It is easy to get bitten by that if you work with Windows-style paths.

**Comment by szhorvat** [comment]
Windows actually accepts forward slashes in almost all contexts. The standard Windows API functions certainly do, and they have always worked in `cmd.exe` as well. I'm surprised that that was necessary.

Thanks so much for figuring this out Vincent, this was a lot of work!
