### ISSUE TITLE
fail to get vertex through edge!

### ISSUE THREAD

**Issue by 584251395** [igraph/igraph#1522]
//get edge list
    igraph_es_t esedge= igraph_ess_all(IGRAPH_EDGEORDER_ID);
    igraph_eit_t eitedge;
    
    //igraph_es_all(&esedge, );
    igraph_eit_create(g, esedge, &eitedge);
    while (IGRAPH_EIT_END(eitedge) == 0) {
        int id=IGRAPH_EIT_GET(eitedge);
        cout << eitedge.start << "->" << eitedge.end <<":"<< id<< endl;
        print_vector(eitedge.vec);

        IGRAPH_EIT_NEXT(eitedge);

    }

**Comment by szhorvat** [comment]
We would like to reserve the issue tracker for bug reports and feature requests. Please use the forum for support questions: https://igraph.discourse.group/ Make sure you described what the problem is in detail, and [show a complete minimal example](http://sscce.org/). 

Also, please refrain from creating multiple issues with the same text (#1523).
