### ISSUE TITLE
prpack returns pointer to variable that goes out of scope

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1525]
prpack returns a pointer to a variable that goes out of scope

`res->method` is set here:

https://github.com/igraph/igraph/blob/master/src/prpack/prpack_solver.cpp#L240

Note that `m` is a local variable, and it will be destroyed when the function is done. Yet `ret` is returned. If `ret->method` is accessed at a later point, it may cause a crash.

**Comment by szhorvat** [comment]
A robust fix would be to use a pointer to one of the constant strings that appear within the function.

Since this problem is not triggered in igraph, we should probably just report to upstream at the moment.

**Comment by ntamas** [comment]
Note that a branch in the function appends `_uv` to one of the constants if certain conditions hold, so we cannot simply return one of the predefined constants (or we need to create a table in advance with all the possible method names, with and without the `_uv` suffix).

IMHO in igraph we could simply make the `method` member of `prpack_result` into a `string` instead of a `const char*`; we don't use it anyway but at least it would then work without problems and take care of releasing its own memory.
