### ISSUE TITLE
igraph_is_connected() and null graphs

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1539]
I opened this issue to discuss changing `igraph_is_connected()` to return `false` for the null graph. The null graph is the graph with no vertices.

There is no one clearly correct answer to the question of whether the null graph is connected. It is, of course, a question of convention. However, it is a common opinion that it should be considered disconnected:

 - https://math.stackexchange.com/a/50552/12384
 - [Is the null graph a pointless concept?](https://link.springer.com/chapter/10.1007%2FBFb0066433) by Harary and Read

The usual argument for considering the null graph not to be connected is that some of the properties that connected graphs with at least one vertex have break down for the null graph. One might explicitly make the exception for the null graph when discussing or defining those properties, or one might simply not consider the null graph connected. 

I think that in igraph we should make `igraph_is_connected()` return `false` for the null graph for the same reason: consistency with other functions.

To give an example, a classic argument (also in the paper I mentioned above) is this: A forest is a graph with no cycles. A tree is a connected graph with no cycles. Generally, a tree has one more vertex than edges, V = E+1. This is not true for the null graph. It makes sense to consider the null graph a forest, but not a tree, by convention, so that the V = E+1 property can hold for all trees. This is exactly what `igraph_is_tree()` does in igraph.

In order to avoid having to deal with these issues, some graph theory authors simply require at least one vertex in their definition of a graph.

----

Now we are not writing a graph theory book. We are writing graph theory software. So the considerations are different: **what is useful and safe (i.e. likely to prevent, rather than cause bugs) to users?**  

Not supporting zero-vertex graphs is not useful: it goes against expectations and would create many inconvenient error conditions, such as deleting the vertex of a singleton graph throwing an error. Thus, we *should* support null graphs (and we do).

Imagine this situation: A user is implementing a new function, using igraph's functionality. They assume that connected graphs have a number of properties that are required for the successful completion of the algorithm. Thus they write their function with `if is_connected(g) do X else ERROR`. But many of the properties that one might take for granted for connected graphs break down for the null graph, so it is likely that their function will fail in _unexpected_ ways when passing the null graph to it. To prevent this, the user: 1. has to remember this special case 2. has to implement this special case.

I assert that the safer, more user-friendly solution is that `is_connected(null_graph)` return `false`. A user who does think of special cases can still implement a nicer behaviour in their function for null graphs. A user who doesn't won't end up with a function that fails in strange ways.

One example: it is a natural assumption that a connected graph should have a diameter path, but the null graph does not. It has no paths, not even paths of length zero, in it. Compare with the singleton graph which has a path of length 0, consisting of a single vertex.

----

To be fair, I should note that no other software I have tried makes this choice. However, it is likely that they did not even consider the question seriously. I maintain that the better way is to consider the null graph disconnected.

----

Arguments against making this change:

 - Many other functions in igraph rely on `igraph_is_connected`, we must not break them. **Answer:** True, and I will check all such functions. Maybe I will even discover some edge-case behaviour that needs to be corrected. That will be a win.

 - Such a change may break existing user code. **Answer:** Since this edge case is commonly forgotten, I believe that this change is just as likely to fix existing user code as to break it.

**Comment by ntamas** [comment]
I went through the codebase to check where we are calling `igraph_is_connected()` for any reason. These are the places that I've found:

* Fruchterman-Reingold layout: does not seem to cause any problems as most of the function body is skipped when the graph is a null graph. The only place where we might run into problems is the initialization of vectors with zero lengths, but that's a different topic, unrelated to `igraph_is_connected()`.

* Spinglass clustering: this one needs connected graphs (in `igraph_i_community_spinglass_orig()`), hence the check, but the case of the null graph is trivial so we have to treat this separately before calling one of the internal implementations.

* Girth: we need to decide what the girth of the null graph is. I vote for zero because `igraph_girth()` returns integers so we can return neither `NaN` nor infinity. Otherwise I would prefer `NaN`.

* "Fluid communities" algorithm: again, we need to handle the null graph as a special case.

* `igraph_i_connectivity_checks()` calls `igraph_is_connected()`, but it is already preceded by a check for the null graph so it's okay.

* `igraph_layout_mds()` calls `igraph_is_connected()`, but it can never reach that code path with the null graph because there's no valid value for the `dim` (dimensionality) argument with a null graph.

Furthermore, some community detection algorithms (like the "fluid communities" algorithm) have an out-parameter named `modularity`, and we need to return something there for null graphs. I propose returning zero as the modularity formula is simply a sum-of-things, and sum-of-nothing is zero. We also need to ensure that `igraph_modularity()` returns zero for null graphs for sake of consistency.

If there are no objections, I'll move ahead with the changes outlined above.

**Comment by szhorvat** [comment]
Agreed with everything, except the modularity. I don't _disagree_ with that either, I just need to think it through, as it's divided by the number of edges, which is zero even for the singleton graph, or any graph consisting of isolated vertices.

**Comment by ntamas** [comment]
Hmmm, you have a point there. Zero divided by zero is usually `NaN`, so how about `NaN` then?

**Comment by ntamas** [comment]
@szhorvat Did you have time to think it through? I'm torn between 0 and `NaN`; `NaN` seems logical from a mathematical point of view, but 0 aligns better with my intuition.

**Comment by vtraag** [comment]
Sparse graphs can have a high modularity:

Bagrow, J. (2012). Communities and bottlenecks: Trees and treelike networks have high modularity. Physical Review E, 85(6), 9. https://doi.org/10.1103/PhysRevE.85.066118

Hence, the limit depends on the exact partition that you take. The expected modularity will be 0 for a random graph over any fixed partition of course, however, for any given graph there exists a partition with distinctly higher modularity. Depending on how you approach the limit of no edges, you will then either approach it from above or from zero. Any particular limit value does not seem to make sense to me.

For modularity, I would hence suggest `NaN`.

**Comment by ntamas** [comment]
`NaN` it is then -- I will link the documentation to this issue so we will remember what the reasoning behind the decision was.

**Comment by szhorvat** [comment]
In the stochastic block model graph example I gave, the modularity necessarily goes to zero as p decreases, as for very low p, we will have mostly zero-degree vertices and a handful of degree-1 vertices. The probability that any partition would have more than one degree-1 vertex goes to zero.  However, this breakdown happens only when the number of non-zero-degree vertices becomes comparable to the number of partitions. For denser graphs, Q is effectively unchanged even for very small p.

Furthermore, we can have high modularity values for _some_ very sparse graphs. Consider the case when all degrees are zero except four, which are 1. Two of these deg-1 vertices are in one partition, the other two in another. Additionally, we may have any number of empty partitions. The modularity will be 0.5, which is a high value.

I also (cautiously) support returning `NaN`.

**Comment by szhorvat** [comment]
The next user complaint will be: "I generated a billion random graphs and computed the average modularity and why is it NaN!?!" Because just one of those billion happened to be an edgeless graph. Still, I do support returning NaN.

**Comment by ntamas** [comment]
We can print a warning for edgeless graphs, something along the lines of `Modularity is not well-defined for graphs without edges` -- at least the user would know that some edge case was not considered when the first edgeless graph is generated out of those one billion.

**Comment by szhorvat** [comment]
I think just going with NaN is fine.
