### ISSUE TITLE
igraph_convergence_degree should be documented

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1654]
There is an undocumented but public and tested `igraph_convergence_degree` function. What does it do? This should be documented.

It is exposed through the Python interface, but not documented there either:

https://igraph.org/python/doc/igraph.GraphBase-class.html#convergence_degree

**Comment by GroteGnoom** [comment]
Some more information can be found here:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2603227/
"Convergence and divergence are mostly reciprocated properties of the connections in the network of cortical areas"
By László Négyessy, @ntamas et al. :slightly_smiling_face:

**Comment by szhorvat** [comment]
I think @ntamas was of the opinion that this was perhaps too niche to keep (it never caught on), which is why I left it to the stale bot to close. Personally, I think it wouldn't be a bad thing to keep it if @ntamas is happy to maintain it. It's different from an outsider contributing something and never coming back again.

**Comment by ntamas** [comment]
I surrendered to the popular demand ( ;) ) and added documentation for `igraph_convergence_degree()` in c207c7707. I'm not sure where to put it in the manual, though - I added it under "centrality measures" for the time being because it behaves similarly to edge betweenness (actually, this was our main inspiration at that time, we were explicitly looking for edges that had both high betweenness and high convergence degree), but it could have also gone under "shortest paths". I don't think it warrants a separate heading on its own so I ruled that out. Feel free to move it elsewhere.
