### ISSUE TITLE
Some SCG tests fail on linux aarch64

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#1694]
**Describe the bug**
Two tests fail when compiled on Linux aarch64. This is a build on Anaconda (`conda-forge`) using the following configuration:

<details>
<summary>Configuration</summary>

```
-- -----[ Build configuration ]----
-- Version:      0.9.0-dev+6bb4e76c
-- CMake build type:        Release
-- Library type:             shared
--  
-- ----------[ Features ]----------
-- GLPK for optimization:       yes
-- Reading GraphML files:       yes
-- Thread-local storage:        yes
-- Link-time optimization:      yes
--  
-- --------[ Dependencies ]--------
-- ARPACK:                 vendored
-- BISON:                        no
-- BLAS:                        yes
-- CXSparse:                    yes
-- FLEX:                         no
-- GLPK:                        yes
-- GMP:                         yes
-- LAPACK:                      yes
-- LibXml2:                     yes
--  
-- -----------[ Testing ]----------
-- Diff tool:                  diff
-- Sanitizers:                 none
-- Code coverage:                no
-- Verify 'finally' stack:       no
--  
-- --------[ Documentation ]-------
-- HTML:                         no
-- PDF:                          no
```

It links to blas `3.8 *netlib`, which is used as a stand-in package that can be replaced by MKL or OpenBLAS by a user, see `conda-forge` [documentation](https://conda-forge.org/docs/maintainer/knowledge_base.html#blas) for details. It also links to external suitesparse 5.6.0. Both of these libraries are provided by Anaconda `conda-forge`.

</details>

The two tests that fail are:

<details>
<summary><code>igraph_scg_grouping3</code></summary>

```
305/327 Test #305: example::igraph_scg_grouping3 .....................***Failed    0.06 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- $SRC_DIR/examples/simple/igraph_scg_grouping3.out	2021-02-16 14:59:33.000000000 +0000
+++ $SRC_DIR/build/tests/example_igraph_scg_grouping3.out	2021-02-24 08:02:41.385775467 +0000
@@ -1,4 +1,4 @@
-0 0 0 1 0 1 0 2 2 2
+0 0 1 1 0 1 0 2 2 0
 0 1 1 1 1 1 0 2 2 0
 0 1 1 1 1 1 0 2 2 0
 0 1 2 3 4 5 6 7 8 9
-- -------------------------------------------------------
CMake Error at $SRC_DIR/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.
```
</details>

<details>
<summary><code>igraph_scg_semiprojectors2</code></summary>

```
308/327 Test #308: example::igraph_scg_semiprojectors2 ...............***Failed    0.07 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- $SRC_DIR/examples/simple/igraph_scg_semiprojectors2.out	2021-02-16 14:59:33.000000000 +0000
+++ $SRC_DIR/build/tests/example_igraph_scg_semiprojectors2.out	2021-02-24 08:02:41.557762598 +0000
@@ -1,11 +1,11 @@
 ----------------------
-0.222222 0.222222 0.111111 0 0.222222 0 0.222222 0 0 0
-0 0 0 0.333333 0 0.666667 0 0 0 0
-0 0 0 0 0 0 0 0.166667 0.333333 0.5
+0.181818 0.181818 0 0 0.181818 0 0.181818 0 0 0.272727
+0 0 0.25 0.25 0 0.5 0 0 0 0
+0 0 0 0 0 0 0 0.333333 0.666667 0
 ---
-1 1 1 0 1 0 1 0 0 0
-0 0 0 1 0 1 0 0 0 0
-0 0 0 0 0 0 0 1 1 1
+1 1 0 0 1 0 1 0 0 1
+0 0 1 1 0 1 0 0 0 0
+0 0 0 0 0 0 0 1 1 0
 ---
 ----------------------
 0.285714 0 0 0 0 0 0.285714 0 0 0.428571
-- -------------------------------------------------------
CMake Error at $SRC_DIR/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.
```
</details>

The full log is available [here](https://cloud.drone.io/conda-forge/igraph-feedstock/90/1/2).

**To reproduce**
Can be reproduced in the current PR (https://github.com/conda-forge/igraph-feedstock/pull/25) to update Anaconda `conda-forge` `igraph` to 0.9.0.

**Version information**
Released 0.9.0 source tarball.

**Comment by vtraag** [comment]
I will now first try to build the package with vendored libraries only.

**Comment by vtraag** [comment]
I can confirm that the problem is due to the external BLAS (netlib). @szhorvat, you have debugged some prior problems with SCGs. Do you have any suggestions? A simple possibility would be to simply build with the vendored BLAS / LAPACK.

**Comment by vtraag** [comment]
Closing, since the build in https://github.com/conda-forge/igraph-feedstock/pull/25 now passes on aarch64 with all external libraries. I do not know the exact cause for these particular failures. If they ever do resurface, we can always re-open the issue.

**Comment by szhorvat** [comment]
Which version / which commit are you using on conda?

Shortly after 0.9.0 was released, I replaced all the `qsort` with `igraph_qsort` in the codebase, as `qsort`'s implementation is platform-dependent, and can in some cases lead to different results (when there are multiple equivalent sorting orders). The SCG stuff uses qsort extensively.

If you switched to a later commit, this could be the reason why the tests pass now.

**Comment by vtraag** [comment]
Conda only uses released version (which I patched for some building purposes, all of which are also in the `igraph` repository). There have been some changes with respect to package linking, perhaps that might have had something to do with it. In any case, I don't want to go back breaking things in order to try to reproduce the error again :)

**Comment by dotlambda** [comment]
I have the same issue on NixOS (aarch64 as well). I'm using the system's openblas.

**Comment by szhorvat** [comment]
@dotlambda Can you post the output please?

**Comment by dotlambda** [comment]
<details>
<summary>Here it is.</summary>

```
cd /build/source/build/tests && /nix/store/vr6bg7hsj3i58jxdva34mgvkd68yanm2-cmake-3.19.6/bin/ctest --progress --output-on-failure -C Release
Test project /build/source/build/tests
347/382 Test #348: test::tls1.........................................  0.17 sec
348/382 Test #351: example::igraph_scg_grouping3......................***Failed   22.03 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- /build/source/examples/simple/igraph_scg_grouping3.out      1970-01-01 00:00:01.000000000 +0000
+++ /build/source/build/tests/example_igraph_scg_grouping3.out  2021-03-25 08:33:13.818707117 +0000
@@ -1,4 +1,4 @@
-0 0 0 1 0 1 0 2 2 2
+0 0 1 1 0 1 0 2 2 0
 0 1 1 1 1 1 0 2 2 0
 0 1 1 1 1 1 0 2 2 0
 0 1 2 3 4 5 6 7 8 9
-- -------------------------------------------------------
CMake Error at /build/source/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.



351/382 Test #354: example::igraph_scg_semiprojectors2................***Failed    0.29 sec
-- Test case output differs from the expected output
-- See diff below:
-- -------------------------------------------------------
--- /build/source/examples/simple/igraph_scg_semiprojectors2.out        1970-01-01 00:00:01.000000000 +0000
+++ /build/source/build/tests/example_igraph_scg_semiprojectors2.out    2021-03-25 08:33:21.334654806 +0000
@@ -1,11 +1,11 @@
 ----------------------
-0.222222 0.222222 0.111111 0 0.222222 0 0.222222 0 0 0
-0 0 0 0.333333 0 0.666667 0 0 0 0
-0 0 0 0 0 0 0 0.166667 0.333333 0.5
+0.181818 0.181818 0 0 0.181818 0 0.181818 0 0 0.272727
+0 0 0.25 0.25 0 0.5 0 0 0 0
+0 0 0 0 0 0 0 0.333333 0.666667 0
 ---
-1 1 1 0 1 0 1 0 0 0
-0 0 0 1 0 1 0 0 0 0
-0 0 0 0 0 0 0 1 1 1
+1 1 0 0 1 0 1 0 0 1
+0 0 1 1 0 1 0 0 0 0
+0 0 0 0 0 0 0 1 1 0
 ---
 ----------------------
 0.285714 0 0 0 0 0 0.285714 0 0 0.428571
-- -------------------------------------------------------
CMake Error at /build/source/etc/cmake/run_legacy_test.cmake:80 (message):
  Exiting test.



382/382 Test #178: test::igraph_layout_drl[Kinvalid_inputslt
99% tests passed, 2 tests failed out of 382

Total Test time (real) = 891.66 sec

The following tests did not run:
        348 - test::tls1 (Skipped)

The following tests FAILED:
        351 - example::igraph_scg_grouping3 (Failed)
        354 - example::igraph_scg_semiprojectors2 (Failed)
Errors while running CTest
```
</details>

**Comment by szhorvat** [comment]
Thanks you @dotlambda. Unless I missed a detail, this is completely identical to the failure @vtraag noticed. @vtraag I wonder why the problem went away for you (perhaps it's not really linking to OpenBLAS)?

@dotlambda, here's my take on this situation:

 - I recommend that you go ahead and ignore these specific failures. Needless to say, this advice applies *only* to these specific failures, not to anything else.
 - If you really have to (e.g. because NixOS policies might require it), you may patch the package in NixOS and disable these two tests there (comment out the two relevant lines in `tests/CMakeLists.txt`). This is not ideal because the feedback you've given was valuable, and it would be useful to be notified of any changes in the future.
 - We have been having trouble with SCG tests for a while now. SCG appears to be very sensitive to numerical errors, and tends to produce different output when switching the floating point implementation (e.g. x87 vs SSE on Intel processors) or switching the BLAS.  In my opinion, it is very likely that these failures do not indicate a real bug in the code (although they might indicate that the mathematical method is inherently sensitive ...)
 - The question that needs to be answered is: are all these different outputs correct? Can one construct a test which has only one valid output instead of multiple?  We already spent multiple hours on trying to deal with this.  I estimate that it would take several days of full-time work to sort it out. With my current 1 day / week igraph schedule, this would take me a month (including reading the original papers on the method). That time can be better spent elsewhere.
 - SCG is a very niche application that probably doesn't get much use (if it gets any at all). It is not a standard network analysis technique.
 - The SCG code in igraph was written by the author of the mathematical method, and later integrated into igraph. The original code has disappeared from the internet many years ago. It is not maintained anywhere except in igraph. It is not a small or simple codebase. This is one of the reasons it would take so much time to review it for correctness.
 - Because of these problems, we have even discussed removing this from future versions of igraph, perhaps breaking it out into a separate package. I don't know if this will happen or not.
 - In my experience while working with igraph, OpenBLAS tends to be the outlier among BLAS implementations. It tends to produce the least accurate results (admittedly, this is a subjective impression), and it was usually the one that required numerical tolerances to be relaxed in tests. With SCG, the output is discrete (categories), so one cannot simply relax tolerances. The other BLAS/LAPACK implementations I tested (netlib, Apple vecLib, MKL) all produced results closer to each other.

**Comment by szhorvat** [comment]
A final problem is that we do not have convenient access to aarch64 to work on this. Travis provided such machines, but Travis no longer supports open source projects. (They claimed otherwise, but they never responded to my emails when I tried to request continuing support for igraph.)

**Comment by szhorvat** [comment]
I'll check if I can reproduce the same issue on my Raspberry Pi (note: 32-bit!) with OpenBLAS, and might give it another go in the future. But as I said: this is a lot of work for little gain. It's just not worth it.

**Comment by dotlambda** [comment]
@szhorvat Thanks a lot for looking into it. I'll disable these two specific tests on aarch64 for now.

**Comment by szhorvat** [comment]
For reference, I cannot reproduce this on the Raspberry Pi. `arch` prints `armv7l`. This is a 32-bit platform.

**Comment by szhorvat** [comment]
However, the `example::igraph_scg_grouping` test took over 98 seconds with OpenBLAS. With the vendored BLAS, it takes 2.3 seconds. This is very strange.

**Comment by szhorvat** [comment]
It seems Fedora is hitting this too:

https://src.fedoraproject.org/rpms/igraph/pull-request/1

And not only on aarch64 but also on i686.

**Comment by szhorvat** [comment]
This is not reproducible on Travis with Ubuntu 20.04, which has OpenBLAS 0.3.8. Maybe it only appears with later OpenBLAS. Here's a mock PR I used to test: https://github.com/igraph/igraph/pull/1768

**Comment by szhorvat** [comment]
@Enchufa2 Regarding [the aarch64 failures in Fedora](https://src.fedoraproject.org/rpms/igraph/pull-request/1), are you able to check if these were due to enabling CXSparse, or due to a switch in the BLAS implementation? We cannot reproduce these.

**Comment by Enchufa2** [comment]
We had a couple of test failures for i686 and a ton of failures for aarch64 with OpenBLAS OpenMP as the backend (default in Fedora). You can see the logs here: https://koji.fedoraproject.org/koji/taskinfo?taskID=66182184. Given that they will be gc'ed at some point, I attach them here for your convenience.

Now we launch the tests using the reference implementation from Netlib, and all tests pass.

[build_aarch64.log.gz](https://github.com/igraph/igraph/files/6337441/build_aarch64.log.gz)
[build_i686.log.gz](https://github.com/igraph/igraph/files/6337442/build_i686.log.gz)

**Comment by szhorvat** [comment]
Interesting to see the timeout on aarch64:

```
386/386 Test #327: example::igraph_lapack_dsyevr .....................***Timeout 1499.89 sec
```

Reminds me of this: https://github.com/msys2/MINGW-packages/issues/8399

@Enchufa2 Could you help me look up with what options OpenBLAS was compiled in Fedora?  (Especially with reference to https://github.com/xianyi/OpenBLAS/wiki/faq#multi-threaded )

**Comment by Enchufa2** [comment]
Here: https://src.fedoraproject.org/rpms/openblas/blob/rawhide/f/openblas.spec#_402
