### ISSUE TITLE
igraph_diversity mishandles multi-edges

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1712]
**Describe the bug**
I believe `igraph_diversity` may be mishandling multi-edges (although I didn't read the associated paper).

**To reproduce**
In Python,

```
In []: g = Graph([(0,1),(1,2),(1,2)])

In []: g.diversity(weights=[2,1,1])
Out[]: [nan, 0.946394630357186, 1.0]
```

I believe the result should be either `[1,1,1]` or `[nan, 1, 1]` depending on interpretation.

I would expect the weights of the multi-edges to be added up. However, looking at the C code makes it clear that they are treated as if they were connecting to different vertices.

**Version information**

v0.9.0 python-igraph

**Comment by ntamas** [comment]
For future reference, [this is the original paper](https://www.uvm.edu/pdodds/files/papers/others/2010/beep2010a.pdf) that the measure is based on. In the context that the paper is working (edges are mobile phone contacts, weight is total call volume), it makes sense to add up the weights. I guess the underlying C implementation does not handle multigraphs explicitly. If we go down this rabbit hole, we should also think about the consequences of loop edges, which also do not make sense for mobile phone networks but maybe they do in other contexts.

**Comment by szhorvat** [comment]
> I guess the underlying C implementation does not handle multigraphs explicitly.

Yes, this was a bug report for the C core. I just happened to use Python to illustrate.

This is not a widely used measure, and it's likely not worth bothering to make it work for multigraphs. Those who need that can just simplify the graph and add up edge weights explicitly. 

I suggest adding a check for multigraphs. That will slow the function down a bit, but it will still be very fast (and eventually we'll make the multigraph check O(1) by caching the previous result).

**Comment by ntamas** [comment]
@szhorvat I have added a check for multiple edges in 57486de6d; however, there's still a corner case that we haven't treated: a directed graph with a mutual edge pair between two vertices. These will not be spotted by `igraph_has_multiple()` (and rightly so), but since the function treats directed graphs as undirected (it uses `igraph_incident()` with mode = `IGRAPH_ALL`), this will still produce erroneous results.

What shall we do with it?

* Throw an error for directed graphs and add it to `master` (after all, the measure was defined for undirected graphs in the original paper so we can consider it a bug that directed graphs were accepted -- on the other hand, directed graphs without mutual edges work just fine, each edge is treated as undirected).
* Throw an error for directed graphs and add it to `develop` (because it's a breaking change).
* Add a mutuality check for directed graphs and throw an error if there are mutual edges. This can go into `master` as the old behaviour is clearly buggy if the graph has mutual edges.

**Comment by szhorvat** [comment]
I vote for option 1: directed graphs should be disallowed, and it should go on `master`.  A directed graph with no reciprocal edges would be quite unusual as a real-world network. 

Of course, there are applications for such graphs. Sometimes one just needs an orientation for undirected edge to have a reference for a direction of a flow. Sometimes we have a bipartite network, which can conveniently be encoded as directed (targets and sources being the two partitions) but usually analysed as undirected.

But overall, I'd think that applications where this measure would come up, and the network is directed, would be quite rare.
