### ISSUE TITLE
Inclusion of Role and Structural Hole research

### ISSUE THREAD

**Issue by BrandonKMLee** [igraph/igraph#1735]
**What is the feature or improvement you would like to see?**
Inclusion of Role Detection / Role Similarity algorithms, and Structural Hole Indices.

**Use cases for the feature**
Identify leaders and brokers of a community within a network for social research and marketing

**References**
See references in https://github.com/GiulioRossetti/cdlib/issues/137 and https://github.com/GiulioRossetti/cdlib/issues/149

**Comment by szhorvat** [comment]
Just noting that Burt's constraint score is already included as `igraph_constraint`.

**Comment by szhorvat** [comment]
As currently written, this request is very broad and vague. Please make it more concrete: 

 - Which _specific_ metric are you requesting? You indicate an entire research area, but this is not really a tangible starting point for a potential contributor.

 -  Where is the metric best described, and where is the algorithm to compute it best described? Is this something that can be easily implemented using existing facilities (and high-level interfaces of igraph), or does it truly require an implementation in C?  Having clear answers to these is important so that potential contributors have a clear starting point.

 - What is the metric you propose useful for? Who uses it? We need to be able to judge if this is a niche idea, or something with broader acceptance in the network analysis community.

 - Please make the post self-contained and include references (permalinks or full citations) in this post directly, instead of linking to a page we have no control over (and which may disappear in the future—this has actually happened before).

As is the case with most open-source projects, igraph relies on volunteers.  Realistically, to get these features into igraph, you would either need to contribute it yourself (contributions are most welcome!), or provide enough information that another volunteer would be able to get started (and also _interested_ 😉 ) If the request is described in such a way that even those who are unfamiliar with this specific area of social network analysis can understand the gist of it, then there is a higher chance that someone will pick it up. If it just a link to a paper, it is likely to languish.

**Comment by BrandonKMLee** [comment]
From https://arxiv.org/pdf/1908.08572.pdf:

- [ ] Spectral embedding [Chung 1997]
- [ ] deepwalk [Perozzi et al. 2014]
- [ ] node2vec [Grover and Leskovec 2016]
- [ ] LINE [Tang et al. 2015]
- [ ] GraRep [Cao et al. 2015]
- [ ] ComE+ [Cavallari et al. 2019]
- [ ] GCN [Kipf and Welling 2017]
- [ ] GraphSage [Hamilton et al. 2017]
- [ ] MultiLENS [Jin et al. 2019c]
- [ ] deepGL [Rossi et al. 2017]
- [ ] MCN [Lee et al. 2018b]
- [ ] HONE [Rossi et al. 2018b]
- [ ] role2vec [Ahmed et al. 2018]
- [ ] node2bits [Jin et al. 2019a]
- [ ] SimSum [Liu et al. 2018b, 2019]
- [ ] rolX [Henderson et al. 2012]
- [ ] HERO [Ahmed et al. 2017b]
- [ ] EMBER [Jin et al. 2019b]

And from https://arxiv.org/pdf/1405.7134.pdf
- [ ] RPT [30]
- [ ] RDN-Boost. [122], [123]
- [ ] ReFeX [124]
- [ ] RPT [31]
- [ ] SAYU [82]
- [ ] nFOIL [83]
- [ ] SAYU-VISTA [125]
- [ ] Discri. MLN [126]
- [ ] ProbFOIL [127]
- [ ] kFOIL [128]
- [ ] PRM stru. learn. [129]
- [ ] TSDL [130]
- [ ] BUSL [131]
- [ ] PBN Learn & Join [132]

From Similarity Measure for Social Networks - A Brief Survey:
- [ ] SimRank
- [ ] PageSim
- [ ] E-Rank
- [ ] SimFusion
- [ ] P-Rank
- [ ] FriendTNS

**Comment by BrandonKMLee** [comment]
@szhorvat
For the metrics I am requesting, they seemed to be bundled together with major survey papers like the ones I have cited.

The utility of these measures stems from the needs to identify roles within a network, it can be a biological network, a social network or a business network.

> Where is the metric best described, and where is the algorithm to compute it best described? Is this something that can be easily implemented using existing facilities (and high-level interfaces of igraph), or does it truly require an implementation in C? Having clear answers to these is important so that potential contributors have a clear starting point.

This is a tough question, but there has not been libraries that collect info for all algorithms provided. Here is only two algorithms that are publically available to GitHub:
- https://github.com/dkaslovsky/GraphRole
- https://github.com/benedekrozemberczki/role2vec
