### ISSUE TITLE
Unable to cross-compile

### ISSUE THREAD

**Issue by Parakoopa** [igraph/igraph#1743]
**Describe the bug**
I am unable to cross-compile for Android, because it seems part of the generated Makefile tries to run the compiled `f2c/arith` which doesn't work since it's build for the target system.

**To reproduce**
In my case I have the following setup to run this, but other more simpler setups probably work too.

1. Clone python-igraph and update submodules
2. Have the Android SDK / NDK installed and ready
2. Run `python setup.py install` the environment setup as described here: https://developer.android.com/ndk/guides/other_build_systems#autoconf

**Version information**
0.9.0 of python-igraph.

**Comment by Parakoopa** [comment]
For reference, the part of the src/Makefile.im that causes the issue:
```
@INTERNAL_F2C_TRUE@  f2c/arith.h: f2c/arithchk.c
@INTERNAL_F2C_TRUE@	$(CC) $(CFLAGS) -DNO_FPINIT $(top_srcdir)/src/f2c/arithchk.c -lm -o f2c/arith || \
@INTERNAL_F2C_TRUE@	$(CC) -DNO_LONG_LONG $(CFLAGS) -DNO_FPINIT $(top_srcdir)/src/f2c/arithchk.c \
@INTERNAL_F2C_TRUE@		$(WARNING_CFLAGS) -lm -o f2c/arith
@INTERNAL_F2C_TRUE@	f2c/arith > f2c/arith.h
@INTERNAL_F2C_TRUE@  f2c/sysdep1.h: f2c/sysdep1.h0
@INTERNAL_F2C_TRUE@	cp f2c/sysdep1.h0 f2c/sysdep1.h
@INTERNAL_F2C_TRUE@  f2c/signal1.h: f2c/signal1.h0
@INTERNAL_F2C_TRUE@	cp f2c/signal1.h0 f2c/signal1.h
```

Specifically `f2c/arith > f2c/arith.h`

**Comment by szhorvat** [comment]
A workaround for this is already included in the development version by allowing to specify a custom `arith.h` file. Set the `F2C_EXTERNAL_ARITH_HEADER` CMake variable to point to your custom `arith.h` file.

See here in the documentation: https://github.com/igraph/igraph/blob/master/doc/installation.xml#L479

It is your responsibility to ensure that the `arith.h` file you use is suitable for your target platform. Generating this file on the host machine is likely NOT to produce correct results.

Let us know if this works for you.

**Comment by szhorvat** [comment]
Alternatively, you can link to an external ARPACK, LAPACK and BLAS, in which case f2c is not used at all.

**Comment by Parakoopa** [comment]
> It is your responsibility to ensure that the arith.h file you use is suitable for your target platform. Generating this file on the host machine is likely NOT to produce correct results.

But wait, maybe I misunderstand, but it's compiling fine for the target platform. The problem is that it tries to *run* it on the host platform after compiling.

**Comment by szhorvat** [comment]
> The problem is that it tries to _run_ it on the host platform after compiling.

Yes, it runs the program `arithchk`, which then generates the header file `arith.h`.

Version 0.9.1 will allow you to provide your own `arith.h` file. Ideally, you will compile `artihchk` on your target platform, run it, record its output, then use it in cross-compilation later.  This is available in the `master` branch of igraph (which will become version 0.9.1). Version 0.9.0 does not support this.

What I wrote above refers to the igraph C library (the "C core"). You are compiling the Python interface. You can set the `IGRAPH_CMAKE_EXTRA_ARGS` environment variable before compiling python-igraph in order to control how it compiles the C core.  You should probably be using the development version of python-igraph too (again, `master` branch).

We included this features to make it possible to cross-compile for Apple Silicon Macs. Let us know how it went with Android, and consider posting a copy of the correct `arith.h` for that platform here (in case others need it).

**Comment by szhorvat** [comment]
@Parakoopa Android is a strange platform to be running igraph on. I am curious what your project is (unless it's confidential).

**Comment by Parakoopa** [comment]
It isn't confidential, but it's a pretty specific project with lots of gears to make it work.

The part that requires igraph is a sort of disassembler that tries to convert a low-level scripting language with ASM-like control flow into a high-level scripting language with control structures such as loops and if/switch-conditions. I decided to use a graph based approach to make that work and python-igraph did the job great (especially considering performance).
https://github.com/SkyTemple/ExplorerScript/

This is used in a project to reverse-engineer the ROM of a video game, more specifically I'm currently porting the "Randomizer" to Android (changes a lot of attributes about the game around randomly and also needs to decompile and recompile scripts for that).

**Comment by Parakoopa** [comment]
In case you (or anybody stumbling upon this) is interested, this is the python-for-android recipe I got it running with:
https://github.com/SkyTemple/skytemple-randomizer/blob/p4a/android/recipes/python-igraph/__init__.py
