### ISSUE TITLE
OSS-fuzz build broken

### ISSUE THREAD

**Issue by AdamKorcz** [igraph/igraph#1747]
The [OSS-fuzz build script](https://github.com/igraph/igraph/blob/master/fuzzing/build.sh) is currently broken.

When running cmake .. the following error happens:

```
-- Setting build type to 'Release' as none was specified.
-- Cannot find out the version number of this package; IGRAPH_VERSION is missing.
-- 
-- The official igraph tarballs should contain this file, therefore you are
-- most likely trying to compile a development version yourself. The development
-- versions need Git to be able to determine the version number of igraph.
-- 
-- It seems like you do have Git but it failed to determine the package version number.
-- 
-- Git was found at: /usr/bin/git
-- The version number detection failed with: -128-NOTFOUND
-- 
-- Most frequently this is caused by a shallow Git checkout that contains no tags in the history.
-- 
CMake Error at etc/cmake/version.cmake:69 (message):
  Configuration failed.
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)
```

**Comment by ntamas** [comment]
Are you using a shallow git checkout in OSS-fuzz?

This usually happens when a shallow checkout is used. `etc/cmake/version.cmake` uses `git describe` to figure out the version number of igraph by going back in the history and looking for the most recent tag. If the checkout is shallow and no tag falls within the range that was checked out, the process will fail and you get the message that you see above. A workaround is to create a file named `IGRAPH_VERSION` in the repo root with a fake version number.

**Comment by ntamas** [comment]
Okay, this got broken recently in https://github.com/igraph/igraph/commit/7996a15ea3757a71463231086de5df35064f7deb where we tried adding support for using `igraph` as a subproject of another CMake project. I reverted the changes made to `etc/cmake/version.cmake` in that commit so it should work again now in your environment, but it probably breaks using `igraph` as a subproject so this is only a temporary fix.

**Comment by ntamas** [comment]
https://github.com/igraph/igraph/commit/7b4b2e1930fada163a7f32be84c695d37a902490 should solve this issue.
