### ISSUE TITLE
pkg-config file needs to be adapted when using OpenMP

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1765]
On my system, using OpenMP triggers linking to `libomp.dylib`. When OpenMP is enabled, this dependency should be present in the pkg-config file.

**Comment by szhorvat** [comment]
The same guesses as we use for the other libraries won't easily work here. With gcc I see `libgomp`, with clang I see `libomp`, with Intel 2015 `libiomp5`, etc.

**Comment by ntamas** [comment]
https://github.com/igraph/igraph/commit/5f0b0e6b8dae28ec1b585cb35af92f69fd7479b5 and https://github.com/igraph/igraph/commit/bbd0111ac622e1b3584cc1f09308d6835817f681 solves this, assuming that wherever the OpenMP library is, it is in a folder where the compiler looks for libraries by default. Since OpenMP is an integral part of these compilers, I think it is a reasonable assumption.
