### ISSUE TITLE
OpenMP missing when using igraph through CMake

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1766]
**Describe the bug**

Cannot use igraph through CMake when compiled with OpenMP.

**To reproduce**

Compile igraph with OpenMP support, install it, and try to use it in a CMake project:

```
cmake_minimum_required(VERSION 3.16)
project(igraph_test)

find_package(igraph REQUIRED)
# find_package(OpenMP)

add_executable(igraph_test igraph_test.c)
target_link_libraries(igraph_test PUBLIC igraph::igraph)
```

Unless the `find_package(OpenMP)` line is uncommented, this error occurs:

```
CMake Error at CMakeLists.txt:7 (add_executable):
  Target "igraph_test" links to target "OpenMP::OpenMP_CXX" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

**Version information**

0.9.2-5-g79c527a2b

**Comment by ntamas** [comment]
This seems to be fixed by https://github.com/igraph/igraph/commit/4eea1232452efc70483f7fedc9842b321510f9d0 and https://github.com/igraph/igraph/commit/a8b753109b7619cccd4fcb7c2fa32568dc02d6f1; please test it in a few configurations (I'm doing the same thing) and report back if you find any configuration that trips up the compilation.

**Comment by szhorvat** [comment]
Seems to work fine, assuming that the compiled used for the project also supports OpenMP.
