### ISSUE TITLE
Add a warning when user is adding too many vertices or edges

### ISSUE THREAD

**Issue by iosonofabio** [igraph/igraph#1769]
When a user has more than 2 billion nodes/edges on 32 bit integers, they start getting weird bugs without a warning.

We should add a warning in `add_vertices` and `add_edges` such that if we are overflowing on the current platform, the user at least knows about it. We could also throw an error.

Original issue: igraph/python-igraph#338
This issue should wait until the conversion to configurable ints is done #1626

**Comment by ntamas** [comment]
To put things in historical context: we never bothered with vertex / edge count checks in the past because when we started igraph, it seemed practically impossible to fit two billion vertices or edges in memory (the assumption was that you would be hitting memory limits earlier due to other reasons). I feel that this still holds for 64-bit integers so if we add such a check, it's probably enough to do so if `sizeof(igraph_integer_t) < 8`.

**Comment by ntamas** [comment]
Blocked by #1626; adding `todo` label to keep stalebot at bay

**Comment by szhorvat** [comment]
I recently fixed this, see be25a738be28219150394d4924d2459b04351074 and dcda4c668c832d0329d5cc79416185ff8e7ade08
