### ISSUE TITLE
Fix up plfit RNG usage

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1772]
plfit should:

 - Use igraph's RNG.
 - Not attempt to use igraph's RNG from multiple threads. plfit has some OpenMP code which uses the RNG. igraph may borrow the RNG from the host language (Python, R, Mathematica) in which case it likely won't be safe to use it from multiple  threads. For Mathematica, it isn't.

**Comment by ntamas** [comment]
Note to self (and for future generations): `vendor/plfit` seems to be tweaked already to support igraph's built-in RNG. In particular, if the `rng` argument (of type `plfit_rng_t*`) is `NULL` for any RNG-related functions, then `plfit` uses igraph's RNG.

Now, if `plfit` is compiled _without_ OpenMP, then all `plfit_` routines get their RNG from `options->rng` where `options` is of type `plfit_continuous_options_t` or `plfit_discrete_options_t`. Both structures initialize `options->rng` to NULL so we are okay.

If `plfit` was compiled with OpenMP, then it would use igraph's RNG to seed one private Mersenne Twister RNG per OpenMP thread, and then each thread would get its own RNG. The OpenMP threads would _not_ use igraph's RNG, and since each thread gets its own RNG instance, this seems okay to me. The result would still be deterministic if you seed igraph's RNG appropriately as each seed in the OpenMP threads would also be identical in that case.

The only part where nondeterminism may come into play (if I understand correctly) is the seeding of the individual Mersenne Twister RNGs. Seeding is done in `mt_init_from_rng(p_rng, options->rng)`, where `p_rng` is the private per-thread RNG, and `options->rng` is NULL so it is igraph's own RNG. (`mt_init_from_rng()` calls `get_random_uint16()` if the seeder RNG is NULL, and `get_random_uint16()` calls `RNG_INT31() & 0xFFFF`. `mt_init_from_rng()` is placed in the code like this:

```
#pragma omp parallel
{
...
#pragma omp critical
{
    p_rng = &private_rng;
    mt_init_from_rng(p_rng, options->rng);
}
...
#pragma omp for reduction(+:successes)
for (i = 0; i < num_trials; i++) {
    [...do some magic stuff with p_rng, trials are distributed to threads...]
}
...
}
```

What happens here is that the RNG seeding is in a critical section, so threads will take turns in seeding their own RNGs from the seeder in some arbitrary order, but only one thread will be messing around with the seeder RNG at any given point in time. So, in the end, you won't be able to predict _which_ thread gets a given seed, but with every run the same set of seeds will be distributed to the threads if you seed the seeder RNG in advance _and the number of CPU cores used by OpenMP stays the same_. If you change the number of threads used by OpenMP, or someone else changes them, then determinism is lost.

Anyhow, I think that the current implementation tries very hard to ensure that igraph's RNG is used only in a thread-safe way. Am I missing something here @szhorvat?

**Comment by szhorvat** [comment]
@ntamas Yes, this sounds reasonable. Can you please enable OpenMP for plfit then?

We might want to look at some of the clang analyzer warnings for plfit, and then we can do a 0.9.3, I think.

**Comment by ntamas** [comment]
Okay, it's done, see above.

**Comment by szhorvat** [comment]
Do you have any idea what OpenMP version plfit requires? I'll look into the MSVC failure later. MSVC supports version 2.0, which is super old:

```
-- Found OpenMP_C: -openmp (found version "2.0") 
-- Found OpenMP_CXX: -openmp (found version "2.0") 
```

**Comment by ntamas** [comment]
Well, it compiled fine now in CI on MSVC, so I think we don't use anything fancy from later versions.

Most of the work on `plfit` was done in 2013-2014. At that time, OpenMP was at version 3 so I'm 100% sure we don't use anything from OpenMP 4 or 5.
