### ISSUE TITLE
Leverage Centrality as an integrated Python Function

### ISSUE THREAD

**Issue by BrandonKMLee** [igraph/igraph#1792]
**What is the feature or improvement you would like to see?**
Being able to use igraph-python and have Leverage Centrality to be available without relying on R.

**Use cases for the feature**
Leverage centrality is a replacement form of Degree Centrality that is less correlated to Closeness Centrality.
Conversely, to de-couple Closeness Centrality from Degree Centrality, Eigenvector Centrality (iGraph/NetworkX) or Information Centrality (NetworkX) or Laplacian Centrality (https://andrewpwheeler.com/2015/07/29/laplacian-centrality-in-networkx-python/) can be used.

**References**
- Current R script http://igraph.wikidot.com/r-recipes#toc10
- Coupling Factor https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0220061
- Other references
  - http://jafarilab.com/cinna/articles/CINNA.html#correlation-between-computed-centrality-measures
  - https://www.nature.com/articles/s41598-021-89549-x#Fig1
  - https://www.researchgate.net/figure/Correlation-of-the-centrality-measures-investigated_fig3_339677873

**Comment by szhorvat** [comment]
Since this is not a widely adopted concept, it would have been useful to include a direct link to the article defining it, as well as including the definition directly in this issue.

This is the article:

 * Joyce et al, A New Measure of Centrality for Brain Networks, PLOS ONE, 2010, https://doi.org/10.1371/journal.pone.0012200

This is the definition from the article:

<img width="445" alt="image" src="https://user-images.githubusercontent.com/1212871/118681210-b370f500-b7ff-11eb-88bf-14d67c61efbe.png">

This is fairly trivial to implement in any high-level interface of igraph (as the essentially one-line R code you linked to demonstrates). Thus, I am not convinced that the inclusion of this measure is justified in C/igraph.

If you need help implementing this in python-igraph, feel free to ask on the support forum: https://igraph.discourse.group/

With my horrible Python,

```
from statistic import mean

def leverage(graph, v):
    return mean( (d[v] - d[u]) / (d[v] + d[u]) for u in graph.neighbors(v) )
```

**Comment by BrandonKMLee** [comment]
@szhorvat take a look at the notes made in https://github.com/networkx/networkx/issues/4973

**Comment by BrandonKMLee** [comment]
For R-based Centrality (hopefully being ported to Python) https://cran.r-project.org/web/packages/CINNA/vignettes/CINNA.html#centrality-measure-analysis
