### ISSUE TITLE
matrix_int_t in igraph_adjacency

### ISSUE THREAD

**Issue by iosonofabio** [igraph/igraph#1806]
During the configurable integer transition, a number of functions got corrections re their use of `igraph_vector_t` and `igraph_matrix_t` versus their `_int_` counterparts.

Seems like we forgot `igraph_adjacency`, who I think should take an integer matrix since there's a dedicated function for the weighted case. Any thoughts?

**Comment by ntamas** [comment]
No, we haven't forgotten about `igraph_adjacency()`, there was a bit of discussion about it on Slack and the decision was not to convert it to an `igraph_matrix_int_t`.

The guideline was that we absolutely need to convert all vectors and matrices that store _indices_ of vertices, edges or other enumerable stuff (and it turned out that this was 99% of the cases). Adjacency and incidence matrices were a bit of a borderline case, and the reason why we decided to keep `igraph_matrix_t` instead is to cater for cases when the user already has a matrix from the output of some other algorithm; in that case, we don't want to force the user to convert it to an `igraph_matrix_int_t` just for the sake of passing it to `igraph_adjacency()`, and I feel that `igraph_matrix_t` is what users would be using anyway most of the time.

I'm willing to revisit the decision  if you guys think it's necessary. @szhorvat and @vtraag were probably not following the discussion very closely on Slack as they were on holidays, so it was mostly me and @GroteGnoom . Now that I've summoned the whole team to this issue, we can think about it once again and settle this once and for all :)

**Comment by szhorvat** [comment]
I remember _some_ of the discussion and I agree that the fact that some quantity is typically integral is _in itself_ not sufficient reason to store it as an integer. We found examples where storing things as integers had disadvantages or limitations. Thus it's best to examine each case individually.

As @ntamas said, the idea was that all indices (vertex indices, edge indices, numbers used to index arrays) should be converted to integers. Other things should be decided case-by-case.

----

As for the specific case of adjacency matrices, I don't have a strong opinion, but I have a slight preference for keeping it consistently as reals. Some thoughts:

 - _Sparse_ adjacency matrices will not be integers because our sparse type only stores doubles (and extending it is probably not easy and thus not worth it)
 - When dealing with networks, it is almost always best to use a sparse representation. I expect to move in that direction in the future. 
 - The most common reason for using a matrix representation is so that one can do linear algebra (think spectral properties, relations like `triangle_count = Tr(A^3)/6`, or the cocitation matrix basically being a matrix product). Linear algebra is best supported for reals. Sure, there is niche software that does good linear algebra with integers, but BLAS, LAPACK, and friends all focus on doubles.
 - If we keep things as reals, as a small bonus we can easily move between the weighted / unweighted case. E.g. do I want to interpret entries as edge multiplicities, or as edge weights? Of course, one can copy/convert between integer and real matrices. It might seem annoying that this wastes memory. The real solution to limited memory is sparse matrices though, which bring us back again to using reals.

Thus I think it makes sense to keep matrices as doubles. Of course, this does bring some inconveniences. It would make sense that the entries are actually integers, or at least document what happens when they are not (how many edges get created when the entry is `2.5`?)

**Comment by iosonofabio** [comment]
Sounds good, I agree in spirit. But ATM we have `matrix_int_t` as well, and in the conversion to Python one has to be quite careful about these details.

I'll close this issue since it was intentional, and try to work around the real adjacency matrices at the CPython API level.

**Comment by vtraag** [comment]
I generally agree with what @ntamas suggests, and the general guidelines outlined by @szhorvat are indeed sensible. 

There are some edge cases however, and at the very least exceptions to such general principles should be properly documented. The [`igraph_get_adjacency`](https://igraph.org/c/doc/igraph-Structural.html#igraph_get_adjacency) function allows to return integer indices of edges, meaning that the entries do represent integers that are used for indexing. Since these are `igraph_real_t`, they only accurately represent the indices up to 2^53. I don't think this will ever be a problem in practice, since adjacency graphs for so many edges will not be frequently used anyway. Hence, even in this edge case, I agree that it is easier to keep on using an `igraph_matrix_t` instead of an `igraph_matrix_int_t`.

**Comment by szhorvat** [comment]
> The [`igraph_get_adjacency`](https://igraph.org/c/doc/igraph-Structural.html#igraph_get_adjacency) function allows to return integer indices of edges

I've forgotten about this. This is a rather unusual feature, and I wonder if we really need it in the C core.

Does anyone have examples of actual uses for it? _Within_ the C core, it is not used, but it is exposed in both R and Python. What I am curious about is if anyone has come across of practical uses for this feature in the wild, and what the use case was.  Most of the possible uses I can come up with (usually having to do with mapping vertex pairs to edge IDs in O(1) time and then using them to index into something) could be replaced with better approaches. But I'm sure I'm missing something. Perhaps in one of the high-level languages such matrices can be used for direct indexing very conveniently, allowing for very compact code?

I think we should think about whether it even makes sense to keep this functionality:
 - It can be kept as-is (but needs better error checking and docs)
 - It can be broken out into a separate function
 - It can be removed

If we keep it, the handling of multigraphs needs to be improved. Doing this just makes no sense for multigraphs.

> they only accurately represent the indices up to 2^53. I don't think this will ever be a problem in practice, since adjacency graphs for so many edges will not be frequently used anyway

Indeed. Adjacency matrices for graphs with so many edges simply won't fit into memory on any computer in the foreseeable future. Since the operation makes sense only for graphs without any multi-edges, we're talking about matrices with _at least_ 2^53 elements, each on 8 bytes, so 2^56 bytes = 2^16 terabytes ~= 65 petabytes.

The answer, as always, is sparse matrices. But sparse matrices holding edge indices should be trivial to construct in any high-level language that supports them. In R, the current implementation is almost a one-liner for each case of `type` and in Mathematica it would be an even simpler one-liner (`SparseArray[IGIndexEdgeList[g] -> Range@EdgeCount[g]]`).

**Comment by szhorvat** [comment]
For now I'll just make sure that `igraph_get_adjacency` shows a warning (or should it be an error?) when given a multigraph and asking for edge indices. This is trivial to implement without much of a performance decrease.

**Comment by ntamas** [comment]
> Does anyone have examples of actual uses for it?

I suspect this feature was implemented with an R-specific use-case in mind. Maybe R has a clever indexing operator that would allow you to construct a matrix where element (i, j) contains the value of some edge attribute that connects vertices i and j. Not being an R magician, I could only come up with this, which is not terribly concise:

```
> names <- c("a", "b", "c")
> matrix <- matrix(c(0,0,1,2,0,3,0,2,1), nrow=3)
> apply(matrix, 1:2, function(x) names[x])
```

The same could be achieved in Python if we returned a NumPy array because you can then index a NumPy 1D array with a NumPy 2D array, although again it's a bit awkward because you need a sentinel element in the `names` array:

```
>>> names = numpy.array(["", "a", "b", "c"])
>>> matrix = numpy.array([[0,0,1],[2,0,3],[0,2,1]])
>>> names[matrix]
array([['', '', 'a'],
       ['b', '', 'c'],
       ['', 'b', 'a']], dtype='<U1')
```

So, all in all, I don't think that this boolean argument should belong in the C core. This baiscally makes our beloved `igraph_get_adjacency()` function _two_ unrelated functions in one, with the boolean argument switching between the two implementations. I'd vote for removing the argument from the API, and maybe provide an extra function for returning this strange matrix of edge-IDs-plus-one instead.

**Comment by ntamas** [comment]
> For now I'll just make sure that `igraph_get_adjacency` shows a warning 

That's OK for me, but let's also check whether it makes sense to remove the option entirely if we are cleaning up the API anyway.

**Comment by szhorvat** [comment]
> I'd vote for removing the argument from the API

That's decided then.

> and maybe provide an extra function for returning this strange matrix of edge-IDs-plus-one instead.

We need to decide if we want this or not. @gaborcsardi, what was the original motivation for it? Here's a short summary so you don't have to read all messages:

 - The `get_adjacency` function has a feature to return an adjacency matrix, which does not contain `0`s and `1`s but `0` and edge indices.
 - This is not used within the igraph C core, but it is exposed in the R interface.
 - Are you aware of any practical use cases for this feature?
 - One idea was that perhaps some programming languages can use such matrices for indexing. Is this the case for R? Does it have a particularly concise indexing syntax where these matrices can be used?

Related:  https://github.com/igraph/rigraph/issues/473

**Comment by gaborcsardi** [comment]
I don't remember but if it is not used anywhere then sure, you can remove
it

**Comment by szhorvat** [comment]
OK, in that case, let us remove this feature both from the C core and the R/Python interfaces.

Generally, I am not very comfortable removing features, but in this specific case, it will be easy enough to re-add it if users come complaining. I did a search StackOveflow / `igraph` tag, and no one seems to have used this feature in any answers.
