### ISSUE TITLE
igraph_avg_nearest_neighbor_degree does not handle loop edges correctly

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#183]
A -- B
A -- C
B -- C
A -- D
B -- D
A -- A

The result for A should be 3, but igraph counts A itself twice, because it appears twice in the neighbor list.

---

Imported from Launchpad using lp2gh.
- date created: 2010-04-08T07:56:45Z
- owner: gabor.csardi
- assignee: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/557903

**Comment by szhorvat** [comment]
Re-opening because non-simple graphs should be supported by this function. With the new adjlist/inclist constructor a fix may be easy.

**Comment by szhorvat** [comment]
Actually, this function does not use adjlists, but `igraph_neighbors`. Supporting multigraphs in functions like these is an argument in favour of making either `igraph_neighbors` or an internal version of it have fine-grained self-loop controls (ignore, take once, take twice). The weighted version uses `igraph_incident`.

**Comment by szhorvat** [comment]
This is being requested on the forum: https://igraph.discourse.group/t/how-can-i-calculate-knn-k-of-not-simple-graph/968

**Comment by szhorvat** [comment]
> The result for A should be 3, but igraph counts A itself twice, because it appears twice in the neighbor list.

The function gives 3.4, not 3, because A is indeed counted twice. However, this is entirely consistent with the directed-undirected equivalence principle we've been using: The result for an undirected graph must be the same as for a directed graph with all-reciprocal edges.

With additional testing and comparison with an alternate implementation, I will re-enable support for non-simple graphs in #2419
