### ISSUE TITLE
Create symmetric tree from vector of branching count

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1841]
_Implementing this is a good way to get started with contributing to igraph._

**What is the feature or improvement you would like to see?**

A function to create a symmetric tree which branches to `k[i]` ways at level `i`.

The input will be a vector which indicates the number of branches at each level. The output will be a directed or undirected tree. 

This is already implemented in IGraph/M, but it would be nice to have it in the C core.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/1212871/141661593-a3acf7e1-7b99-42ae-8601-d6caf0572945.png">

**Use cases for the feature**

A convenience function for easily creating arbitrary symmetric trees. This is a generalization of the current `igraph_tree` where the branching count is the same at each level. It makes it easy to create common graphs such as a finite [Bethe lattice](https://en.wikipedia.org/wiki/Bethe_lattice)

**Comment by YuliYudith** [comment]
Hello,

we would like to take this ticket and implement it. We have read through the tutorial and the testing guide and our approach would look as following:

1. Write tests for the symmetric tree. 
2. Check for test cases and follow the checklist on what to take into consideration as test cases.
3. Implement the functionality
3.1 Similarly to igraph_tree
3.2 Instead of all vertices having the same number of children, the number of children for each level is the one specified in the vector starting with the root node
3.3 Use create_graph to create the graph
4. We will not try to mirror part of the tree
5. Write examples for /simple/

Would this be okay with you?

**Comment by GroteGnoom** [comment]
That sounds really great. It sounds so naturally like the correct approach that I don't think you could do better. It usually works well to start a draft PR early in the process so we can quickly give tips, instead of looking over the whole finished PR in one go.

**Comment by YuliYudith** [comment]
Thank you for the fast answer. 

We will start with a draft PR (although this will be the first time for us that we use this feature) and keep our work progress updated.

**Comment by szhorvat** [comment]
@YuliYudith You can take a look at the very first commit in PR #1856 to see what a basic skeleton PR could look like. I suggest you start with something as barebones as that, and build on top of it.

**Comment by YuliYudith** [comment]
Perfect, thank you! We will do that. It's always easier to have an example.

**Comment by YuliYudith** [comment]
![symmetric_tree_example](https://user-images.githubusercontent.com/54366258/144478549-939074dc-455b-4dcb-a9b9-aa23fb70758e.png)

This is how a symmetric tree created with our function with input vector {4, 2, 3} looks like. 
Plotted with python cairo library.
