### ISSUE TITLE
igraph will not build from source: IGRAPH_VERSION file missing

### ISSUE THREAD

**Issue by sauergeek** [igraph/igraph#1847]
**Describe the bug**
Cannot build igraph from release source tarball due to missing file IGRAPH_VERSION required by cmake.

**To reproduce**
`wget https://github.com/igraph/igraph/archive/refs/tags/0.9.5.tar.gz`
`gzip -dc 0.9.5.tar.gz | tar -xf -`
`cd igraph-0.9.5`
`mkdir build`
`cd build`
`cmake ..`

If git is not installed, it will fail with:
`-- Setting build type to 'Release' as none was specified.`
`-- Cannot find out the version number of this package; IGRAPH_VERSION is missing.`
`--`
`-- The official igraph tarballs should contain this file, therefore you are`
`-- most likely trying to compile a development version yourself. The development`
`-- versions need Git to be able to determine the version number of igraph.`
`--`
`-- Please install Git, make sure it is in your path, and then try again.`
`--`
`CMake Error at etc/cmake/version.cmake:56 (message):`
`  Configuration failed.`
`Call Stack (most recent call first):`
`  CMakeLists.txt:27 (include)`
``
``
`-- Configuring incomplete, errors occurred!`

If git is installed, it will fail with:
`-- Cannot find out the version number of this package; IGRAPH_VERSION is missing.`
`--`
`-- The official igraph tarballs should contain this file, therefore you are`
`-- most likely trying to compile a development version yourself. The development`
`-- versions need Git to be able to determine the version number of igraph.`
`--`
`-- It seems like you do have Git but it failed to determine the package version number.`
`--`
`-- Git was found at: /bin/git`
`-- The version number detection failed with: HEAD-HASH-NOTFOUND`
`--`
`-- Most frequently this is caused by a shallow Git checkout that contains no tags in the history.`
`--`
`CMake Error at etc/cmake/version.cmake:56 (message):`
`  Configuration failed.`
`Call Stack (most recent call first):`
`  CMakeLists.txt:27 (include)`
``
``
`-- Configuring incomplete, errors occurred!`

**Version information**
Downloaded the tarball from https://github.com/igraph/igraph/releases/tag/0.9.5

**Comment by szhorvat** [comment]
You are downloading the wrong archive. That is not the release tarball, but the snapshot of the git repo's contents at the `0.9.5` tag. Use the actual release tarball,

https://github.com/igraph/igraph/releases/download/0.9.5/igraph-0.9.5.tar.gz

**Comment by szhorvat** [comment]
Note:

Building from an actual git repo is fine. Taking merely the _contents_ of the git repo, but not having an actual repo to back it up is not going to work. This is because the build system uses git to determine the version. 

If you want a certain release rather than the dev version, use the release tarball. Do not use git.

**Comment by vtraag** [comment]
To add to what @szhorvat said: if you want to build the latest development version, you *have* to clone the repository, so that it also is a proper `git` repository. That is, you need to run `git clone https://github.com/igraph/igraph.git` and follow [the build instructions](https://igraph.org/c/html/latest/igraph-Installation.html#igraph-Installation-general-build-instructions) from there onwards.
