### ISSUE TITLE
Circulant Graphs

### ISSUE THREAD

**Issue by Gomango999** [igraph/igraph#1851]
**What is the feature or improvement you would like to see?**

A circulant graph generator, as mentioned in [#1844](https://github.com/igraph/igraph/pull/1844#issuecomment-972959559)

A circulant graph is a graph such that if the n vertices are labelled from 0 to n-1, and two vertices numbered x and x+d mod n are adjacent, then all vertices numbered z and z+d mod n are adjacent.

The function `G(n, l)` will accept `n`, the number of vertices, and `l`, a list of distances to generate the graph. We will then
- Create `n` nodes `v_0, v_1, ..., v_{n-1}`
- For each node `v_i` and for each distance `d_j`, connect `v_i` to `v_(i+d_j mod n)`

**Use cases for the feature**

From Wikipedia: Circulant graphs can be used to generate Paley graphs, which have applications in number theory, as well as Möbius ladders, which can be used to model molecular structures. There is also a larger list of other classes of graphs based on Circulant graphs which can be found on Wolfram Alpha.

**References**

https://mathworld.wolfram.com/CirculantGraph.html
https://en.wikipedia.org/wiki/Circulant_graph

**Comment by Gomango999** [comment]
I'd also be happy to take on this project as a (hopefully much easier!) first contribution

**Comment by GroteGnoom** [comment]
Awesome that you also made the issue, that makes things a little clearer. Looking forward to your work 🙂

**Comment by ntamas** [comment]
> This way you can quickly test your own code, and if you want a full test you can still do `cmake --build . --target check`

Another neat trick is to install `ccache` and `ninja`, which makes even full rebuilds blazing fast. `ccache` caches compiled object files, while `ninja` is simply much faster than `make`. You need to tell CMake explicitly that you want to use Ninja (`mkdir build && cmake -GNinja ..`), but `ccache` works out of the box as far as I know.

**Comment by ntamas** [comment]
@Gomango999 You can look at https://github.com/igraph/igraph/pull/1844 for inspiration about how a PR of a new graph constructor function looks like.

**Comment by szhorvat** [comment]
Great job on opening the issue! We can point newcomers to it as an example of how to get started.

**Comment by szhorvat** [comment]
> Do you want an option to make it either a directed or undirected graph?

It would be nice if you guys could do a little research on what is being written about directed circulant graphs (if anything), and how they're typically defined.

> Should the distances be limited to n/2 in the undirected case, and n-1 in the directed case? (or get possible multi-edges otherwise) Do we create loops for d=0?

This would also need a bit more research and comparison with what other systems do, but right  now I would say this:

 - This function should be able to generate all simple circulant graphs, therefore we should not restrict the possible parameter values. The following is a valid circulant graph (`n=6`, `l = {3}`):
    <img width="202" alt="image" src="https://user-images.githubusercontent.com/1212871/142722795-3cdc49b9-596e-4862-aa99-2cc2c9864a97.png">
   It satisfies this definition from Wikipedia: "the graph has a graph automorphism, which is a cyclic permutation of its vertices." In other words, we can draw the `n` vertices on a circle in such a way that the drawing is symmetric to rotations by `2pi/n`.
 - It might make sense to add two Boolean parameters to control whether self-loops and multi-edges are generated. In a high-level interface, the default can be "no" for both (i.e. the graph is simplified) because circulant graphs appear to be discussed as simple graphs most of the time. 
 - Alternatively, we can always simplify and not provide the option to create loopy or multigraphs.

**Comment by GroteGnoom** [comment]
If you want loops or not should depend on `l` right? I don't think it needs extra parameters. I was mainly wondering if we should give an error if `d=0` or `d>n/2`(undirected) because they can result in muligraphs and loops.
For example `n=6`, `l ={0,6}` will create two loops at each point.

**Comment by szhorvat** [comment]
`n/2` already results in multi-edges, see my example above. Yet we absolutely do want to allow `n/2` _and_ simplify the graph, as there is no other way to create the graph I illustrated above. The question is whether it is useful to also have a `multi` parameter, which makes it possible to _not_ simplify.

You are right that there is no point in having an option for removing loops because loops appear only when using `d = k*n`.

**Comment by Gomango999** [comment]
I've been doing some research, and here's what I've come up with. In terms of implementations, I've found two libraries that implement circulant graph generators:

[**Wolfram Language**](https://reference.wolfram.com/language/ref/CirculantGraph.html)
- No option for self loops
- No option for multiple edges
- No option for directed
- (All of these are off by default)

[**NetworkX**](https://networkx.org/documentation/stable/reference/generated/networkx.generators.classic.circulant_graph.html)
- Allows self loops by default
- Does not allow multiple edges by default
- One of the arguments is a graph constructor, which can be used to change how the function behaves
    - If a Digraph constructor is passed in, it will form a directed graph.
        - But the [implementation](https://networkx.org/documentation/stable/_modules/networkx/generators/classic.html#circulant_graph) is a bit naive in that edges are always made pointing forwards AND backwards by the offset. Thus for directed graphs, this effectively turns the graph back into it's undirected variant, which I doesn't make a whole lot of sense
    - If a MultiGraph constructor is passed in, it will create multiple edges
        - Again, the implementation is naive, so something like `nx.circulant_graph(n, [1], nx.MultiGraph)` would double up all the edges, giving `2n` edges in total, whereas I would expect it to just create the typical ring graph.
    - To be honest, this functionality feels more like an afterthought, and a bit poorly planned.

**Comment by Gomango999** [comment]
> Do you want an option to make it either a directed or undirected graph?

In terms of directed acyclic graphs, I think they should be supported, as it appears in multiple in papers, for example [here](https://www.tandfonline.com/doi/abs/10.1080/09720529.2019.1694739), [here](http://www.optimization-online.org/DB_FILE/2010/03/2577.pdf) and [here](https://www.sciencedirect.com/science/article/pii/S0012365X99004148). Obviously, we should implement it so that directed edges only connect forward (i.e. `v_i -> v_(i+d_j mod n)`), to stay consistent with the definitions presented in papers, as well as what I would typically expect from a directed circulant graph.

> I was mainly wondering if we should give an error if d=0 or d>n/2(undirected) because they can result in muligraphs and loops.

Neither implementations throws errors when you give it numbers higher than `n/2`(undirected) or `n`(directed), and both follows the 'it just works' philosophy. I think this is a fair assumption, and is consistent with the definition of circulant graphs.

> The question is whether it is useful to also have a multi parameter, which makes it possible to not simplify.

Out of all the papers/resources I looked at, none of them dealt with self loops or multiple edges (except for one, but the goal of that paper was finding spanning trees, so it didn't matter anyway). I think just always simplifying the graph is fine.

**Comment by szhorvat** [comment]
It all sounds good, feel free to go ahead with the PR.
