### ISSUE TITLE
Use CI to verify types in functions.yaml 

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1863]
Most aspects of igraph are checked on each commit. One big missing piece is a verification of `functions.yaml`, and the types within. Do the match the function prototypes in C?

Of course, the verification can only be partial because the types in `functions.yaml` are more granular than the C types. For example, an integer vector may map to: (1) arbitrary integer vector (2) index vector (3) vertex IDs (4) edge IDs, and probably other things too. However, it may not map to a real vector. At least this much should be verified. 

A proposal for a mechanism to carry out this verification:

Implement a dummy interface generator that simply creates identical wrappers for each function. Then let the compiler check that the types match. Use C++ instead of C because C++ has more stringent requirements on matching types. C++ also has facilities for static assertions about some properties of types, e.g. the presence of `const`.

For example,

```yaml
igraph_create:
    PARAMS: OUT GRAPH graph, VECTOR edges, INTEGER n=0, BOOLEAN directed=True
```

could translate to

```c++
int igraph_create_wrapper(igraph_t *graph, const igraph_vector_t *edges, igraph_integer_t n=0, igraph_bool_t directed=1) {
    return igraph_create(graph, edges, n, directed);
}
```

**Comment by szhorvat** [comment]
In fact this may be better, because it requires strict match in `const`ness (and can thus handle `OUT` arguments better):

```c++

int stimulus_igraph_create(igraph_t *, const igraph_vector_t *, igraph_integer_t, igraph_bool_t);

static_assert(std::is_same<decltype(igraph_create), decltype(stimulus_igraph_create)>::value, 
  "igraph_create prototype mismatch");
```

Or some combination of the two variants above.

**Comment by ntamas** [comment]
Started working on this [here](https://github.com/igraph/stimulus/commit/9786c5742258737cfcc03e5dc19c3a3a019fea95). Right now you can do something like this:

```bash
$ stimulus -l ci:validate -f interfaces/functions.yaml
```

This prints the generated code to `stdout`; it does not compile as I don't fill the argument list yet, but it's a starting point. I'll work on it in the next few days to see if this is a feasible direction.

**Comment by ntamas** [comment]
Worked on this a bit more (not committed yet). It seems like we will be running into the following problems:

*Passing by value or by reference*

Types in `types.yaml` need to be marked to let the code generator know whether they are going to be passed by value or by reference if we want to generate correct C function headers. Currently I'm using the following syntax for this:

```
INTEGER:
    CTYPE: igraph_integer_t
    FLAGS: PRIMITIVE
```

(`FLAGS` is just a set of tags that can be applied on the type and we can query them from the code generator with `some_type.has_flag("some_flag")`). I don't particularly like this syntax, especially because types like `igraph_vs_t` are also typically passed by value, plus all enums are also passed by value so the data structures that are passed by reference are actually the minority. Alternative suggestions:

```
GRAPH:
    CTYPE: igraph_t
    FLAGS: BY_REF
```

or

```
GRAPH:
    CTYPE: igraph_t BY_REF
```

The latter is not compatible with the existing type definitions in the `rigraph` repo.

Note that we cannot simply use `CTYPE: igraph_t*` because then we would need to _strip_ the asterisk if we want to allocate an object of that type on the stack.

*Our headers are not const-correct*

The convention that I'm using when generating the headers is that `IN` parameters use `const CTYPE` (unless the type is passed by value, in which case it is simply `CTYPE`), while `OUT` and `INOUT` parameters use `CTYPE*`. This reveals places in the C API where const-correctness is violated; for instance, `igraph_adjacency()` and `igraph_weighted_adjacency()` take an `igraph_matrix_t*`, even though they never modify the matrix, so they should be happy with a `const igraph_matrix_t*`. Fixing this is a breaking API change, so the fix cannot go into 0.9, only into 0.10 -- the best I can do in 0.9 is to ignore these functions in the validator.

**Comment by GroteGnoom** [comment]
```
for instance, igraph_adjacency() and igraph_weighted_adjacency() take an igraph_matrix_t*, even though they never modify the matrix, so they should be happy with a const igraph_matrix_t*. Fixing this is a breaking API change,
```
All the code that compiled before this change should also compile after this change, right? (And do the same) Does that still count as a breaking change?

**Comment by ntamas** [comment]
Hmmm, actually, good point :) Thanks!

**Comment by szhorvat** [comment]
I just wanted to point out one ugly instance of input argument handling. This is the prototype of the label propagation function:

```
igraph_error_t igraph_community_label_propagation(const igraph_t *graph,
                                       igraph_vector_int_t *membership,
                                       igraph_neimode_t mode,
                                       const igraph_vector_t *weights,
                                       const igraph_vector_int_t *initial,
                                       igraph_vector_bool_t *fixed,
                                       igraph_real_t *modularity)
```

`fixed` is an input parameter, so why is it not `const`? It turns out that if the provided `fixed` vector is inconsistent with `initial`, then the `fixed` vector will be modified by the function (and a warning is issued). Somehow I really don't like how input parameters are modified ...

Not a huge deal, just wanted to point it out, since you are adding `const` to many functions that lack it.

**Comment by ntamas** [comment]
> It turns out that if the provided `fixed` vector is inconsistent with initial, then the `fixed` vector will be modified by the function (and a warning is issued).

...and I think the implementation shouldn't do that; we should not mess around with inputs that the user provides to us, unless we document it properly that the function can modify `fixed` -- in which case it's not an `IN` parameter anymore but an `INOUT`. So the internals of `igraph_community_label_propagation()` should be fixed.

It's good that we are doing this consistency check -- these are exactly the types of issues that we should catch and deal with them formally.

**Comment by ntamas** [comment]
Okay, this one seems to work now; all that's left is to integrate it into the CI pipeline.

**Comment by vtraag** [comment]
Implemented PR in https://github.com/igraph/igraph/pull/1868, so closing.
