### ISSUE TITLE
Functions such as cattribute_GAN() call error() but don't return an error code

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1918]
Functions such as `igraph_cattribute_GAN()` call `igraph_error()` but they do not return an error code. They return the attribute value instead. On error, they simply return 0 for numeric/boolean attributes and `NULL` for string attributes. This does not seem right. It seems to be written with the assumption that the error handler does not return, which is not always the case.

What shall we do about this? Refactor the interface? Or perhaps make these functions return a default value and raise a warning instead of an error?

**Comment by ntamas** [comment]
Currently the `igraph_cattribute_GAN()` function is also aliased as `GAN` (with a simple `#define`) so we cannot change its return value to an error code because we lose the ability of providing a "shorthand notation" to the user when the user knows what he/she is doing and wants to skip error checks explicitly.

I'd rather provide `igraph_cattribute_GAN_safe()` or something like that -- this can return an error code, and `igraph_cattribute_GAN()` can then call `igraph_cattribute_GAN_safe()` internally. People who want to be on the safe side could then use `IGRAPH_CHECK(igraph_cattribute_GAN_safe(...))`.

**Comment by szhorvat** [comment]
The way these functions are currently written is buggy: they call `igraph_error()` yet return normally and allow the program to continue. `igraph_error()` typically calls `IGRAPH_FINALLY_FREE()`. This means that when these functions return, there will likely be an attempted access to an already freed memory region and a crash.

We have to do something about this.

**Comment by szhorvat** [comment]
The only error that can occur is that the attribute is not found.

I suggest the following:

 - All functions should have a checked version, in addition to the current unchecked ones. For vertex and edge attributes, we already have these in the form of the vector versions. There is the unchecked `igraph_cattribute_VAN()` and the checked `igraph_cattribute_VANV()`. However, for graph attributes we don't.
 - We can keep the current convenient unchecked versions, but make them issue a warning when the attribute is not found, and return a default value (NaN for numeric, 0 for Boolean, `""` for string).

Does this sound good in general?

**Comment by szhorvat** [comment]
For edge/vertex attributes, we can use the vector version as the "safe" one. For graph attributes, there is no safe version, for which I'll open a new issue. Closing this one now.
