### ISSUE TITLE
NCOL writer should preserve edge order

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1923]
Currently, the NCOL writer outputs edges as `IGRAPH_EDGEORDER_FROM` instead of `IGRAPH_EDGEORDER_ID`. In other words, it sorts the edges by their source vertex.

While NCOL is a format for the LGL software, in practice it is commonly used for writing graphs in a "named edgelist" format. For this more common application, I think there is value in preserving the edge ordering, and I propose changing this function on the `develop` branch to do so. However, I am not sure if the LGL software prefers sorting by the source vertex. The description doesn't say so, but the example that's shown is sorted: http://lgl.sourceforge.net/#FileFormat

**Comment by ntamas** [comment]
I think the original NCOL reader from the LGL project is [here](https://github.com/TheOpteProject/LGL/blob/master/include/graph.hpp#L845). I don't see anything in there that would require the edges to be sorted by their sources, and since there is no formal specification for the format, I'm inclined to say that the order of edges in the NCOL file is undefined / unspecified so we are free to use whatever order we want to. I'm okay with changing the current NCOL writer, but I'd rather do that for 0.10 and not for the next patch release of 0.9 (if there will ever be any).

**Comment by szhorvat** [comment]
Yes, this should only be done for 0.10. There's no reason to mess with this in 0.9. I'll do it.
