### ISSUE TITLE
 `modularity()` results differ when called on communities vs with graph + membership

### ISSUE THREAD

**Issue by ashander** [igraph/igraph#1927]
This is similar to an [old question on SO](https://stackoverflow.com/questions/20313608/the-correct-use-and-interpretation-of-modularity) but not due to weights.

The two different ways given in `?modularity`  give different results yet based on the answer to the SO question I don't think this should be the case.

The two different ways to compute modularity given in the help are:
```r
    wtc <- cluster_walktrap(g)
    modularity(wtc)
    # and
    modularity(g, membership(wtc))
```

For this example these give different results

```r
g2 <- make_graph(c(1,2,2,3,3,1), directed = FALSE)

set.seed(444)
wtc2 <- cluster_walktrap(g2)
modularity(wtc2)
## 0
wtc2
##IGRAPH clustering walktrap, groups: 3, mod: 0
##+ groups:
## $`1`
##  [1] 1
## 
##  $`2`
## [1] 2
##  
##  $`3`
##  [1] 3
modularity(g2, membership(wtc2))
## -0.3333
```

This is with `igraph_1.2.5`.

## Note

This shows up on much more complicated graphs as well -- this is the simplest case where I could reproduce

**Comment by szhorvat** [comment]
This looks like an issue with the Walktrap code in that the returned community structure is not the one with the highest modularity.

Also, Walktrap returns a sequence of modularity values, one for each merge step of the dendrogram. The one for entirely separate vertices is 0, not -0.3333.

Moving to the C core repo, since this is not an R-specific bug.
