### ISSUE TITLE
leading eigenvector community bug

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#1929]
At least this does not seem right:

``` r
g <- graph.full(5) %du% graph.full(5) %du% graph.full(5)
g <- add.edges(g, c(1,6, 1,11, 6, 11))
lec <- leading.eigenvector.community(g)
lec
#> Graph community structure calculated with the leading eigenvector algorithm
#> Number of communities (best split): 1 
#> Modularity (best split): 0 
#> Membership vector:
#> [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
```

**Comment by vtraag** [comment]
Hmm, the problem is that there are multiple leading eigenvalues. The implementation in that case doesn't make any split. I'm not sure if that is really a reasonable behaviour. If there are multiple leading eigenvalues, it sounds to me as if either forms a reasonable split. The only problem of course is trying to make this deterministic, perhaps that was the reason for this behaviour in the case of multiple leading eigenvalues.

**Comment by ntamas** [comment]
Went back in the history to check whether this is a new thing, but it has already been there [in 2012](https://github.com/igraph/igraph/blob/456d95c17f718665c33ba1e620e50c1f16200518/src/community.c#L1859).

I guess we have two options:

1. Close the issue as is, and maybe document that the function will not split communities further in this case, or
2. Add an option to the C function that controls what to do in such cases (stop or pick an arbitrary leading eigenvector and use that).

**Comment by vtraag** [comment]
I'm not really sure about the motivation for not splitting in the case of multiple leading eigenvalues. In the comments, this is the argument for it:

https://github.com/igraph/igraph/blob/3793ca1299119a1647b7b4a003aeb2d7fa1d842e/src/community/leading_eigenvector.c#L673-L678

Deleting the last column and row from the modularity matrix sounds rather strange to me. Also, I don't think it would matter whether we just get the leading eigenvalue or the two first eigenvalue, we can always just get one. In order to ensure reproducible results, we would just have to ensure that the initialisation of the random starting point is done by using the RNG (I'm not sure if that is currently the case or not).

I would be in favour of simply always splitting if possible, instead of avoiding to do so in the case of multiple eigenvalues, while ensuring that results are reproducible. 

Do you see any reason why splitting should not be done in the case of multiple eigenvalues?

**Comment by szhorvat** [comment]
Just curious, did you check if the cited reference has anything to say on this point?

**Comment by vtraag** [comment]
As far as I know, the original reference says nothing about multiplicity of eigenvalues and how they could be problematic.
