### ISSUE TITLE
SETEAN segfaults if igraph_set_attribute_table is not called first

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#1940]
**Describe the bug**
If you forget to call igraph_set_attribute_table, then a call to
SETEAN segfaults

**To reproduce**
```
int main() {
    igraph_t g;

    igraph_small(&g, 4, IGRAPH_DIRECTED,
            0, 1, 0, 1, 0, 1,
            1, 2, 2, 3,
            -1);

    SETEAN(&g, "edge_attr", 0, 10);
}
```

I'm guessing all the other attribute set macros have the same problem.

**Version information**
The latest development branch, which is now at 131992dc0961744fb9911f336910ee1b0b19c23f

**Comment by GroteGnoom** [comment]
It happens because igraph_cattribute setting and getting functions use:
```
igraph_i_cattributes_t *attr = graph->attr;
igraph_vector_ptr_t *val = &attr->val;
 igraph_bool_t l = igraph_i_cattribute_find(val, name, &j);
```
Where attr is NULL, and val is now 0x40
Since they all pass through igraph_i_cattribute_find, it seems nice to solve the problem there in general, but checking for a 0x40 pointer seems like a bad idea.

We can also add a NULL check in all the separate functions. Maybe even better would be to clean up /src/graph/cattributes.c because there's a lot of copied code which makes it hard to fix a single problem in a single place.

**Comment by ntamas** [comment]
I'd vote for adding an `IGRAPH_ASSERT(graph->attr != 0)` in the `igraph_cattribute_*` functions where applicable; these are helpful in catching errors like this during development with a debug build, but they do not present a runtime penalty in production.

**Comment by szhorvat** [comment]
@ntamas `IGRAPH_ASSERT()` stays enabled in release builds by design. 

When we want an assert that does not stay active in release builds we should use `assert()` from `assert.h`.

**Comment by ntamas** [comment]
Hmmm, considering that we have `IGRAPH_ASSERT()` all around the place in `vector.pmt` and related files, I think we can also safely use an `IGRAPH_ASSERT()` here, and in that case we are at least consistent. What do you think?

**Comment by szhorvat** [comment]
I do not think we need to be consistent. 

`assert()` should be used where it can have a real performance hit, while `IGRAPH_ASSERT()` when there is value in keeping it in the release build.  In this case, neither holds, so it doesn't really matter: `IGRAPH_ASSERT()` is just as fine as `assert()`.

----

When is there a value in keep `IGRAPH_ASSERT()` in the release build? Let's take an example:

```
igraph_bool_t FUNCTION(igraph_stack, empty)(TYPE(igraph_stack)* s) {
    IGRAPH_ASSERT(s != NULL);
    IGRAPH_ASSERT(s->stor_begin != NULL);
    return s->stor_begin == s->end;
}
```

I think there is value in keeping `IGRAPH_ASSERT(s->stor_begin != NULL);` because it is a common programming mistake when a data structure is freed (which sets internal pointers to zero) and is accessed again. We had several instances of bugs like this which were present in releases. Using `IGRAPH_ASSERT()` ensures that when a user hits such a bug, they get a nice error message (which is useful for us) and they avoid a crash.

As for `IGRAPH_ASSERT(s != NULL);`, I think this could be an `assert()`. This assertion is useful while developing igraph itself, or developing C programs that use igraph. But I think it is unlikely that this would ever get triggered in a released (= well debugged) version, as most of the time `igraph_stack_t` is created on the stack, not on the heap, so there are not many cases when it can become `NULL`.

There is one more interesting reason for keeping _some_ assertions in release builds. In some cases they can [significantly improve performance](https://stackoverflow.com/a/47183046/695132) by allowing the compiler to optimize for the specific case declared in the assertion.

**Comment by szhorvat** [comment]
IMO this doesn't necessarily need to be fixed. It is the nature of C programming that when some preconditions are not satisfied when calling a function, the result is a crash. Getting an error message is of course nicer and aid debugging, but this situation is trivial: it is obvious that the attribute handler needs to be set up before working with attributes.

**Comment by GroteGnoom** [comment]
> IMO this doesn't necessarily need to be fixed. It is the nature of C programming that when some preconditions are not satisfied when calling a function, the result is a crash.

But in this case we can check for it.

> Getting an error message is of course nicer and aid debugging, but this situation is trivial: it is obvious that the attribute handler needs to be set up before working with attributes.

It wasn't obvious to me what was going on. Of course if you know everything about igraph, then this stuff could become trivial. But dealing with attributes is hard enough as it is, adding clear error messages could really help people like me who are trying to figure things out. When things are nicer and aid debugging we should do them.

**Comment by szhorvat** [comment]
It's good to note here that `SETEAN` is specific to the C attribute handler. It can only be used with this one specific attribute handler, not with anything else. So if we wanted to fix this _right now_, it would not be sufficient to check that an attribute handler is set. It would also be necessary to check that it is indeed the C attribute handler.

Furthermore, it is not enough to call `igraph_set_attribute_table()` before `SETEAN`. In fact it needs to be called before any graph is created. Otherwise the `graph->attr` will be `NULL`.

I suggest that if this is fixed at all, it should be done with assertions (not errors), and that the fix should only be done after the attribute handler interface has been overhauled, or such an overhaul has at least been discussed. It has been bother me for a long time now that there is no way to modify graph attributes in a general way. The general interface provides ways to add attributes when the graph is created, but not to modify existing attributes. That is done differently with each attribute handler.

**Comment by szhorvat** [comment]
Ref: https://github.com/igraph/igraph/issues/2073

**Comment by ntamas** [comment]
I tend to agree with @szhorvat here. There are multiple reasons why we should probably not put much effort into fixing this:

1. This is C, there are multiple ways to shoot yourself in the foot, we cannot protect the user from all of them.
2. As @szhorvat said, `SETEAN` is specific to the C attribute handler only, it works if and only if you use our own C attribute handler, not if you are in Python world or R world or if you made up your own attribute handler (which you could in theory do).
3. The attribute handler interface is incomplete, so if we want to start cleaning up, we should start the cleanup there, and it might turn out that the whole C attribute handler would have to be redesigned anyway.

To put things into historical context: initially the whole problem of handling attributes was put aside completely, the saying was that igraph is concerned with storing the graph itself, it is your responsibility to store the metadata, and to update the metadata if the graph changes. Then the R interface came, and the Python interface came, and we started supporting reading attributes from files and writing attributes to files, and suddenly there was a need for certain parts of igraph's code to _read_ attributes from the graph (for the purpose of writing them to a disk-based format), or to _create_ new graphs with attributes (when reading those files back from disk), without knowing what host language is responsible for storing the attributes (and how), and thus the current attribute handler interface was born. We also created a rudimentary implementation of the attribute handler interface in C, mostly for educational purposes and for examples and test cases. Both the interface and the C implementation have largely been unchanged ever since.

The biggest problem with the current interface is that there is no way to _set_ an attribute value without knowing what sort of attribute handler is attached to the graph. Another limitation is that there is one library-level attribute handler, so you cannot have multiple graphs with different types of attribute handlers -- not sure if that will ever be needed, though.

I'm voting for deferring the fix for this issue after we have decided what we shall do with the attribute handler interface to fix these shortcomings. See #2073 for that.

**Comment by ntamas** [comment]
should have been "not planned", sorry
