### ISSUE TITLE
Remove headers from all examples

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#1949]
Headers like `/* -*- mode: C -*-  */` and copyright headers make the examples less fit for inclusion in the docs. They should all be removed.

But first check if copyright holders agree with it 😄

**Comment by szhorvat** [comment]
I fully support this.

**Comment by ntamas** [comment]
The license notices (I guess that's what you mean by "copyright headers") should be left in the source files, but we can add a preprocessor that removes them from the examples. Something like `tools/removeexamples.py`, but _before_ we feed the source code to the source code highlighter.

**Comment by ntamas** [comment]
Of course this does not apply to editor-speciic headers like `/* -*- mode: C -*- */` or `/* vim:set ts=4 sw=4 sts=4 et */`, those can be removed.

**Comment by szhorvat** [comment]
Can you give some reasoning for why these notices should be included in the example source files? Is there any reason these should be "protected"?

**Comment by ntamas** [comment]
I answered briefly on Slack, but basically, I think that if you don't have a license notice in the file, then it is copyrighted by its author and you are not allowed to just take it and do whatever you want with it. (I'm not a lawyer so YMMV). If you want to state that anyone is free to do anything with the example, then you can put it under a more permissive license, but then you still need a license notice. Removing the license notice from a file is not the right way of saying "feel free to do anything with it" -- which would be our goal here.

**Comment by szhorvat** [comment]
Then put a notice in the `examples` directory and say that it applies to all files.

**Comment by ntamas** [comment]
https://www.gnu.org/licenses/gpl-faq.html#WhyMustIInclude

**Comment by szhorvat** [comment]
Frankly, this is quite silly. These things are not covered by the laws of physics, but by agreements between people. I can give away whatever document I want without putting a page-long license notice at the top. If people use that document, I won't complain, and won't sue them. It's as simple as that.  These notices are used to protect the author, not to protect the user.

Also, what you linked is specifically about the GPL, and specifically about placing literal copies of the GPL in a repository. This is not what I suggested. If you are concerned that people won't dare to use the examples, then put a readme file in the same directory, and state that anyone can do whatever they want with these examples. Licensing under GPL is not useful.

**Comment by ntamas** [comment]
I don't want to go into lengthy debates about what makes sense or what does not make sense regarding the application of the GNU GPL so I just added a pre-processor script in fb3ef9e26 that strips the license notices from the examples when they are included in the documentation. I hope that this is satisfactory for everyone.

(One other reason why I don't want to remove the license notices from the examples is because these examples are installed on the end user's system when installing igraph from a Debian package, and Debian package maintainers might be forced to add the license notice back so their internal linter tools (`licensecheck` etc) do not complain).
