### ISSUE TITLE
Support for large random integers

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#1987]
`igraph_rng_get_integer()` should support large (larger than `2^31 - 1`) integers when building in 64-bit more, and should return `igraph_integer_t` instead of `long int`.

Once concern that was brought up before was: it is good to ensure that the RNG behaves identically on 32-bit and 64-bit platforms. This can be achieved: there can be two branches of the implementation depending on whether the `h` parameter (upper limit) exceeds the largest signed integer representable on 32 bits.

Notes:

 - I am not suggesting that the underlying RNG implementation should use 64 bit integers, only that the high-level `igraph_rng_get_integer()` function should be able to produce them.
 - We also have a `get_int31()` function. This is generating the RNG's largest possible native type. Perhaps we want to rename it to indicate that, in case we ever want to allow 64-bit RNGs.
 - `get_integer()` and `get_int31()` are the only two functions returning an integer type. All other integer-valued samplers, such as the geometric one, return an `igraph_real_t`. It is not an unreasonable possibility to let `get_integer()` return an `igraph_real_t` as well, but I am not in favour.

**Comment by ntamas** [comment]
One problem that we might be running into when allowing 64-bit random numbers on 64-bit platforms is that igraph functions relying heavily on random numbers will give different results on 32-bit and 64-bit platforms, even in unit tests, and even if we seed the RNG first in the unit test.

So, something like this:

```python
g = Graph.GRG(100, 0.2)
comm = g.community_label_propagation()
assert comm.membership == [...some_expected_result...]
```

will fail on either 32-bit or on 64-bit platforms, unless we provide the expected result for both cases. This is not a vote for or against the proposed change, just something to be aware of.

On the other hand, ensuring reproducibility is a hard problem anyway: even if we provide an RNG that works the same way on both 32-bit and 64-bit platforms, the host language might use its own RNGs differently, or the behaviour of the host RNG might change between versions and we cannot do anything about that. So, it's not entirely up to us. I think igraph's job would be to ensure that if someone wants to achieve reproducible results, then igraph should not stand in its way. This could be achieved by letting the "default" RNG in igraph to use the full 64-bits on 64-bit platforms, but then we should provide a "reproducible" RNG for cases when reproducibility is more important than performance.

But, here's another thing to consider: what do we gain by generating a 64-bit random number if all that the caller wants is a random number between 0 and, say, 15? (Think about someone repeatedly genearting uniform random integers between 0 and 15, inclusive, by calling `igraph_rng_get_unif`). We would generate 64 random bits and then throw away 60 of them. This could even hurt performance in the long term.

**Comment by szhorvat** [comment]
> But, here's another thing to consider: what do we gain by generating a 64-bit random number if all that the caller wants is a random number between 0 and, say, 15?

We don't.  `igraph_rng_get_integer()` takes two arguments for the upper and lower limit. Let's say the low one is zero. If the high one is smaller than `2^31 - 1`, and my low-level RNG give me 31-bit raw integers, then I can generate my `igraph_integer_t` from a single raw integer.  This would always be the case on 32-bit platforms.  If the high one is greater than `2^31-1`, then we use two raw integers to fill out all random bits.

Thus:

 - The sequence of values will not be different on 32- and 64-bit platform. 64-bit platforms are simply capable of working with larger numbers. But if we take a program that can run on 32-bit without overflow, and move it to 64-bit, the output will not change.
 - When generating a random `igraph_integer_t`, we will not generate more raw random integers than is necessary.

**Comment by vtraag** [comment]
Just adding here that it might be worth looking into fast RNG for integers, see the implementation at https://github.com/lemire/FastShuffleExperiments and the associated publication at https://arxiv.org/abs/1805.10941.

**Comment by ntamas** [comment]
This is now done in the `feat/rng-refactoring` branch, which I'l submit for a round of reviews as a PR soon(ish).

Specific points:

* `igraph_rng_get_integer()` now works with `igraph_integer_t` so it can return 64-bit results when igraph is compiled with 64-bit support.
* Under the hood, we have `igraph_i_rng_get_uint()` and `igraph_i_rng_get_uint_bounded()`, which return an `igraph_uint_t` in a range that is bounded by zero from below and optionally by some specific number from above. The implementations of these functions ensure that if the range is less than 2^32, then the generator behaves the same way on 32-bit and 64-bit platforms. So, we are good in unit tests as long as we don't start using more than the 32-bit range.
* `igraph_rng_get_unif01()` has a resolution that is equal to the number of random bits generated by the RNG _in a single round_. This is again to ensure consistent behaviour on 32-bit and 64-bit platforms. According to recommendations I've found on the Internet, we now use `ldexp()` to generate the double instead of division because it is faster and less biased.
* I've also added PCG32 as a random number generator; we might switch to it in the future, but the default is still the Mersenne Twister.
