### ISSUE TITLE
igraph_list_triangles() should return a matrix, not a vector

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2034]
`igraph_list_triangles()` returns a vector of concatenated triplets. Instead, it should return a matrix, either n-by-3 (makes more sense to me) or 3-by-n (achievable by wrapping the current result in a `matrix_t`, as matrices are stored in column-major order).

**Comment by szhorvat** [comment]
We need to make a decision here.

When returning `n` vectors of length `m` each, do we use an `n*m` or an `m*n` matrix? There is value in using a matrix instead of a vector list, as it's not only more efficient to store in igraph, it's sometimes much more efficient to transfer to a host language (thinking of Mathematica here).

 1. **Argument for `n*m`:** It may be more natural to expose it in high-level languages. For example, if the vectors are `[1,2,3]` and `[4,5,6]` then the only sensible result in Python is `[[1,2,3], [4,5,6]]`, and the same in Mathematica. However, in Mathematica I already transpose most matrices anyway, to go from igraph's column-major format to Mathematica's row-major, so there wouldn't be any savings from using this format. I'm not sure about R: I think it can treat an underlying vector either as column- or row-major?

 2. **Argument for `m*n`:** igraph uses column-major storage, so this is natural. When generating the list of `m`-sized vectors, it may not be known in advance how many there will be in total (i.e. `n`). Thus it is most efficient to first fill up a vector with all `m*n` elements, using `push_back`, then wrap this `vector_t` with a `matrix_t`, taking advantage of the column-major order and avoiding copying.  If some host language makes transposing necessary, it should be done in that host language, or in the glue code between it and igraph. Inefficiencies that are not necessary to have for _all_ interfaces should be kept out of the C core.

After having thought more about this, I vote for choice (2). This is because it it easier to implement efficient algorithms in the C core, and because transposition can be done in high-level languages on a per need basis.

Agreed? Opinions?

**Comment by szhorvat** [comment]
In order to be able to go ahead with this, we will need some new core functions. The problem is that there is currently no way to efficiently push to a matrix, in a way similar to `vector_push()`, nor do I see a simple _and performant_ way to implement one.

Instead, I would prefer to have a new function that _moves_ (not copies!) the contents of a vector into a matrix of the same type, without reallocation. Then the implementation can fill up a vector with `push_back()`, as usual, then finally convert that vector into a matrix, without any re-allocation or copying.

What would be the best interface for such a function, and what should happen to the vector after we have moved its contents? Comparable functions are `strvector_merge()`, which clears the vector and `vector_list_push_back()` which invalidates the vector (sort of kind of...)

**Comment by ntamas** [comment]
`igraph_matrix_init_from_vector()` would be a good name for such an operation, and I think we can simply say that the vector becomes a _view_ into the original data (as if it was created with `igraph_vector_view()` into an existing array) and ownership is transferred into the matrix. For sake of completeness, we could also add:

* `igraph_matrix_view_from_vector()`, which is the same but the vector retains ownership of its elements and the matrix becomes a view into this vector.
* `igraph_matrix_init_from_vector_copy()`, which copies the data from the vector into the matrix and thus both objects can retain ownership of their individual elements.

And of course we could have the opposite operations as well, going from matrix to vector.

All of this assumes that there is indeed a need to convert the output of `igraph_list_triangles()` from a vector into a matrix. After all, if we add `igraph_matrix_init_from_vector()`, then the user already has a way to turn the output of `igraph_list_triangles()` into a matrix with an extra function call. I cannot decide whether the matrix or the vector representation is more convenient. One thing is for sure: if you want to get the edge IDs of the triangles, this is easier with a vector because you can simply call `igraph_expand_path_to_pairs()` followed by `igraph_get_eids()`, while you cannot do the same thing with matrices (unless you convert the matrix back to a vector).

**Comment by szhorvat** [comment]
> I cannot decide whether the matrix or the vector representation is more convenient.

In a high-level language, clearly it's the matrix representation, or rather some sort of "list of triplets" representation. I want to be able to get the `k`th triangle easily. The `i`th vertex of the `k`th triangle has 1-based index `(k-1)*3 + i + 1`, which is some mental strain to write correctly. I just want to write `triangles[k][i]` or similar. Ideally I want to write it in a way that's the same regardless of using 0-based or 1-based indexing.

In C, it's less clear which is the good representation. I think it's important to use a representation that can be constructed efficiently, so it has an underlying vector that can be pushed to. I don't insist that we have to use the matrix representation in C.

**Comment by ntamas** [comment]
> In a high-level language, clearly it's the matrix representation, or rather some sort of "list of triplets" representation

Yes, there's no debate about that.

If we decide to go for a matrix representation in C, I totally agree with your assessment that it should be a matrix backed by a vector that is filled with the triangles, and that the matrix should present the triangles in column-major order. All that we need is to decide whether we want a matrix or a vector. I see no advantage of using a vector now if you add the functions that I outlined above for conversion from a vector to a matrix, and there is indeed a disadvantage about the indexing, as you mentioned. I'm slightly leaning towards changing `igraph_list_triangles()` to return a matrix.

**Comment by szhorvat** [comment]
To me, the most appealing solution mentioned so far is a matrix as a view into a vector. I.e. the matrix is read-only. Then we let the function return a vector and let users wrap it by a matrix for easy indexing.

**Comment by szhorvat** [comment]
One of the complicating factors is that if the function returns a matrix, then it takes an initialized matrix as input. If the public API only provides views, we cannot handle this. We need to somehow take the vector backing the matrix, then push to it, then update the matrix dimensions accordingly. It seems a bit complicated to do this.

We would need a function that doesn't _init_ a matrix, but somehow updates it from a vector without reallocation. It is difficult to fit this into a simple and intuitive framework.

**Comment by ntamas** [comment]
This is now done in 127558330 and bbce7d94d
