### ISSUE TITLE
Inconsistent modularity value for edgeless graph across community detection functions

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2044]
When passing in an edgeless graph, such as a singleton graph or two isolated vertices, most community detection functions return `NaN` for the modularity, but some return `0.0`. `igraph_modularity()` would return `NaN`.

The ones that return `0.0` are `igraph_community_fastgreedy()` and `igraph_community_walktrap()` (even after PR #2043).

Do we care about this at all, and do we want to fix it?

Note that the modularity of a single vertex with a self-loop is computed as 0, so it seems a bit pointless to bother with these details.

**Comment by szhorvat** [comment]
A related issue is the modularity result given for a null graph. This is usually NaN, but there are outliers again:

 - `fastgreedy()` gives the vector `(0.0)`.
 - `edge_betweenness()` gives an empty vector `( )`.
 - `walktrap()` gives `( )`.

These outliers are the hierarchical methods. (`leading_egenvector()` is also hierarchical, but it does it the opposite way: splits instead of merges, and does not return a modularity vector).

There are two reasonable approaches here:

 1. We can say that the modularity vector length is always the same as the number of vertices, so the result should be `( )` for the empty graph.
 2. We can say that `modularity[i]` gives the modularity _before_ performing merge `i`. This way, the modularity vector has one more element than the list of merges. When there are no merges, as with either the singleton or the empty graph, the modularity vector should have a single element, representing "each vertex belonging to its own separate community".

IMO approach 2 is the more useful here: it makes it possible to simply take `max(modularity)` for `modularity` vectors returns by hierarchical methods, to choose the "best" modularity. I expect that users _will_ compute `max(modularity)` either way, and most high-level languages will just return `-Inf` for `( )` which is again inconsistent with everything else.

**Comment by ntamas** [comment]
I think the correct result for the modularity of an edgeless graph is `NaN` and functions that do not return `NaN` should be fixed. Zero makes sense only if there is at least one edge; otherwise you are dividing zero with zero in the modularity formula, which should be NaN (unless there is a strong argument that the numerator is a "strong zero" and the denominator is a "weak zero").

Re the modularity vector returned from iterative functions: yes, we can argue that `modularity[i]` is the modularity _before_ performing merge `i`; however, note that for edgeless graphs we should still return `NaN` and not zero in that single element of the modularity vector.

**Comment by szhorvat** [comment]
@ntamas These are fixed on https://github.com/igraph/igraph/tree/fix/clustering-null Have a look and merge if you see no issues. Maybe we can even have it in R/igraph 1.3.1 ...

**Comment by ntamas** [comment]
Merged `clustering-null` into `master` so this should be okay now.
