### ISSUE TITLE
GML writer should skip NaN values

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2055]
[The GML spec](https://web.archive.org/web/20190207140002/http://www.fim.uni-passau.de/index.php?id=17297%26L=1) does not include support for `NaN` / `Inf`. This is an igraph extension.

When reading GML files, igraph will use NaN for missing numerical values. This is consistent with other parts of igraph, but it also means that there is a high chance that reading in a GML file and writing it back will create NaNs, which are technically not compliant with the spec. I did not verify if other systems handle NaNs.

This is a proposal to change the GML writer so it skips writing NaN values for numerical attributes. This does not affect round-tripping, since missing values are read back as NaN anyway. The only exception is when all values of a numerical attribute are NaN, as in this case the attribute will be completely gone.

----

Example input file:

```
graph [ 
  node [ name "A" val 1 ] 
  node [ name "B" ]
]
```

Reading this in and writing it again produces:

```
Creator "igraph version 0.10.0-dev+df6f3665 Sat May  7 10:10:00 2022"
Version 1
graph
[
  directed 0
  node
  [
    id 0
    name "A"
    val 1
  ]
  node
  [
    id 1
    name "B"
    val NaN
  ]
]
```

The proposal is to produce:

```
Creator "igraph version 0.10.0-dev+df6f3665 Sat May  7 10:10:00 2022"
Version 1
graph
[
  directed 0
  node
  [
    id 0
    name "A"
    val 1
  ]
  node
  [
    id 1
    name "B"
  ]
]
```

Any objections @ntamas ?

**Comment by szhorvat** [comment]
I checked that neither yEd nor networkx will read a file with NaN values. This tells me that we need to handle this better. I will go ahead with this change.

**Comment by szhorvat** [comment]
Remaining question @ntamas, should we issue a warning when writing Inf/-Inf? This produces a non-conformant GML that apparently can't be read by several other software (but it can be read by igraph). I would not forbid writing Inf, but I would issue a warning.

**Comment by szhorvat** [comment]
Warning added. This is a reasonable safety measure.

**Comment by ntamas** [comment]
Back from the weekend, and yes, I agree with everything you've done here, so that's great.

From a philosophical point of view, I think a read-write cycle should be idempotent if possible, at least for valid files. So, if we read a GML file from the disk that does not have numeric values for certain attributes, and we replace those with NaN, it feels natural to replace NaNs back into missing attributes when writing the file, especially because NaN is not a valid value according to the GML spec.

For strings, the case is different: we need to replace missing string attributes with empty strings, but we cannot turn those empty strings back into missing attributes because an empty string is a perfectly valid attribute.
