### ISSUE TITLE
Dijkstra algorithm time complexity

### ISSUE THREAD

**Issue by RicoFio** [igraph/igraph#2098]
**Describe the bug**
In the following sections of the documentation [get_shortest_path_dijkstra](https://igraph.org/c/doc/igraph-Structural.html#igraph_get_shortest_path_dijkstra), [get_shortest_paths_dijkstra](https://igraph.org/c/doc/igraph-Structural.html#igraph_get_shortest_paths_dijkstra), and [shortest_paths_dijkstra](https://igraph.org/c/doc/igraph-Structural.html#igraph_shortest_paths_dijkstra) (non-exhaustive list), the time complexity for the computation is referred to as `O(|E|log|E|+|V|)` or `O(s*|E|log|E|+|V|)` respectively.

However, all the literature I can find on the complexity analysis of the Dijkstra algorithm's time complexity using a binary heap is `O(|E|+|V|*log|V|)` (e.g. [see here](https://iq.opengenus.org/time-and-space-complexity-of-dijkstra-algorithm/)). I assume here a binary heap as that is the graph representation referred to in the documentation.

In case of a Fibonacci Heap, the time complexity would be `O(|E|*log|V|)` (see link above).

Hence, I am confused as of where the `O(|E|log|E|+|V|)` originates from?

Furthermore, it is also not specified whether the Dijkstra algorithm used has any limitations on the graph structure, i.e. is the algorithm applicable also to non-negatively weighted, directed, multi-graphs?

I am not sure whether this issues is within the Python interface or would have better been placed in the igraph root-package. Any suggestions are welcome!

**Comment by szhorvat** [comment]
> is the algorithm applicable also to non-negatively weighted, directed, multi-graphs?

Yes it is. Generally, functions should work on any graph, including directed and undirected, simple or non-simple, unless mentioned otherwise. This applies to the C core documentation. The Python and R interface documentations may take a different approach—I can't comment on that.

I'll look into the complexity issue a bit later.

**Comment by ntamas** [comment]
Could it be the case that the difference lies in the fact that we use incidence lists instead of adjacency lists in the algorithm, anticipating the possibility of multiple edges between the same pairs of nodes? All the theoretical treatment of the algorithm that I've found on the Internet sidesteps the problem of multiple edges and simply assumes that there is only a single edge between any pair of vertices.

Note that even if there are multiple edges, we should simply pick the one with the lowest weight and ignore the rest, and we could detect multiple edges in O(|E|) time as we already have the incidence list representation, so I'm not saying that we cannot achieve the claimed `O(|V| log |V| + |E|)` complexity, it's just that our particular implementation does not achieve that at the moment.

**Comment by szhorvat** [comment]
> Could it be the case that the difference lies in the fact that we use incidence lists instead of adjacency lists in the algorithm, anticipating the possibility of multiple edges between the same pairs of nodes?

Looking at the code, it appears that a new vertex will only be pushed to the heap if it does not already contain it. Thus the heap size should not be able to exceed $|V|$. It seems to me that the docs are incorrect, and the core loop has complexity $|E| \log |V|$. Additionally, there's the initial initialization of $|V|$-size data structures, which gives $|V| + |E| \log |V|$.

I will correct the docs.
