### ISSUE TITLE
Document basic types and size limits

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2100]
Things like the following should be documented:

`igraph_integer_t`, `igraph_real_t`, `igraph_uint_t`, `IGRAPH_INTEGER_MAX/MIN`, `IGRAPH_PRId/u`, `IGRAPH_VCOUNT/ECOUNT_MAX`.

There was a complaint about these not being sufficiently documented.

I created a new `0.10.x` milestone for this, meaning that it doesn't block 0.10 but nor should it be left for 0.11.

**Comment by ntamas** [comment]
I guess we would need a separate section in the documentation dedicated to the igraph-specific integer and real types. Question is: where to put it? One candidate would be chapter 7 ("Data structure library: vector, matrix, other data types"); another option is chapter 4 ("About igraph graphs, the basic interface"). I wouldn't introduce these any earlier even though the tutorial uses them because we should focus on getting the user through the tutorial first before diving into the intricacies.

**Comment by szhorvat** [comment]
I'm not sure, that's why I didn't start doing it ... I guess it's better in 4 than in 7. Alternatively, we can add a new chapter that explains some of the basic concepts, naming conventions, how stuff is set up, etc. in more details than a tutorial would.

**Comment by ntamas** [comment]
I'm thinking about bringing this forward to 0.10.0 as we'll have a lot of explaining to do anyway due to the extensive set of changes.

**Comment by szhorvat** [comment]
If not too much trouble, can you update the docs on the website? It's just so much more pleasant to read, and it shows in the docs with their final formatting (e.g. code box widths).

**Comment by szhorvat** [comment]
This is good, it can be closed.
