### ISSUE TITLE
Does Bellman-Ford need to check for duplicate 'to' vertices?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2104]
`distances_dijkstra()` disallows duplicates in the `to` argument. Presumable they would cause trouble in the algorithm.

`distance_bellman_ford()` does not have a check for them. Will something go wrong when duplicates are passed in? This needs to be verified.

**Comment by ntamas** [comment]
Actually, `igraph_distances_bellman_ford()` claims in the documentation that it is an error to have a vertex multiple times in the `to` vector, but the implementation seems fine even if there are duplicates.

In the Dijkstra algorithm, the result matrix is updated in tandem with the progress of the algorithm, and when you reach a vertex `w` from a source vertex `v`, you need to know which column of the matrix should be updated. (The row index is trivial, the rows proceed in the order in which the source vertex iterator yields the source vertices). This is done by building a vector that maps `w` back to its column index. That's why you cannot have duplicates.

In Bellman-Ford, a separate distance vector is used for keeping track of stuff, and this distance vector is written back to the result matrix at the end of the iteration of the outer loop, so there's no need for an index. Presumably, `igraph_distances_dijkstra()` could be built in the same way if you wanted to support the same target vertex appearing multiple times in the `to` iterator.

**Comment by szhorvat** [comment]
OK, so it sounds like you verified that Bellman-Ford works correctly? Can you add a comment at this position, to avoid future confusion?

https://github.com/igraph/igraph/blob/develop/src/paths/bellman_ford.c#L124

That's where Dijkstra/unweighted have the check.
