### ISSUE TITLE
eit_create() and vit_create() must check that IDs are valid

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2110]
`igraph_eit_create()` and `igraph_vit_create()` create an iterator (ties to a specific graph) from a selector (which is an abstract object that can contain any edge/vertex IDs).  This issue is a TODO item to make sure that the iterator creation functions verify that all edge/vertex IDs coming from the selectors are valid for the given graph. Note that there are many code paths, only some of which can receive arbitrary IDs. All these should be verified.

**Comment by ntamas** [comment]
Okay, so here's what I've found by the type of the edge selector (i.e. `es.type`):

* `IGRAPH_ES_ALL`, `IGRAPH_ES_ALLFROM`, `IGRAPH_ES_ALLTO`, `IGRAPH_ES_NONE`: these are easy, the user cannot input any vertex/edge IDs directly
* `IGRAPH_ES_INCIDENT` takes a vertex ID and pipes it through `igraph_incident()`, which checks whether the vertex ID is valid.
* `IGRAPH_ES_1`: edge ID is checked within `igraph_eit_create()`
* `IGRAPH_ES_VECTOR`, `IGRAPH_ES_VECTORPTR`: edge IDs are checked within `igraph_eit_create()` with `igraph_vector_int_isininterval()`
* `IGRAPH_ES_SEQ`: edge IDs are checked within `igraph_eit_create()`, but it allows `to` to be larger than the number of edges in the graph, which is probably a problem and should be fixed
* `IGRAPH_ES_PAIRS`, `IGRAPH_ES_PATH`: all vertex IDs in the input vector are eventually sent to `igraph_get_eid()`, which handles out-of-bounds vertex IDs
* `IGRAPH_ES_ALL_BETWEEN`: vertex IDs in the input are checked explicitly in `igraph_i_eit_all_between`.

So we seem to have a minor problem in `IGRAPH_ES_SEQ` only.

As for vertex selectors:

* `IGRAPH_VS_ALL`, `IGRAPH_VS_NONE`: trivial
* `IGRAPH_VS_1`, `IGRAPH_VS_VECTORPTR`, `IGRAPH_VS_VECTOR`: vertex ID validity checked directly in `igraph_vit_create()`
* `IGRAPH_VS_SEQ`: not checked, so that's a problem
* `IGRAPH_VS_ADJ`, `IGRAPH_VS_NONADJ`: the vertex ID is passed to `igraph_neighbors()`, which takes care of the validation

Again, we seem to take care of `IGRAPH_VS_SEQ` only.

**Comment by szhorvat** [comment]
Something seems wrong in the creation of a `seq` type edge iterator from a `seq` type edge selector.

It was my impression that `igraph_eit_t::end` points _one past_ the last edge index. This is consistent with this line:

https://github.com/igraph/igraph/blob/master/src/graph/iterators.c#L1804

as well as with:

```c
#define IGRAPH_EIT_END(eit)   ((eit).pos >= (eit).end)
```

In `es_seq`, the `to` value is inclusive, i.e. it is the last index to be considered, _not_ one past it: https://github.com/igraph/igraph/blob/master/src/graph/iterators.c#L1112 

So here a `+ 1` is missing, no?

https://github.com/igraph/igraph/blob/master/src/graph/iterators.c#L1857

Same thing for the vertex iterator:

https://github.com/igraph/igraph/blob/master/src/graph/iterators.c#L774

Am I missing something?

This should be fixed for 0.9.10.

**Comment by szhorvat** [comment]
Regarding the interpretation of the `to` value in `vs_seq` and `es_seq`. It seems the history is as follows:

Originally, the `\param` documentation stated that `to` is the last id to be included, so the range was supposed to be inclusive. When @GroteGnoom wrote unit tests for this functionality, he noticed that this was not the case and added a note to the documentation that: 

> This includes <code>from</code> and excludes <code>to</code>.

So right now the documentation is inconsistent.

The question is then: Do we fix the behaviour to follow the _original_ documentation, i.e. `to` being inclusive? Or do we keep the current behaviour, and update the docs?

At first blush, it seems natural to keep the current behaviour and update the docs to follow it. But this would actually cause inconsistencies with other parts of igraph. Wherever I find integer ranges, they are inclusive. `igraph_vector_init_seq` uses inclusive `from` and `to`. `RNG_INTEGER` uses an inclusive range. **Thus I vote for using an inclusive range.**

Where are the `vs_seq` and `es_seq` selectors used?

 - They are _not_ used in any of the high-level interfaces.
 - They are used in their own unit test, which was recently added. Here of course the range is assumed to be exclusive. The docs were partially updated when adding this test.
 - They are used in benchmarks, which I might have written myself (?) before the docs were updated, and code assumes that the range is inclusive.

@ntamas @GroteGnoom Do you mind if I go ahead and fix the behaviour to use an inclusive range, as _originally_ documented?

**Comment by ntamas** [comment]
I think that the inclusivity of both endpoints originates from igraph's R heritage, where all intervals are inclusive for both endpoints. In C (and in 0-based indexing), it's more natural to have the start as inclusive and the end as exclusive. `igraph_vector_init_seq` is probably ill-designed for the very same reason.

But anyhow, if inclusive endpoints seem to be predominant now in igraph, it's probably better to adapt `es_seq` to `vs_seq` (towards the majority).

**Comment by szhorvat** [comment]
OK. Let me know when #2115 can be merged.
