### ISSUE TITLE
Some functions that create simple graphs should set the cache

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2122]
There are some functions which explicitly create simple graphs. These should immediately set the cache to indicate that the graph is simple.

Specifically:

 - [ ] igraph_simplify
 - [ ] igraph_simplify_and_colorize

----

There are also many graph generators which create simple graphs. I suggest NOT to set the cache in these because the risk of a bug is high. See e.g. the issue where the G(n,p) generator can create multigraphs due to esoteric overflow issues, or the considerations about whether `igraph_ring` and `igraph_lattice` should create simple graphs. What's a 1-vertex or 2-vertex "ring"? We recently moved to non-simple graphs for that function.

**Comment by ntamas** [comment]
I'm still not too fond of the idea of pre-populating the cache as it means extra code with marginal benefits.

Thinking aloud: suppose that we make `igraph_simplify()` to declare in the cache that the graph is simple. What do we gain from it? We will save the cost of an `O(|V| + |E|)` call later in some other igraph function to `igraph_is_simple()`. If we don't populate the cache in advance, we pay the `O(|V| + |E|)` cost but there is a high chance that the function that actually needs the result of `igraph_is_simple()` as a pre-test has a runtime complexity that dominates `O(|V| + |E|)`, so we won't shave off anything significant from the overall computation time. And note that if the function is executed multiple times on the _same_ graph, the first invocation of `igraph_is_simple()` would populate the cache anyway, so the `O(|V| + |E|)` cost is paid only once.

> There are also many graph generators which create simple graphs. I suggest NOT to set the cache in these because the risk of a bug is high.

Following the same train of thought: I'd say that the risk of a bug in `igraph_simplify()` is definitely larger than the risk of a bug in `igraph_is_simple()` (due to the complexity of the implementation), so if we do the caching in `igraph_simplify()`, we have a higher chance of accidentally caching the wrong result than if we do the caching in `igraph_is_simple()`.

My suggestion would be to wait for the first real-life use-case to pop up where _not_ caching in `igraph_simplify()` results in a measurable performance penalty compared to doing the caching there (i.e. measure first, don't do premature optimization). If we find such a case, I would be convinced that it's the right thing to pre-populate the cache in `igraph_simplify()`.

**Comment by szhorvat** [comment]
This was motivated by the discussion about caching and VF2. There is a specific use case of checking whether the graph is simple before performing the isomorphism test, and if not, using `simplify_and_colorize()` in conjunction with VF2. Having `simplify_and_colorize()` set the cache saves one simple graph check. See #2123.

Another way to save this check is to have two versions of VF2: a public version which does the check and an internal version which does not. But this, IMO, is not as nice/clean as relying on the cache.

**Comment by szhorvat** [comment]
I still think that `igraph_simplify()` is sufficiently commonly used that in this case it's worth setting the cache. It makes sense to make this decision on a case-by-case basis for each function. I agree that the majority should not set the cache, but I think here it's worth it.



> but there is a high chance that the function that actually needs the result of `igraph_is_simple()` as a pre-test has a runtime complexity that dominates `O(|V| + |E|)`

My motivation for proposing the cache was precisely that this is not always  the case. With functions that have higher-than-linear complexity, it made sense to add the check even before caching was introduced (at least I went ahead and added it without worried). But with linear-time functions, or functions which are linear not in the graph size, but in the result size (e.g. compute result for only some of the vertices instead of all of them) we need to be careful not to introduce a significant slowdown. There are also functions which have a fast path and a slow path. Consider isomorphism testing, which is slow in general, but can be short circuited to an O(1) path when the edge or vertex counts do not match.



> Following the same train of thought: I'd say that the risk of a bug in `igraph_simplify()` is definitely larger than the risk of a bug in `igraph_is_simple()` (

Yes, sure, but this is not black and white. There is a continuum of risk. We need to consider tradeoffs, and decide where to draw the line. I think `igraph_simplify()` is sufficiently prominent that in this case it's worth it. For as long as not too many functions set the cache, the risk can be managed. Also consider that `igraph_simple()`, or most other similar functions, are well-tested and rarely modified. Compare this to graph constructors, which are frequently added, many are rarely used, and some are contributed by inexperienced people. 

> (i.e. measure first, don't do premature optimization)

The "premature optimization" argument does not apply here. Implementing this is (much) less work than measuring, and only increases the complexity of code marginally. The change itself is low-risk, and does not increase the maintenance burden for the future.

**Comment by szhorvat** [comment]
Based on my judgement, here are the functions I would set the cache in, just to show you that it is not many. This is in rough order of decreasing priority.

 - simplify
 - subgraph
 - permute
 - disjoint_union

Of these, I expect `simplify` and `subgraph` to bring noticeable gain, with the other two being less frequently used.

Some of the rest of the graph mutation operators _could_ in principle set some cache bits, but doing it correctly is requires much more care, so I don't suggest we do it there.

**Comment by szhorvat** [comment]
Here's my proposal. Let's first test 0.10 with the new cache system and make sure that it's fine and we get no complaints. Then add this improvement in 0.10.x.

**Comment by ntamas** [comment]
Agreed, that sounds good for me.
