### ISSUE TITLE
We should update our CI to test with a recent non-Apple Clang.

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#2129]
_Originally posted by @szhorvat in https://github.com/igraph/igraph/issues/2128#issuecomment-1193102072_

Clang sometimes warns about things that no other compiler warns about. Then sometimes when a new version of Clang comes out, or igraph is changed, Clang can't be used to build igraph because there's a new warning (that will be turned into an error with -Werror. Also, the warnings could mean there's a problem in our code.

**Comment by szhorvat** [comment]
I added this, but I'm worried that we have too many tests in CI.

Does anyone object to disabling the `linux_shared_external` test? Right now I can't think of a situation where this test something not covered by the others. Another option is to combine this setup with another test, i.e. just move another test to use clang.

Note: This is explicitly asking for `ubuntu-22.04` so that we can have Clang 14.

**Comment by szhorvat** [comment]
I'm not sure if everything's right here. The tests finish in 27 s even though I enabled debug mode and ASan, and the CMake output seems to indicate that they are indeed enabled.

https://dev.azure.com/igraph-team/igraph/_build/results?buildId=3909&view=logs&j=6f6997c9-34f6-54c1-c928-e65e0b5a2c2e&t=eb289072-3844-52ab-e8a9-1e3831c9ccb2

**Comment by GroteGnoom** [comment]
Since it's only running, not building of the tests, 27s should be possible.

**Comment by szhorvat** [comment]
This made me realize that I was not running the tests in parallel on my machine. In debug mode with ASan they took 180 seconds. After `export CTEST_PARALLEL_LEVEL=8`, which I should put in my profile, it's 69 seconds. Still a far cry from 37 s though ...

**Comment by ntamas** [comment]
Speaking of tests (which is completely unrelated from this issue), I was wondering whether we should look into some of the more establised C/C++ unit testing frameworks (like GTest) that would allow us to compile a _single_ test executable and select the tests to run at runtime (instead of compiling one executable per test, which seems like a waste for me, especially if the library is built statically). Do you guys have experience with any of these test frameworks?

**Comment by szhorvat** [comment]
Will it still be possible to run tests in parallel, using not a single process (which is risky) but multiple processes?

Will it be less convenient to work on a single test? Does this require putting all tests within a single source file? That would make it harder to work with tests and debug problems.

If neither of these two things are a problem then I'm all for it. But I have no experience with these frameworks.

**Comment by szhorvat** [comment]
I should say that the only inconvenience I see from having many test executables is that `make check` will recompile _everything_ every time. This sacrifice was made in order to support `make test`, which I still don't consider a good idea. `make check` is a very common way to invoke tests, including for CMake projects. Distro maintainers should read the docs and deal with it, just as they are already dealing with it when it comes to other packages.

**Comment by ntamas** [comment]
Moving this discussion to Slack.
