### ISSUE TITLE
walktrap should be able to compute membership without modularity or merges

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2133]
When passing `NULL` to `modularity` and `merges` in `community_walktrap()`, but requesting the `membership`, it errors with:

Error at src/community/walktrap/walktrap.cpp:165 : Cannot calculate membership without modularity or merges - Invalid value.

https://github.com/igraph/igraph/blob/develop/src/community/walktrap/walktrap.cpp#L163

This restrictions should be relaxed because the most common use case is probably to request only membership (i.e. which are the communities?)

**Comment by ntamas** [comment]
...although then it would hide the fact that the walktrap method is primarily a _hierarchical_ method, i.e. it provides a dendrogram as its primary output, and provides no guidance on where to cut the dendrogram to obtain a "flat" community structure. I think we do that based on maximum modularity, but that's why you need the dendrogram in the first place.

(Of course the code could be refactored to use an internally allocated merge matrix if the user did not provide one, so I'm not talking about technical difficulties here).

**Comment by szhorvat** [comment]
The current behaviour is an inconvenience that just forced me to set up a vector and a matrix _just for this one method_, see d4424be8560a405bd1e5193b2a3717ae3febb9c0  There is no reason not to handle this more nicely.
