### ISSUE TITLE
Add vcpkg installation instructions

### ISSUE THREAD

**Issue by JonLiu1993** [igraph/igraph#2172]
igraph is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for igraph and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build igraph, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/igraph/portfile.cmake). We try to keep the library maintained as close as possible to the original library. :)

We don't have permission to submit pr to your repository, can you agree with us to submit this pr?

README.md
````
[![Build Status on Azure Pipelines](https://dev.azure.com/igraph-team/igraph/_apis/build/status/igraph.igraph?branchName=master)](https://dev.azure.com/igraph-team/igraph/_build/latest?definitionId=1&branchName=master)
![Build Status on Github Actions](https://github.com/igraph/igraph/workflows/MINGW/badge.svg?branch=master)
[![codecov](https://codecov.io/gh/igraph/igraph/branch/master/graph/badge.svg?token=xGFabHJE2I)](https://codecov.io/gh/igraph/igraph)
[![DOI](https://zenodo.org/badge/8546198.svg)](https://zenodo.org/badge/latestdoi/8546198)

The igraph library
------------------

igraph is a C library for creating, manipulating and analysing graphs.
It is intended to be as powerful (i.e. fast) as possible to enable
working with large graphs.

See https://igraph.org for installation instructions
and documentation.

igraph can also be used from:

 - R — https://github.com/igraph/rigraph
 - Python — https://github.com/igraph/python-igraph
 - Mathematica — https://github.com/szhorvat/IGraphM

igraph is a collaborative work of many people from all around the world —
see the [list of contributors here](./CONTRIBUTORS.md). If you would like
to contribute yourself, [click here to see how you can
help](./CONTRIBUTING.md).

Building igraph - Using vcpkg

You can download and install igraph using the [vcpkg](https://github.com/Microsoft/vcpkg) dependency manager:

    git clone https://github.com/Microsoft/vcpkg.git
    cd vcpkg
    ./bootstrap-vcpkg.sh
    ./vcpkg integrate install
    ./vcpkg install igraph

The igraph port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.

````

**Comment by szhorvat** [comment]
Hello @JonLiu1993,

We already recommend vcpkg as an easy way to install igraph on Windows, and the installation command is mentioned on the main website: https://igraph.org/c/#startc Would putting a direct link to https://vcpkg.io/ suit you? That would direct users to the commands to set up vcpkg itself.

In the main documentation, vcpkg is also suggested as the simplest way to install dependencies when compiling igraph from sources: https://igraph.org/c/html/latest/igraph-Installation.html#igraph-Installation-microsoft-visual-studio I am thinking that for the next release we can also add a section pointing out that igraph is already present in many package managers, including vcpkg.  I do make sure that the vcpkg version is updated right away after each new release.

In fact, we are preparing to release version 0.10 soon, which will be a major release. I opened [a test PR for vcpkg](https://github.com/microsoft/vcpkg/pull/26432) to check if we need to make any changes before the final release. Unfortunately, there are some issues on the UWP platform, and I do not have access to a Windows 10/11 machine to test with UWP locally. The problem is that CMake's `try_run()` does not seem to work with UWP, as executables cannot be run directly. There are several possible solutions here, but I have not yet received a clear answer on which one I should go with. Could you please look at the discussion within that PR if you have time?

**Comment by JonLiu1993** [comment]
@szhorvat ,Thanks for your prompt reply, Adding link https://vcpkg.io/ to main site: https://igraph.org/c/#startc is good, 
About your test PR, I will take a look, if you need to test on the UWP platform, I can help you

**Comment by szhorvat** [comment]
This is now done. The change will go online once our team member who deals with the website returns from holidays.

https://github.com/igraph/igraph.org/commit/bf005275a0617498f040c2cd1a35f75a6fc4c730
67f4f15143992e6736a3ee317dfc773460a08caf
