### ISSUE TITLE
IGRAPH_CHECK and RNG_END

### ISSUE THREAD

**Issue by iosonofabio** [igraph/igraph#2179]
**Describe the bug**
I'm not sure if this is a "sleeper" bug because `RNG_END` defaults to "do nothing" ATM (except on R??).

In any case, when `IGRAPH_CHECK(myfunction())` fails between `RNG_BEGIN` and `RNG_END`, the RNG is probably messed up?

**To reproduce**
I'm wondering in this situation:

https://github.com/iosonofabio/treasuremap/blob/e68e60966800daf8b760dd8754692302348de373/src/_treasuremap/treasuremap_layout.c#L602

I used to have an `IGRAPH_CHECK` there (we have one in the `igraph`-shipped version of the file) but now I'm not sure that's alright...

What do you guys think?

Might emerge when #2158 is implemented.

**Comment by szhorvat** [comment]
This has been discussed before, and it would be good to have a way to get rid of RNG_BEGIN/END entirely. These are needed because of the R interface, which requires calling GetRNGState()/PutRNGState(): https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Random-numbers

It is not entirely clear to me why this is necessary. If I understand correctly, it's for synchronizing the `.Random.seed` R variable with the RNG state stored _separately_ on the C side. This would mean that omitting the PutRNGState() on error/interruption would effectively fail to propagate the state. It will appear as if no random functions had been called. That behaviour might be acceptable when the computation was interrupted or errored out anyway.

That said, RNG_BEGIN/END are only necessary when calling random number generation functions, typically invoked with RNG_ macros. In many parts of the code, the use of these macros is very localized, and surrounded directly by RNG_BEGIN/END. There is often nothing inbetween that can fail (no IGRAPH_CHECK). You could use the same approach in the code you linked. This solution of course means more calls to RNG_BEGIN/END and I thin we never benchmarked how bad that is in practice. 

In the end, my advice would be:

 - Don't worry about this right now and don't try to catch errors and manually call RNG_END. We'll deal with all these cases when we get there.
 - Make the RNG_BEGIN/END pairs reasonably localized, meaning: maybe don't put them in an inner loop, but also don't put them right at the start/end of a top-level function unless truly necessary.

**Comment by szhorvat** [comment]
For #2158 this is not a problem. It's been proposed before that RNG_BEGIN/END should not be public at all and I think we should not include them in any examples. Instead, examples should seed the RNG explicitly before first use.

**Comment by iosonofabio** [comment]
Thanks, closing then. Feel free to reopen if you want to keep this on your radar.

**Comment by ntamas** [comment]
Long-term plans for the RNG handling, just for the sake of documentation:

* `functions.yaml` should indicate which functions rely on random numbers
* Interface generators for higher-level interfaces should automatically add the _language-specific_ RNG preparation  and release code in the generated interface instead of relying on the C core to provide injection places with `RNG_BEGIN()` and `RNG_END()`.

This would solve the problem because releasing the RNG properly would be put into the hands of the higher-level interface where it can be dealt with whatever mechanism the higher-level interface provides.
