### ISSUE TITLE
Setting context for interruption handler

### ISSUE THREAD

**Issue by ntamas** [igraph/igraph#2180]
igraph needs an `igraph_set_interruption_handler_context()` function or something similar that allows higher-level interfaces to specify a `void*` pointer that gets passed on to the interruption handler in case the handler needs access to stuff from the higher-level interface. Right now the interruption handler has a thunk argument at the end, but igraph always passes `NULL` there.

**Comment by szhorvat** [comment]
Let me try to articulate why I think that this is unnecessary, and instead the interruption handler should take no arguments at all.

First, note that there is no difference between the case of the interrupt and error handlers. If the interrupt handlers needs the extra argument, so does the error handler.

The reasoning you have for this was that "all callbacks" should take an "extra data" pointer so that they can have access to context-dependent information. But the interruption and error handlers are not the same kind of callback as used by functions like `igraph_cliques_callback()`. These two cases should be distinguished, and treated differently.

Why do we need the extra data argument with e.g. `igraph_cliques_callback()`? In short, so that the callback can operate on data which is _local_ to a function. This makes it easy to ensure reentrancy. The typical example is writing a function that collects all cliques into some data structure. That data structure can be a local variable instead of a global one thank to the "extra data" argument. Notice that the `callback` argument is also local to the `igraph_cliques_callback()` function and it is common to call this function with different callback functions within the same program.

Interruption handlers and error handlers are different because they are inherently global. They are stored in a global variable, and are typically set for the lifetime of the program. If we were to implement a mechanism to change the "extra data" that is passed to these function, it would also be stored in a global variable. There is no local context here, there is no need for reentrancy. The extra data won't be a local variable in some function, as reasonable use cases won't require different ways to check for interruption or different ways to report errors when executing different functions.

If some unusual use case required this anyway, it's very easy to do it: the user can provide their own global variable which is accessed by their interrupt or error handler. igraph doing this by default won't be a great convenience at all. 

But note that so far we have not needed this, nor can I think up any _reasoable_ use case where the need would arise. This contrasts with _local_ callbacks such as the ones in `cliques_callback()` where the need is very common, and the workaround would be much more cumbersome.

**Comment by szhorvat** [comment]
For these reasons, I vote for removing the currently non-functional extra argument from the interrupt handler. This keeps the interface simple and easy to understand, and does not actually prevent any unanticipated use case.

**Comment by iosonofabio** [comment]
TBH, that sounds reasonable @szhorvat - +1

**Comment by ntamas** [comment]
I've returned to this issue and started removing the `void*` argument, then I noticed that even though the interruption handler is supposed to return an `igraph_error_t`, we always translate this error code unconditionally to an `IGRAPH_INTERRUPTED` in the `IGRAPH_ALLOW_INTERRUPTION()` macro. Do we want to keep on doing that? After all, it's not too stressing for maintainers of high-level interfaces to return `IGRAPH_INTERRUPTED` if they really want interruption without raising an error -- on the other hand, why would anyone want to raise an error code from the interruption handler?

**Comment by szhorvat** [comment]
I vote for changing the interface so that the interruption handler returns a boolean instead of an error code.

----

I thought about this a bit and currently I cannot see a situation whether it makes sense for the interruption handler to return an error code (i.e. anything else than `IGRAPH_SUCCESS` or `IGRAPH_INTERRUPTED`).

The interruption handler serves two purposes:

 1. Check for interruption
 2. [Yield](https://en.wikipedia.org/wiki/Yield_(multithreading)) control to ensure that the application stays responsive, i.e. use cooperative style multitasking. Typically, this ensures that single threaded GUI applications stay responsive. For example, the Windows R GUI locks up during times when the interruption handler is not called.

An error can theoretically occur within the interruption handler in cases like point 2, but these are not an igraph error, and it seems to me that they shouldn't be signalled with the same mechanism as igraph errors. If it is necessary to signal or handle such errors, it's probably better done with a global variable which holds information specific to the given system. An `IGRAPH_FAILURE` won't really help.

**Comment by ntamas** [comment]
The interruption handler now returns `igraph_bool_t`; see 60bf995a5
