### ISSUE TITLE
Update "my first function" tutorial for 0.10

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2182]
The tutorial on first contributions should be updated with the API changes that 0.10 brought. The code there no longer compiled with 0.10. https://github.com/igraph/igraph/wiki/Contributing-your-first-function-to-igraph

@iosonofabio would you have time for this?

It should be simple, but it requires some attention (and ideally: testing the code):

  -`long int` -> `igraph_integer_t`
 - return code is `igraph_error_t`, not `int`
 - `test_utilities.h` instead of `.inc`
 - ... ?

**Comment by ntamas** [comment]
I'll do this tomorrow before the 0.10.0 release.

**Comment by szhorvat** [comment]
This doesn't really need to block the 0.10 release.

**Comment by ntamas** [comment]
I've fleshed out a few things; in particular:

* `git` command examples were fixed to use `upstream` for the name of the remote that refers to our repository instead of `igraph` as this is a common convention (`origin` for the Github repo that the local copy was checked out from, and `upstream` for the repo that the Github repo was forked off from)
* Functions now return an `igraph_error_t` instead of an `int`
* `igraph_vector_long_t` was replaced with `igraph_vector_int_t`
* `long int` variables were replaced with `igraph_integer_t`
* A short explanation for `IGRAPH_PRId` was added

I think that's all that had to be done to make things work nicely with 0.10; if you find anything else, let me know or feel free to fix it. I think that the current state is good to go for 0.10.0.

**Comment by szhorvat** [comment]
I made a few more fixes, closing.
