### ISSUE TITLE
igraph_read_graph_graphdb can use more error checks

### ISSUE THREAD

**Issue by GroteGnoom** [igraph/igraph#2191]
graphdb reader does not check if [ferror()](https://en.cppreference.com/w/c/io/ferror) gets set on the stream. 
It also doesn't check if it has read the whole file. 
(It does check if the file unexpectedly stopped.)

Not reading the whole file can happen if it's corrupted and the first two bytes don't indicate the length correctly.

It would be nice to also add a few corrupted file tests.

**Version information**
current master, 96af37bec109bf426c6f09ba7dc1447c6becb02c

**Comment by szhorvat** [comment]
Yes, this is one of the two readers not being tested on OSS-fuzz, so they're not in great shape. The other is the DIMACS reader, which would need a complete rewrite anyway.

The graphdb format is used only by a single graph database which is not even online anymore, so we probably shouldn't put too much effort into this. As I remember, this database is used for testing isomoprhiosm functions

**Comment by szhorvat** [comment]
> graphdb reader does not check if [ferror()](https://en.cppreference.com/w/c/io/ferror) gets set on the stream.

I believe this is not necessary. The reading function returns -1 on failure. Failure is either caused by error (`ferror`) or end-of-file (`feof`). There is a check for end-of-file condition. If that returns `false`, it shows that `ferror` would return true.

> It also doesn't check if it has read the whole file.

I added a check for this. I looked at the format documentation again, and found nothing that indicates that extra bytes should be tolerated. Thus I made it an error, not a warning.

Additionally, there was one missing error check in the `getword()` function.

> It would be nice to also add a few corrupted file tests.

I won't do this now, but I'll add a fuzzer.
