### ISSUE TITLE
What is the purpose of igraph_edge()?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2204]
Currently, `igraph_edge()` is just a wrapper over `IGRAPH_TO` and `IGRAPH_FROM`. There is no advantage to using it, yet it will decrease performance when used in an inner loop (due to the function call overhead). I notice that it keeps popping up in new code as well, where IMO it shouldn't be used at all, as it decreases performance.

We should decide what to do with this function, and whether it should be deprecated and eventually removed.

The documentation makes the impression that this function is the error checked version of `IGRAPH_TO` and `IGRAPH_FROM`, however, it does not do actually any error checking at all. The only error that can occur is an out-of-range edge ID. Checking for this error only makes sense if the edge ID is coming from a source that the C programmer has no control over, in other words: when `igraph_edges()` is exposed to high-level interfaces. Is it exposed anywhere, and if yes, though which function?

TODO list:

 - Decide whether to keep or deprecate it. IMO the only good reason to keep it is if it's exposed in high-level interfaces.
 - If it is kept because it is accessible from high-level interfaces, then it should do error checking on `eid`.

**Comment by ntamas** [comment]
Let's make it error-checked and then it has a clear benefit over `IGRAPH_FROM` and `IGRAPH_TO`. I never liked these two macros anyway because they expose the internals of `igraph_t` in a public header, which basically prevents us from switching the internal representation of the graph to something else without breaking the API.

In the long term I'd rather converge in a direction that users would not be allowed to use "naked" `igraph_t` variables (they would be forced to allocate an `igraph_t` on the heap), which would then open up the possibility to replace or adjust the internal graph representation transparently, without breaking API. We could still use `IGRAPH_FROM` and `IGRAPH_TO` internally in their unchecked form, but they would be private; users of the library would have to go through `igraph_edge()`. But this is really for the long term, I have no intention to do this any time soon, and maybe we'll never do this, but I see no reason to remove `igraph_edge()`.

**Comment by ntamas** [comment]
Historical context: now that I was reading the other issue (#2205) about `igraph_edges()`, I recall that `igraph_edge()` was there first, and `IGRAPH_FROM()` and `IGRAPH_TO()` were added only later when we got tired with declaring temporary variables for the `from` and `to` endpoints so that we can pass their addresses to `igraph_edge()`.

**Comment by szhorvat** [comment]
I understand the benefits of making the interface opaque, but there are downsides as well. These macros are typically used in tight inner loops, and there's a very real risk of a noticeable performance impact from changing them to functions.

We have (informally) discussed before how C is effectively slower than C++ because in C you typically pay for abstraction with performance. The advantage of C++ is that it avoids that. The way it achieves this in practice is by using a lot of inline functions which live in headers. These are in many ways similar to macros and do not allow making the interface completely opaque. This illustrates the tradeoff between a very stable API and performance.

igraph has performance as a stated goal, yet it is probably slower than the compiled alternatives. Of course benchmarking would be needed to be sure, but _from personal experience_, igraph is slower than Boost Graph (templated C++), LEMON (templated C++) and petgraph (Rust).

We should be at least careful here, and probably develop a usable benchmarking infrastructure. We can't currently tell how big a performance impact the various refactorings have. Based on my experience with C programming, much hunch is that moving `IGRAPH_TO`/`IGRAPH_FROM` to functions could have a significant effect, but the "betweeness" benchmarks done by @GroteGnoom  have shown that the picture is more complicated that I expected, and non-locality in the core graph datastructure may play the most significant role. Once again, this shows the need for a better benchmark setup before making big changes.

**Comment by szhorvat** [comment]
Error checking added 535a3bc2445f46ba119106d602ec9e6c0d81ba3b

**Comment by ntamas** [comment]
Error checking was added above and I'm not keen on removing the function just "because" there might be other, more performant options (because the overhead of calling from a higher-level interface is probably more significant anyway so calling `IGRAPH_FROM()` instead of `igraph_edge()` would probably provide no measurable benefit - especially if you need both endpoints at once). So I'm closing the issue for the time being.
