### ISSUE TITLE
arpack should provide a way to be deterministic

### ISSUE THREAD

**Issue by flying-sheep** [igraph/igraph#2207]
In order to get a deterministic result, one either has to set a seed in FORTRAN or provide a starting vector (v0). I assume that would be the `start` parameter. Currently `start` is not implemented though:

https://github.com/igraph/rigraph/blob/5e7a689afde1864c2f36b2a7825db24f2f89b22b/R/centrality.R#L117-L119

I also have no idea how to set a seed in FORTRAN…

There’s some discussion in scipy/scipy#9023

**Comment by szhorvat** [comment]
This is really a C core issue, not an R/igraph issue.

The non-determinism is present in places where `options->start` is set to `0` when calling `igraph_arpack_r(s|n)solve()`, indicating that ARPACK should generate its own random starting vector. That random vector does not use igraph's own RNG.

Here are the affected igraph functions, based on grepping for `options->start`:

 - `igraph_community_leading_eigenvector()` 
 - `igraph_adjacency_spectral_embedding()`
 - `igraph_laplacian_spectral_embedding()`

A simple fix would be to generate our own random starting vectors and pass them to ARPACK.

**Comment by ntamas** [comment]
Note to self: ARPACK generates random vectors in `dgetv0`, using LAPACK's `dlarnv`, and it requests a uniform distribution in the [-1, 1] range.

**Comment by szhorvat** [comment]
I thought I made that note here, but I may have forgotten to post it, and it got lost. What I don't fully understand is how `dgetv0` "forces it into the range of OP", and what magnitude random vector we should be passing manually. We should probably choose it based on the specifics of the problem at hand, e.g. for eigenvector centrality we start with a slightly randomized degree vector.

**Comment by vtraag** [comment]
> I don't fully understand why `igraph_community_leading_eigenvector()` calls ARPACK twice though.

I believe we discuss this also in https://github.com/igraph/igraph/issues/1929.

**Comment by ntamas** [comment]
I took care of the RNG setup in the spectral embedding routines; this leaves us to deal only with `igraph_community_leading_eigenvector()`, where we have this problem with the double invocation of ARPACK. I think I was the one who added that a long time ago when trying to ensure that the function gives at least _some_ result for all the graphs in the Graph Atlas. I wanted the change to be as surgical as possible, so the idea was that we try to calculate the eigenvectors with a random starting vector first, which should work in most cases except the pathological or highly symmetric cases, in which case we use another vector.

Note that the leading eigenvector problem is formulated in a way that the values in the eigenvector will be positive for one side of the split and negative for the other side. (I think there might also be something about the magnitudes of these values, i.e. in a perfect split, you would mostly see +1 and -1). ARPACK works the best if you can "guess" an initial start vector that is as parallel to the eigenvector that you are looking for as possible. However, if we had such a guess, then we would already have a pretty good guess at the community structure as well, so this is a chicken-and-egg problem. That's why I simply start from a deterministic even split of vertices to one or other side of the cluster (that's why we have -1 and +1 in the start vector), and it seems to work in cases when ARPACK fails to converge from a completely random start vector.

One way to go ahead would be to get rid of the double ARPACK calls and just start from a random +1 / -1 vector in all cases. It does not make sense to start from the degrees because the eigenvector that we want to converge to is not related to the degrees (unlike in the case of eigenvector centrality, where we assume that degrees and centralities are somewhat correlated).

**Comment by ntamas** [comment]
I don't have more time to investigate the CI failures now, but I'll return to this eventually.

**Comment by ntamas** [comment]
Investigated the failures a bit more, and it seems like using a _random_ start vector (even something that is deliberately biased towards -1 and +1, like `pow(RNG_UNIF(-1, 1), 3)`) sometimes yields convergence problems with the vendored ARPACK, especially on 64-bit machines. I could not find the reason for this, but switching to a completely deterministic starting vector (effectively `pow(-1, i)` for `i = 0..n-1`) gets rid of the problem in all environments I tried. Any suggestions?

**Comment by ntamas** [comment]
Also, using a start vector that is essentially something like `(RNG_UNIF(-1, 1) < 0 ? -1 : 1) + RNG_UNIF(-1e-4, 1e-4)` seems to work, but not without the random noise added to the end of it. I guess that the problem is that for small graphs, the chance of getting a degenerate starting vector (like all 1s) is a real possibility and ARPACK will fail there.

**Comment by szhorvat** [comment]
Stupid idea: shuffle a vector containing equal numbers of -1 and 1.

**Comment by ntamas** [comment]
Okay, I think this is now done; I've searched for all the places where we could have potentially relied on ARPACK / LAPACK to generate a random starting vector and replaced those with igraph's own routines. Feel free to reopen the issue if you find any remaining places where we still rely on ARPACK's start vectors.
