### ISSUE TITLE
Weighted clique results are sometimes wrong when using identical weights

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2306]
**Describe the bug**

Weighted clique results are sometimes wrong when using identical weights.

**To reproduce**

I added tests that demonstrate this in b99ef43eefcec7a37fc2fac31e80a28fa6bd935b

**Version information**

Tested in 0.10.4.

Bug is not present in 0.9, this is a regression in 0.10.

**Comment by szhorvat** [comment]
@ntamas Would you have time to take a look at this?

**Comment by ntamas** [comment]
I think we aren't doing much in our Cliquer wrapper apart from converting the vertex weight vector to Cliquer's format, right? So if it's a bug, it's either a bug in the stock Cliquer, or something went wrong during the integration of Cliquer's source into igraph.

**Comment by szhorvat** [comment]
The issue is not present in 0.9, only in 0.10. I tested this using IGraph/M.

**Comment by ntamas** [comment]
Inside `clique_max_weight()`, `clique_find_single()` returns `NULL` for `&s` when invoked with the P_2 graph with (5, 5) as the weights. I need to dig further into `clique_find_single()` to see what's happening there.

**Comment by ntamas** [comment]
Okay, so, the allocation / deallocation structure of Cliquer is weird and I don't really understand the purpose of the `ENTRANCE_SAVE()` and `ENTRANCE_RESTORE()` calls, but here's what I've found:

* `clique_max_weight()` first calls `clique_find_single()`
* `clique_find_single()` eventually calls `clique_unweighted_find_single()` when it realizes that all the weights are the same
* `clique_unweighted_find_single()` correctly finds the largest clique in `current_clique`, but then, upon exit, it calls `ENTRANCE_RESTORE()`, which restores `current_clique` to an empty set, and that's why we are seeing that outside.
