### ISSUE TITLE
CMake package is not relocatable

### ISSUE THREAD

**Issue by vtraag** [igraph/igraph#2339]
**Describe the bug**
The CMake package is not relocatable. That is, in `igraph-targets.cmake` it contains hardcoded paths to `libm.so`, `libopenblas.so` and `libgmp.so`. This prevents it from being build on one system and then being relocated to another location. 

I noticed this is also the case in the Debian packages (ping @jgmbenoit). Perhaps this is not a problem there, since the hardcoded paths from the build system may be identical to the paths on the users' system. However, if the build system ever changes, this will lead to problems with other packages linking to `igraph` using the CMake build system.

**To reproduce**
Follow the usual installation routine `cmake --build . --target install`. Then check the `igraph-targets.cmake` file in `lib/cmake/igraph` under the `CMAKE_INSTALL_PREFIX` path to see the hardcoded paths.

**Version information**
Latest `master` branch (d789a7eb70a197840606f29eaa5211c37f05d836).

**Additional information**

See https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#creating-relocatable-packages for making relocatable packages. I already briefly looked into it, but I haven't yet found a solution, that's why I'm just opening the issue now.

The problem surfaced in https://github.com/conda-forge/staged-recipes/pull/22615, where I try to build the library version of my `leidenalg` package (see https://github.com/vtraag/libleidenalg) against `igraph`. However, in that case, `igraph` is originally built in a separate docker container, which uses different paths than where the binary is actually being installed in.

On a slightly separate, yet related, note: why are all the dependencies with `target_link_libraries` marked as `PUBLIC`? According to [the documentation](https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#target-usage-requirements), we should only mark it as `PUBLIC` whenever the dependencies are also used in header files, which is not the case, I believe? In that case, I believe we can mark them all as `PRIVATE`. This doesn't change the hardcoding of the paths, but it does prevent the libraries from being necessary transitive dependencies for direct dependencies of `igraph` I believe. For instance, it is not necessary for `libleidenalg` to link to `libopenblas`, since it already links to `libigraph`, which then links to `libopenblas`.

**Comment by ntamas** [comment]
Okay, so it seems like part of the solution to this problem would be to declare libraries to link to in `src/CMakeLists.txt` like this:

```
if(BLAS_FOUND)
    target_link_libraries(igraph PUBLIC BLAS::BLAS)
endif()
```

This is because `FindBLAS.cmake` exports a target named `BLAS::BLAS` that can be imported by libraries that wish to use BLAS. I believe that most other `Find*.cmake` modules export similar targets, although there might be a few that don't, and we need to figure out what to do with those.

However, herein lies the first problem: `BLAS::BLAS` is declared only since CMake 3.18. In one of the previous dev meetings we agreed to try to stick to CMake 3.16 (except for the unit tests) to facilitate the compilation of igraph in R for older versions of Linux that do not ship with CMake 3.16 yet (cc @krlmlr). If we start to use `BLAS::BLAS`, this means that we need to commit ourselves to CMake 3.18 fully. If we do not, we will need to find other ways around the relocatability issue, and this is the point where it gets costly to ensure compatibility with ancient Linux distributions.

**Comment by szhorvat** [comment]
Some thoughts to help with the decision:

 - If we continue supporting certain old CMake versions, we should be clear about why we do this, and when we are willing to bump the requirements. Let's try to avoid perpetually sticking to the oldest possible version, and instead weigh the pros and cons of moving ahead, or perhaps even come up with clear guidelines (e.g. "support last two Ubuntu LTS" or similar).
 - A while ago I wrote a short summary in chat about CMake versions in various Linux distros of relevance. It is my impression that the problem distro here is Ubuntu 20.04 LTS, which includes only CMake 3.16. However, Ubuntu 20.04 users can install newer CMake versions relatively easily. They can either use `snap` (as we did in our CI), or they can use https://apt.kitware.com/
 
     Other popular distros tend to be either fast-moving (such as Arch-based ones), or so extremely conservative that supporting their out-of-box package versions is not reasonable (RHEL/CentOS). The conservative ones are typically used on HPC clusters, where the users can ask the sysadmin to deal with the problem.

**Comment by vtraag** [comment]
> I think this is the case only if igraph is compiled dynamically. If igraph is compiled statically, dependents have no way of telling that igraph itself requires libopenblas and you'll get linker errors - unless you compile libopenblas _into_ igraph itself. But I'm not 100% sure.

Correct. However, because the dependencies are now declared `PUBLIC` in `target_link_libraries `, when using `find_package` using Cmake in any package that wants to link to `igraph`, it now instructs that package to also try to link directly to that package. It should not do this. I've tried this out, and indeed, the problem with a dynamic library disappears when the dependencies are indicated as `PRIVATE` instead of `PUBLIC`. To me, this is the most pertinent problem at the moment.

I'm not exactly sure how this works out for a static build, and there might still be problems with absolute paths.

**Comment by ntamas** [comment]
So, switching all instances of `target_link_libraries(... PUBLIC ...)` to `PRIVATE` seems to work, _but_:

* If I leave the `install(...)` command as is, like `install(TARGETS igraph bliss cliquer cxsparse_vendored pcg prpack...`, then all these additional targets (which are in fact sub-libraries of igraph) get exported in `igraph-install.cmake` and we end up with one hardcoded path there (the one for GMP).
* If I only write `install(TARGETS igraph...`, without all the sub-libraries, then CMake complains during a static build:

```
CMake Error: install(EXPORT "igraph_targets" ...) includes target "igraph" which requires target "bliss" that is not in any export set.
```

(and similarly for all the other sub-libraries).

Note that we cannot make the `install(...)` command conditional on whether we are building a static or a shared library, because in Linux distributions the distro maintainer wants to prepare both the static and the shared library. Right now the solution is to compile igraph twice, once for the static config and once for the shared, but the generated `igraph-install.cmake` file is identical for both. If we branch based on whether we are building static or shared libs, then the generated `igraph-install.cmake` file will be valid for one configuration only but not the other.

**Comment by ntamas** [comment]
Made some progress, see above. With this construct, `igraph-targets.cmake` contains an absolute path for GMP only (and I don't understand why) when igraph is built as a shared library. When igraph is built as a static library, there are still absolute paths for all dependencies in `igraph-targets.cmake`, but I guess we can't really do anything about that as you need to link to dependencies explicitly when `igraph` is built as a static lib.

I still need to investigate the GMP issue.

**Comment by ntamas** [comment]
It seems like since `igraph::bliss` is a CMake object library only, we do not need to link to GMP explicitly there, it is enough to do it in the top-level `igraph` target (see 521420e). This seems to work now.

**Comment by szhorvat** [comment]
Plus make s note in the changelog
