### ISSUE TITLE
test::igraph_community_voronoi  fails on Fedora on aarch64, s390x

### ISSUE THREAD

**Issue by limburgher** [igraph/igraph#2366]
**Describe the bug**
426/545 Test #426: test::igraph_community_voronoi .....................Subprocess aborted***Exception:   0.29 sec
Error at src/community/voronoi.c:397 : Optimizer did not converge while maximizing modularity for Voronoi communities. - Numeric procedure did not converge.

**To reproduce**
Build with tests enabled

**Version information**
0.10.5 release tarball.

I'm the Fedora pacakge maintainer; we're keeping igraph at 0.10.4 until this works.

**Comment by szhorvat** [comment]
Can you please link to the build logs and test output, so we can find out what is different in your configuration?

**Comment by limburgher** [comment]
Fedora 39: https://koji.fedoraproject.org/koji/buildinfo?buildID=2224427
Fedora 38: https://koji.fedoraproject.org/koji/buildinfo?buildID=2224428

**Comment by szhorvat** [comment]
I was a bit confused navigating the page. For reference, here's a direct link to the output from one of the s390x builds:

https://kojipkgs.fedoraproject.org/work/tasks/9888/102779888/build.log

Some of the differences from our s390x CI test:

 - Compiler is GCC 13.1.1.
 - LTO is enabled.
 - There's an `-mtune` option used.

The problem is likely the numerical stability of the algorithm. I'll look into this.

@limburgher If you have direct access to a machine with one of the affected architectures, it would be very useful if you could build the package with passing the `-DUSE_SANITIZER=Address` option, and send me the test output. It will show a stack trace, so I'll be able to tell which precise part of the test is failing. Unfortunately I have no direct access to aarch64 or s390x (my IBM trial access has expired). In the meantime I'll try to make the algorithm more robust.

I do not recommend skipping 0.10.5 for this reason, as Fedora users will miss out on multiple bugfixes and improvements. The affected function is a new addition and marked as experimental.

**Comment by limburgher** [comment]
Attached, from aarch64
[build.log](https://github.com/igraph/igraph/files/11919873/build.log)

**Comment by szhorvat** [comment]
Thanks you @limburgher. I see that there are some additional ASan warnings as well, which did not come up in our CI tests. I will take a look at these.

In the meantime, I made some progress on this, and I believe that the following patch resolves the issue:

https://github.com/igraph/igraph/commit/23dd3ee5fc3c56ed4e0bd5339e4bde07d7dcd831

I also managed to reproduce it on Travis. The relevant difference was building with or without optimizations (i.e. no optimization vs `-O2`). The above patch seems to eliminate the problem.

**Comment by limburgher** [comment]
It works for me as well, thank you very much!

**Comment by szhorvat** [comment]
Thanks for maintaining igraph in Fedora!

----

I'm not sure what's going on with the other test failures from the build log you posted. These are not actually ASan errors, but an exception being thrown _only when ASan is enabled_. That is unusual. The exception is coming from here:

https://github.com/gcc-mirror/gcc/blob/master/libstdc++-v3/include/bits/basic_string.tcc#L139

It appears that it is triggered when the capacity of a string is larger than its maximum possible size. Perhaps ASan somehow reduces the max size, but even so this is strange.

I was unable to reproduce it on x86_64 with GCC 13.1.0. I looked through the string creation parts of the HRG code, but nothing jumped out at me. It's not happening on Travis on aarch64, either with or without optimizations. It's not clear whether there is a real issue here or not. For now I'll close this.
