### ISSUE TITLE
Is there any point to the `scale` parameter of `eigenvector_centrality()`?

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2446]
The function `igraph_eigenvector_centrality()` has a `scale` parameter. 

 - When `scale==true`, values are scaled so that the one largest in magnitude is 1.0.
 - When `scale==false`, we give no promises about the scaling.

This issue is to discuss whether there any point to having the `scale` parameter. Eigenvectors are unique only up to a multiplicative constant. Eigenvector centrality values are not meaningful in isolation. The eigenvector centrality of a vertex is interpretable only relative to the eigenvector centrality of another vertex within the same graph.

Unfortunately, many users do not seem to realize this. There are regular support question on StackOverflow and the forum, most recently [here](https://igraph.discourse.group/t/the-result-is-different-neo4j-for-eigenvector-centrality/1715?u=szhorvat).

Would it make sense to _always_ scale values, and just remove this parameter? Will this reduce confusion? What is the point of ever explicitly choosing `scale=false`?

**Comment by ntamas** [comment]
I think that the primary role of scaling is not to reduce confusion (people will always try to interpret eigenvector centralities in absolute terms no matter how you scale them) but to bring the values to a manageable range so they are easier to parse with the naked eye. Otherwise the parameter really doesn't have any well-defined role. I'd remove it if it weren't for the API breakage.

Also note that we need to be more conservative with parameter removals if the R interface starts relying more on auto-generated code. Removing the argument entirely would stop old code from working in R so the sooner we make these removals the better it is.

**Comment by ntamas** [comment]
Feel free to go ahead.

**Comment by szhorvat** [comment]
The scale parameter was removed.
