### ISSUE TITLE
Non-Zero Result for Directly Connected Nodes with a Self-Loop in `similarity_inverse_log_weighted` Function

### ISSUE THREAD

**Issue by iany0** [igraph/igraph#2448]
Hello,\
**Describe the bug**  
`similarity_inverse_log_weighted` function is unexpectedly returning a non-zero similarity index for two directly connected nodes where one of the nodes has a self-loop. Specifically, in an undirected graph with nodes 0 and 1 directly connected and node 1 having a self-loop, the function returns a similarity index of 1.8204784532536746 instead of the expected 0, given that there are no other common neighbors.

**To Reproduce**
```python
from igraph import Graph

# Create an undirected graph with 5 nodes
g = Graph(n=5, edges=[(0, 1), (1, 1), (2, 3), (3, 4)], directed=False)

similarity_matrix = g.similarity_inverse_log_weighted()

print(similarity_matrix[0][1])
```

**Expected Behavior**\
The expected Adamic–Adar index between nodes 0 and 1 should be 0, as there are no common neighbors other than their direct connection.

**Version Information**
- `python-igraph` version: 0.11.3
- Source of `python-igraph` (e.g., pip, conda, source): pip

**Additional context**\
If two nodes are not directly connected but one has a self-loop, the function returns 0 as expected.
```python
from igraph import Graph

# Create an undirected graph with 5 nodes
g = Graph(n=5, edges=[(1, 1), (2, 3), (3, 4)], directed=False)

similarity_matrix = g.similarity_inverse_log_weighted()

print(similarity_matrix[0][1])
```

**Comment by szhorvat** [comment]
Can you email me the Adamic & Adar paper at szabolcsh at ru.is please? Downloading it is difficult at my current location.

**Comment by ntamas** [comment]
I don't believe this is a bug. The original Adamic-Adar paper is not concerned with the existence of self-loops as far as I know, but a common interpretation of neighborhood is that a node is a neighbor of itself when it has a self-loop. So, the intersection of the neighbor sets of a graph with edge list [(0, 1), (1, 1)] implies that 1 is a common neighbor of 0 and 1. In fact, since 1 is a neighbor of itself _twice_ since it has two edge stems that lead to node 1.

I understand that the treatment of loops is somewhat up to interpretation in this particular case (and in many others, since many of the measures in igraph were not defined rigorously for graphs with loop edges). My argument for the current behaviour is that if you want to ignore loop edges, then you can easily remove them before calling `Graph.similarity_inverse_log_weighted()`, while if we pre-emptively ignore loop edges in the code, then there is no way back.

**Comment by iany0** [comment]
> Can you email me the Adamic & Adar paper at szabolcsh at ru.is please? Downloading it is difficult at my current location.

Apologies for the delayed reply; I have sent the paper to you via email.

**Comment by iany0** [comment]
> I understand that the treatment of loops is somewhat up to interpretation in this particular case (and in many others, since many of the measures in igraph were not defined rigorously for graphs with loop edges). 

I completely concur with your points. However, I suggest enhancing clarity by addressing this matter in the documentation or by introducing an option to include or exclude self-loops in the calculations?

**Comment by ntamas** [comment]
Documentation clarified in the C core. I'll do something similar for the Python interface as well. Thanks for the suggestion!
