### ISSUE TITLE
Test failure on mips64el architecture

### ISSUE THREAD

**Issue by tillea** [igraph/igraph#2450]
**Describe the bug**
When trying to run the build time test of version 0.10.8 on mips64el there are some test failures.  Please see the [full build log](https://buildd.debian.org/status/fetch.php?pkg=igraph&arch=mips64el&ver=0.10.8%2Bds-1&stamp=1701192760&raw=0) and seek for

    Start 246: test::igraph_pseudo_diameter_dijkstra
    ...
    243/551 Test #243: test::igraph_pagerank ..............................***Failed    1.15 sec

In total there are `99% tests passed, 1 tests failed out of 551`

**To reproduce**
Not sure whether this can be reproduced on some emulated mips64el machine.

**Version information**
0.10.8

**Comment by szhorvat** [comment]
This is the same issue that you reported a couple of years ago (and which I can't  look up at the moment due to very bad network connection). Segments of the vector that ARPACK returns are all zeros. We put many hours into this already, and @jgmbenoit reported it to ARPACK-NG, but we could never figure out the reason.

I do not suggest spending any more time on it. I'd consider ARPACK broken on that platform. Whether that's due to ARPACK or a compiler bug, I do not know,.

**Comment by szhorvat** [comment]
Finally: https://github.com/igraph/igraph/issues/1469

**Comment by szhorvat** [comment]
Closing this in favour of #1469. Let us continue the discussion there.
