### ISSUE TITLE
Make randomization in Louvain optional

### ISSUE THREAD

**Issue by danifernandes-hub** [igraph/igraph#2538]
**What is the feature or improvement you would like to see?**

I would like to be able to get the same results for the same graph every time I run the algorithm instead of having it change per run.  I saw that https://github.com/igraph/igraph/pull/1696 added randomization, but for my particular use case having homogeneous results is important (I'm using the algorithm in production and inconsistent results look buggy for my users). It makes more sense to have a parameter to be able to tell if you want the results randomized or not.

**Use cases for the feature**

Consistent results for applications.

**Comment by ntamas** [comment]
Would seeding the RNG with the same seed before each invocation of the Louvain algorithm solve the problem? You can use `igraph_rng_seed(igraph_default_rng(), 1234)` or something like that.

**Comment by szhorvat** [comment]
> and inconsistent results look buggy for my users

I would say that the correct approach is to educate your users about why having an ensemble of (random) results is beneficial.

Remember that this is a heuristic modularity maximization algorithm. It won't usually find the optimum partitioning (i.e. the global maximum). Comparing results from multiple runs allows you to judge whether the result is meaningful at all. Do you get comparable partitioning? That's confidence inspiring. Or not? Then the network probably doesn't have any community structure.

As @ntamas said, if you truly need determinism, for example for testing, you can set a random seed. However, in my opinion, when using such heuristic modularity maximization methods, no community analysis is complete until you have performed multiple runs and checked that the results are consistent. 

I will close this now since I believe adding such a feature will do a disservice to our users by creating a false sense of security about the result of this function.

**Comment by danifernandes-hub** [comment]
> I would say that the correct approach is to educate your users about why having an ensemble of (random) results is beneficial, and why drawing conclusions based on a single one is dangerous.

No need for such aggression/rudeness here, you don't know anything about my use-case to tell me how I should address my users. I'm not running a lab, so that level of complexity is undesired on my end.

> As @ntamas said, if you truly need determinism, for example for testing, you can set a random seed. However, in my opinion, when using such heuristic modularity maximization methods, no community analysis is complete until you have performed multiple runs and checked that the results are consistent. Keep in mind that with this method, the result will always depend on the order in which the vertices are processed. Surely you don't want a deterministic method whose result depends not on the network, but the specific representation of the network on a computer?
> 
> I will close this now since I believe adding such a feature will do a disservice to our users by creating a false sense of security about the result of this function.

All I'm asking for is a parameter to have it be non-random if I want so. It could be the seed so I can set it directly from the class, that makes it clear for any user of the library that the order does matter and can affect the results like it does for many other algorithms (ML has an ample repertoire of this and they deal with it easily enough by adding a random_state parameter or a seed so I don't see why this can't behave similarly, it is not such a special algorithm after all). The documentation could address such a fact easily enough.

**Comment by szhorvat** [comment]
No rudeness intended. I simply explained the reasoning for not adding such a feature, which I strongly believe would be damaging given the large number of inexperienced users we have from empirical fields such as biology or sociology. 

igraph has many stochastic functions. None have a seed parameter. Instead, you can set a seed before running these functions. Furthermore, in all three high-level interfaces there are easy ways to save/restore the the random seed before/after calling functions. If there is a need to do this in C, we can discuss that in a separate feature requests, but there won't be a seed parameter for individual functions.
