### ISSUE TITLE
Switch to bucket sort in `igraph_i_is_bigraphical_simple`

### ISSUE THREAD

**Issue by Tagl** [igraph/igraph#2546]
https://github.com/igraph/igraph/blob/2728866fb7c91552bddbc454e5a568b6842e80f3/src/misc/graphicality.c#L770-L776

Switching the sort here from a comparison based sort to a bucket sort improves the time complexity to $\mathcal{O}(N_1 + N_2)$.
Then all the implemented graphicality checks run in linear time, as far as I can tell.

**Comment by ntamas** [comment]
I think the problem is that we need to cater for cases when the degree distribution is extremely skewed (like, many vertices with degree 1 and one vertex with a high degree). This would need lots of empty buckets, which might be prohibitive in terms of memory usage.

One thing that I was considering for a while now though is to switch from the built-in comparison-based sort of the standard C library to [timsort](https://en.wikipedia.org/wiki/Timsort). Or, sort routines on integer vectors could use the difference between the minimum and maximum of the vector as a proxy to decide whether a bucket sort would be feasible, and fall back to timsort if needed.

**Comment by szhorvat** [comment]
When considering graphs without multi-edges, the max degree is no greater than the vertex count. Thus for a bucket sort we only need an array of the same size as the degree vector (we only really need the degree counts, as vertex indices are irrelevant).  This does double the memory usage compared to an in-place sort, but perhaps that's not so bad.

Some of these graphicality checks can in fact be implemented by working directly with an array containing degree counts. We don't need to keep track of the vertices' identities, just how many vertices are there of degree 1, 2, etc. Reordering the degree sequences doesn't affect their graphicality.  (This is not true for directed graphs where we do need to keep track of which in-degree belongs to which out-degree.)

This is indeed the approach currently used in `igraph_i_is_graphical_undirected_simple()`. It should also work for `igraph_i_is_bigraphical_simple()`.

**Comment by szhorvat** [comment]
#2286 is related: when we do need a plain sort, we can make an improvement by (1) using better algorithms such as timsort or (2) inlining the comparator for special cases such as integer vectors.

**Comment by szhorvat** [comment]
> This does double the memory usage compared to an in-place sort

Actually we aren't even using an in-place sort, we're copying the degree vector (which is `const`) before sorting. So the memory usage won't be affected either.
