### ISSUE TITLE
igraph_get_all_eids_between doesn't work

### ISSUE THREAD

**Issue by mengrj** [igraph/igraph#2609]
**Describe the bug**
How could I get all edges between two vertices? I assume I should use the function `igraph_get_all_eids_between`,  but it seems not to be working. 

I created a directed graph and added two paths: 0->1->2->3 and 0->2->3. Now I would like to get all edges between the vertices 0 and 2. I hope to get edges 0->1, 1->2, and 0->2, but I only got the edge 0->2. 

It would be very helpful if you could let me know if there is a bug or if I used the wrong function. 

**To reproduce**
Here is my code:
```
  igraph_t ipsm;
  igraph_small(&ipsm, 0, IGRAPH_DIRECTED, -1);
  ...
  igraph_vector_int_t eids;
  igraph_vector_int_init(&eids, 0);
  igraph_integer_t from = 1;
  igraph_integer_t to = 3;
  igraph_get_all_eids_between(&ipsm, &eids, from, to, IGRAPH_DIRECTED);
  if (res != IGRAPH_SUCCESS) {
    printf("Error: %d\n", res);
    return 1;
  }
  // print the edge count
  printf("Edge count: %ld\n", igraph_vector_int_size(&eids));
  // print all the edges
  for (int i = 0; i < igraph_vector_int_size(&eids); i++) {
    printf("%ld ", VECTOR(eids)[i]);
  }
  printf("\n");
```

**Version information**
v0.10.12 on Ubuntu 22.04.

**Comment by szhorvat** [comment]
Can you please provide a _complete_ example, ready-to-run code that doesn't need modification on our part?

Please include the actual output and the expected output in the post.

This will be very helpful. After a quick skim I see nothing wrong with your code, but it's incomplete, so I'm not certain what you're doing exactly.

**Comment by szhorvat** [comment]
The example you show is not complete, so I can't run it.

However, your description indicates a misunderstanding.

The edge `0 -> 1` is not between `0` and `2`. It is, by definition, between `0` and `1`.

If you are looking for _paths_ connecting two vertices, use `igraph_get_all_simple_paths()`.

I believe this issue is the result of a misunderstanding, so I'm closing it, but feel free to continue the discussion if you need more clarifications.
