### ISSUE TITLE
Compilation issue on macOS with homebrew's g++-14

### ISSUE THREAD

**Issue by marekkokot** [igraph/igraph#2691]
**Describe the bug**
Does not compile on MAC OS homebrew g++-14 because of `-D_POSIX_C_SOURCE=200809L`.

**To reproduce**
```
git clone https://github.com/igraph/igraph/
cd igraph
mkdir build-g++-14
cd build-g++-14
cmake .. -DCMAKE_CXX_COMPILER=g++-14 -DCMAKE_C_COMPILER=gcc-14
make -j VERBOSE=1 &> build.log
```
I get (for example):
![image](https://github.com/user-attachments/assets/9486aa2b-22bd-4499-9673-6d3d6eda6c64)

**Version information**
[Current master](https://github.com/igraph/igraph/commit/a6441e7a00118988aeac528910d6b9d417aec364)

I am not sure if this is a graph issue or a homebrew g++-14 issue. I started a discussion on this here: https://github.com/orgs/Homebrew/discussions/5714

I think the main question is if `-D_POSIX_C_SOURCE=200809L` is needed

**Comment by szhorvat** [comment]
Thanks for the report!

This is very likely a Homebrew issue, as it works on other systems, and your minimal example seem correct. Their headers might not account for C++ properly. Does the error occur with `stdlib.h` as well? We've seen similar issues (with `math.h` vs `cmath` on other systems, not related to `_POSIX_C_SOURCE`), and the experience was that a workaround for one broken system (through choosing `cmath` vs `math.h` or vice versa) triggered an issue on another broken system. So I'd rather not mess with it and leave it up to Homebrew to try to debug.

I tested this with GCC 14.2.0 on MacPorts, and it compiles (for as long as I don't use the macOS 15.1 SDK, there's a different issue there https://trac.macports.org/ticket/71241)

I also tested on Fedora 41 (in Docker) with GCC 14.2.1, and it also compiles there.

`-D_POSIX_C_SOURCE=200809L` is needed because we use some functions which are not in the C99 standard, but are in the POSIX standard. This used to be a non-portable `-D_GNU_SOURCE` in the past, but the functions are not just a GNU extension, but also POSIX, so we moved to using a portable, documented, standard method. I don't recall from memory which specific functions these were. Is it still broken with `-D_GNU_SOURCE`?

**Comment by szhorvat** [comment]
> I think the main question is if `-D_POSIX_C_SOURCE=200809L` is needed

If you need a workaround for your personal use, and you find that igraph compiles without using this define, then it is safe to use without it.  If there are any bad effects, it will be a slight (likely irrelevant) performance reduction due to using fallback implementations of some of the affected functions.

Note that this doesn't mean that this define is NOT needed in general and we can remove it. Your system may be providing the required non-C99 functions without this define, but some other systems may not. So we can't remove it from igraph (as it will likely break some systems), but if removing it works on your specific system, you should not be worried about going ahead.
