### ISSUE TITLE
Compilation failure on some RHEL versions with a patched libxml2 2.9.7

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#2698]
Some RHEL versions (and their clones, like Rocky Linux) contain a patched version of libxml2 2.9.7:

https://src.fedoraproject.org/rpms/libxml2/blob/f26/f/libxml2-CVE-2016-9597.patch

The patch is effectively breaking, as it adds a new field `xmlEntityRecursionGuard guard` to the `xmlEntity` struct. Since igraph uses the `-Wextra` flag, and does not initialize this field (which shouldn't be there, and isn't present in any released libxml2 version), a warning is triggered, which is then treated as an error:

```
igraph/src/io/graphml.c:73:1: error: missing field 'guard' initializer [-Werror,-Wmissing-field-initializers]
};
^
1 error generated.
```

This is likely to affect some HPC systems, many of which use outdated RHEL operating systems.

Setting `IGRAPH_WARNINGS_AS_ERRORS=OFF` is a good workaround.

**Comment by szhorvat** [comment]
Perhaps we should just set up a troubleshooting FAQ and add this information there.

**Comment by szhorvat** [comment]
No, this doesn't fix it, but as you said, the `static` is needed anyway.

I think a thread-local marker is also needed. Is there any reason not to add it?

**Comment by szhorvat** [comment]
@ntamas lixbml2 doesn't have great documentation ... do you know if this `blankEntity` object is actually valid, with no `name` of `content` in it?

**Comment by ntamas** [comment]
I don't know but it used to work so far. The whole `blankEntity` hackery is actually only needed because the parser tries to ignore unknown entities like `&something;` in the XML docs if this somehow creeps into the document (even if it is not valid XML this way). We can change `igraph_i_graphml_sax_handler_get_entity` to return null if an entity is not found, and in this case the parser would just probably bail out with an error. We used to have problems with error handling in the parser in the past but not any more so it should be okay.

**Comment by szhorvat** [comment]
Wrote a troubleshooting FAQ, https://github.com/igraph/igraph/wiki/Troubleshooting-FAQ
