### ISSUE TITLE
Support reading .paj Pajek project files

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#359]
They may contain various data types, but they are all very simple.

Possible data objects:
- networks, 
- partitions, 
- permutations, 
- clusters, 
- hierarchies and 
- vectors.

The only question is which object belongs to which network, if there are multiple networks in the file.

---

Imported from Launchpad using lp2gh.
- date created: 2012-09-05T02:55:08Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/1046133

**Comment by szhorvat** [comment]
I looked into this a while ago, but gave up, for the following reasons:

 - The Pajek format is not well documented. Perhaps we can discuss this with Pajek's author at our upcoming meeting.
 - Implementing a parser in C is hard because of the stringent requirements. Unlike a somewhat sloppy parser cobbled together from regexes in a high-level language, a C parser must be strict and reliable, and above all not crash or do something unpredictable when presented with bad input.
 - The format is not designed in such a way to make parsing with a standard framework like Flex/Bison easy.
 - The format appears to be designed specifically for the Pajek software, and does not seem like a good _exchange_ format. The format's features are tied to Pajek's features, which do not map well to other systems. While there are several old datasets in the Pajek format, I do not expect people to keep using this format for sharing/exchanging new data. Thus full support should be of low priority.

IMO it only makes sense to proceed if the format becomes well documented, and if people start using it again for new datasets. Otherwise, we should advise users to choose formats which were explicitly designed as exchange formats (such as GraphML or GML), not as the native format of a single system.
