### ISSUE TITLE
Check Dijkstra shortest path functions for zero weights

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#419]
All shortest paths calculation does not seem to handle this, others might.

---

Imported from Launchpad using lp2gh.
- date created: 2010-09-23T11:07:03Z
- owner: gabor.csardi
- the launchpad url was https://bugs.launchpad.net/bugs/645933

**Comment by szhorvat** [comment]
I did a random testing of `igraph_shortest_paths_dijkstra` through the Mathematica interface for a few tens of thousands of inputs of various densities (undirected and directed) and could not find an issue.

For reference, the code was

```
counter = 0;
Dynamic[counter] (* show counter *)
While[True,
 g = IGGiantComponent@
   RandomGraph[{100, 200}, DirectedEdges -> False];
 wg = Graph[g, EdgeWeight -> RandomInteger[{0, 3}, EdgeCount[g]]];
 If[IGDistanceMatrix[wg, Method -> "Dijkstra"] != 
   GraphDistanceMatrix[wg],
  Break[]
  ];
 counter++;
 ]
```

@gaborcsardi Do you remember what the issue was?  Perhaps it can be closed?

**Comment by ntamas** [comment]
I'm pretty sure it's safe to close this.
