### ISSUE TITLE
Break long code lines in the C PDF manual

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#536]
Maybe only possible to break lines in the actual code....

**Comment by ntamas** [comment]
Right now the examples are not even visible in the C PDF manual. This should be fixed before the 0.8 release if possible.

**Comment by szhorvat** [comment]
Does anyone actually use PDF manuals for such software? I would have expected most people to use the HTML version.

Copying code from PDF is not always reliable due to strange character encodings.

**Comment by ntamas** [comment]
Good question. I'd love to be able to drop PDF support at some point because then we could move on to a more modern documentation publishing platform such as [Antora](https://antora.org/). (They are [working on PDF support](https://gitlab.com/antora/antora/issues/349) but it's not there yet).

**Comment by vtraag** [comment]
I wouldn't mind dropping PDF support either. I think almost everyone will use HTML.

**Comment by iosonofabio** [comment]
Let's drop it

**Comment by ntamas** [comment]
> Right now the examples are not even visible in the C PDF manual.

I have checked the build process and it seems like the examples are _explicitly_ removed - only the heading is kept along with the filename, so I guess the original intention was that users who are using the PDF manual should look up the corresponding file on their computers.

Since we have agreed not to put too much emphasis on the PDF documentation, I propose the following: let's keep the current PDF documentation for version 0.8 as it would be extra effort to remove it from the build process and the webpage - _but_, at the same time, let's start exploring alternative options for generating the documentation that relies on standard toolchains instead of brewing our own. This could be left for 0.9 of course.

**Comment by szhorvat** [comment]
So, there is an important point that I forgot about:

Currently, the HTML docs are only convenient to read online. There should be an easy enough way to read them offline. Whether this is through a PDF version of a self-contained zipped package of the HTML pages, it does not matter. But there should be a way.

**Comment by ntamas** [comment]
Would a Dash docset solve that problem for you?

**Comment by szhorvat** [comment]
> Would a Dash docset solve that problem for you?

Well, it's not for me personally. I am comfortable enough with igraph to just build the HTML docs myself.

But normal users of the C interface should not need to do this.

Of course, I'll look into how to make a Dash docset (after all, I suggested it), but I feel that it's not quite sufficient because Dash is not free. However, as part of making that, we can probably easily produce a zipped archive of HTML pages, which will solve this problem, and is still better than PDFs.

**Comment by ntamas** [comment]
> Of course, I'll look into how to make a Dash docset (after all, I suggested it)

I have looked into it already; the bottom line is that you need to:

* create a special directory structure (not a big deal)
* copy all your HTML into one particular folder in this directory structure (not a big deal either)
* provide an Info.plist file with metadata (easy)
* create an SQLite3 database inside the docset that contains the index of the docset

It is the latter part that is tricky; basically, we need to create a large table with search terms and the pages that the terms point to. This probably involves processing the index that we already have in Docbook format, using a custom Python script. SQLite3 comes preinstalled on macOS and Python includes a module for SQLite3 so at least we don't need to bother with that.

**Comment by szhorvat** [comment]
That's really great! Thank you so much.

One more necessary point is collecting all the necessary resources (CSS, images, js files, etc.), which I haven't figured out yet ... I guess you are familiar with this since you were building the website.
