### ISSUE TITLE
SIR failure 

### ISSUE THREAD

**Issue by apford** [igraph/igraph#620]
By changing the time scale of the two rates in sir I get a failure 

> set.seed(42);sirres6 <- sir(HGeg4agc,beta=6, gamma=10, 100)
> set.seed(42);sirresp6 <- sir(HGeg4agc,beta=.6, gamma=1, 100)
> Error in sir(HGeg4agc, beta = 0.6, gamma = 1, 100) : 
>   At sir.c:178 : Internal SIR error, Internal error, likely a bug in igraph
> 
> HGeg4agc
> IGRAPH U--- 610 1469 -- 
> is.simple(HGeg4agc)
> [1] TRUE

I can e-mail the graph as an RData file or dput it  here.

**Comment by vtraag** [comment]
I've been looking at this error. It seems that there are some numerical inaccuracies while doing the simulation. For some reason, this only seems to turn up for `beta < 1`, I'm not sure why exactly.

As a simple solution, I thought we could simply reset the entire vector of `igraph_psumtree_t tree` to zero here, instead of reporting an error: https://github.com/igraph/igraph/blob/9bb8167ad6d6e5ae3a8359610a85bca57916e4b8/src/sir.c#L185
However, that results in another problem, namely that 
https://github.com/igraph/igraph/blob/9bb8167ad6d6e5ae3a8359610a85bca57916e4b8/src/sir.c#L204
results in `vchange = -1`, which is of course problematic.

It therefore seems that `igraph_psumtree_search` is not fully correct, perhaps for some corner case. I've been trying to look into it, but it is undocumented and not immediately clear to understand. For the record, this is my understanding of it at this point. If `tree` is of type `igraph_psumtree_t` then `tree.v`  contains a binary tree in the location `0` to `tree.offset-1` which contains the prefix sums of the values contained in locations `tree.offset` to `tree.offset + tree.size`. However, how the search and update works exactly is not yet clear to me. 

@gaborcsardi, do you have any idea under what conditions `igraph_psumtree_search` may find an index of `-1`?

**Comment by vtraag** [comment]
It seems that numerical issues also arise with 
https://github.com/igraph/igraph/blob/9bb8167ad6d6e5ae3a8359610a85bca57916e4b8/src/sir.c#L198

The problem seems to be that `psum > 0` but that all values in the `tree` are actually 0. In other words, no node can be sampled anymore, and hence `igraph_psumtree_search` returns `-1`.

Changing it to
```
while (ni > 0) {
```
resolves the issue it seems.
