### ISSUE TITLE
Drop NaNs from BFS/DFS order output

### ISSUE THREAD

**Issue by gaborcsardi** [igraph/igraph#814]
For the vertices that were not visited at all....

**Comment by ntamas** [comment]
Just for future reference (so we know what I meant originally): I think it makes sense to keep the NaNs for the output vectors where the value corresponding to vertex i is in the i-th element (e.g., `father`, `succ`, `pred`, `dist`). However, it does not make sense for `order` because that vector is filled from the front anyway.

**Comment by abitofalchemy** [comment]
when `unreachable` is set to 0, I tried to check if the value is `IGRAPH_INFINITY`, but noticed that it doesn't work.  However, using` igraph_vector_print` will print a `NaN`.  If I do a comparison of the value should I be using something other than `IGRAPH_INFINITY`?  
This is what I tried and worked, but I think this is not it igraph-ish way, any suggestions? 
>void print_vector(igraph_vector_t *v) {
>    long int i, l=igraph_vector_size(v);
>    for (i=0; i<l; i++) {
>        if ( (long int)VECTOR(*v)[i] == -9223372036854775808 )
>            printf(" --");
>        else
>            printf(" %2li", (long int) VECTOR(*v)[i]);
>    }
>    printf("\n");
>}

**Comment by ntamas** [comment]
Most C compilers provide a function named `isnan`, which is true iff the value given to it is NaN.

**Comment by szhorvat** [comment]
This is obsolete, there are no more NaN returned by these functions.
