### ISSUE TITLE
Error: GraphBase does not have attribute 'community_leading_eigenvector_naive'

### ISSUE THREAD

**Issue by Pelonza** [igraph/igraph#830]
In the igraph documentation, there is listed the method "community_leading_eigenvector_naive" ... as a graph attribute, which can be called. 

While the attribute is present on a graph instance, if you look at the GraphBase object, it does NOT occur.

I ran into this error in SageMathCloud, so it _might_ be localized to their instance of igraph.
The reported version (via print igraph.**version**) is 0.7.1

I checked the "attributes" via a call to dir() on both igraph.Graph and igraph.GraphBase

If in-fact, the naive version is implemented, then the GraphBase attributes need to be properly updated. If, on the other hand, it's not implemented, the documentation should reflect this.

**Comment by ntamas** [comment]
This is not SageMathCloud's fault, I haven't implemented the necessary glue code between Python and C so this method is not exposed on the Python interface. The reason was that I don't think there's a valid use-case for `community_leading_eigenvector_naive` as the documentation declares that this is *not* the correct implementation of the algorithm (see Newman's paper for more details). I think it was left in the C version for educational purposes only. If you have a valid use-case for this method in Python, let me know and then I'll consider the inclusion in the Python interface.

**Comment by Pelonza** [comment]
I ran into the issue when trying to verify that the primary leading eigenvalue method was working correctly. One of Newman's paper's had reported different leading eigenvalue modularities for matrices I was looking at, but it turned out to be a different between implementing his original algorithm (correctly cited) and his improved algorithm, which appeared in a different paper.

At this point, it doesn't matter much to me if the glue code is implemented attached or not, but I do feel like the documentation should match the implementation(s)... so either a clear note that says it is not fully functional in python (probably fastest/easiest) or add the clue code.

**Comment by vtraag** [comment]
The new `igraph_community_leading_eigenvector` is already implemented, also exposed in `python-igraph`. Can we simply close this issue @ntamas ? Actually, the `community_leading_eigenvector_naive` implementation is removed from the C core, and should also be removed from the Python code; I opened an issue for that: https://github.com/igraph/python-igraph/issues/227

**Comment by ntamas** [comment]
The Python interface never included an implementation; it was only mentioned in the headers. I have removed it from the headers in the Python interface as well so we can close this.
