### ISSUE TITLE
plot swaps weighted option

### ISSUE THREAD

**Issue by surmann** [igraph/igraph#833]
Hallo!
I am using igraph version 0.7.1.
When I create a graph from an adjacency matrix and plot it, I got an unexpected result with respect to the `weighted` option. In my understanding, I expect the plot of an unweighted graph with `weighted=NULL`. But I get it with `weighted=TRUE`. Here is my MWE:
```R
library(igraph)
adjm = diag(rep(0, 3))
adjm[1, 2] = adjm[2, 1] = 1
adjm[2, 3] = adjm[3, 2] = 2
op = par(mfrow = c(1, 2))
g.test = graph.adjacency(adjm, mode = "undirected", weighted = NULL)
plot(g.test, main = "weighted=NULL")
g.test = graph.adjacency(adjm, mode = "undirected", weighted = TRUE)
plot(g.test, main = "weighted=TRUE")
par(op)
```
And the resulting image:
![rplot](https://cloud.githubusercontent.com/assets/4048472/8308325/704869a0-19c4-11e5-819c-a8fe0af7e4a3.png)

Is this a bug or do I missunderstand something?

**Comment by ntamas** [comment]
According to the documentation (see the [R manual page for `graph.adjacency`][1]),

> This argument specifies whether to create a weighted graph from an adjacency matrix. If it is ‘NULL’ then an unweighted graph is created and the elements of the adjacency matrix gives the number of edges between the vertices.

This is consistent with your figure on the left: there are two edges between vertices 2 and 3, but they do not have any associated weight. On the other hand, when you specify `weighted=TRUE`, the following sentence applies:

> If it is ‘TRUE’ then a weighted graph is created and the name of the edge attribute will be ‘weight’.

In this case, you only get a *single* edge between vertices 2 and 3, but that single edge has a weight of 2. Weights are not plotted by default, so that's why the plot "looks like" an unweighted graph with only a single edge between vertices 2 and 3, but if you query the weights of the graph with `E(g.test)$weight`, I'm pretty sure you'll find that one of the edges has weight 1 and the other edge has weight 2.

  [1]: http://www.inside-r.org/packages/cran/igraph/docs/graph.adjacency
