### ISSUE TITLE
igraph_lcf_vector hangs with [2, -2]

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#880]
`igraph_lcf_vector` hangs with `n=2`, `shifts={2, -2}` and `repeats=1`.

**Comment by ntamas** [comment]
It also crashes for `n=2`, `shifts = [2]` and `repeats=1`. Clearly, the problem is caused by `shifts = [2]` - this would create a loop edge and `igraph_lcf_vector` prevents this by only creating edges for which `from < to`.

I'm not that familiar with the LCF notation, though. Are loop edges allowed in graphs created with the LCF notation?

**Comment by szhorvat** [comment]
I'm also unfamiliar with LCF notation, I only heard about it from the igraph docs. None of the example I see online have either self loops or multiple edges ...
