### ISSUE TITLE
Bliss should use igraph's bigints, drop GMP

### ISSUE THREAD

**Issue by szhorvat** [igraph/igraph#889]
As far as I can tell, the only thing GMP is used for in igraph is Bliss.  The only thing Bliss uses GMP for is a bit of non-performance-critical arithmetic for computing the number of automorphisms.

GMP is a big and heavy library. It might be worth getting rid of it entirely and just using igraph's own bigints instead for Bliss.  Bliss has a small large integer class which can wrap either `long double` or GMP bigints.

**Comment by ntamas** [comment]
GMP is not a strict dependency for igraph - you can compile igraph without GMP and then BLISS will fall back to its own bigint (which is basically a glorified `long double` so I wouldn't exactly call that a bigint ;)). So, if you would like to spend some time on this, I think it is okay to extend BLISS's own `BigNum` class to use igraph's bigint instead of just wrapping a `long double`, but I don't think it is necessary to remove support for "real" GMP bigints.

**Comment by szhorvat** [comment]
Well, it's not a strict dependency, but without it the automorphism count may not be accurate, if it is very large.  In practice it can indeed be very very large and not fit all digits in a `long double`.

Once bigints are handled properly, GMP does not seem to provide any advantage given that Bliss uses bigints in a non-performance-critical way.

But unfortunately I don't have time to do this, as I got plenty on my plate (even just for igraph projects).  It was just a suggestion stemming form the observation that GMP is only begin used here.

What might be more interesting is using GMP in other places in igraph, e.g. for betweenness calculations, and seeing if it speeds up things compared to the current bigint implementation.

**Comment by szhorvat** [comment]
I am no longer in favour of doing this. Instead, I would like to see GMP integrated better into igraph.

Closing (re-open if you disagree).
