### ISSUE TITLE
GML node IDs higher than LONG_MAX

### ISSUE THREAD

**Issue by jdevoo** [igraph/igraph#901]
GML files generated from data which exceeds long int limits triggers an exception when loading

igraph._igraph.InternalError: Error at foreign.c:1289: Node 'id' not unique, Parse error

This happens for instance with twitter IDs which exceed 2147483647

**Comment by ntamas** [comment]
The [GML technical report](http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf) states that IDs should be integers:

> .id int
> Defines an identification number for an object. This is usually used to represent pointers.

It also says that GML uses signed 32-bit integers:

> GML uses signed 32-bit integers, which are commonly available on all architectures and languages. Larger numbers should be represented as strings. Especially, bitsets with more than 31 entries should be represented as strings.

Theoretically, we *could* decide to support IDs larger than 2<sup>31</sup>-1 by using `long long int` in the code (assuming that the platform on which igraph is compiled can handle them), but it could lead to problems in the higher level interfaces if they are not prepared for integers larger than a long int. (For instance, Python's native integer data type (`PyInt`) uses long ints). So, I think that the preferred way of handling this would be to 1) provide a better error message in the C core so the user knows that the problem is that the node ID is too large, and 2) use string attributes instead of numeric IDs to represent Twitter IDs.

**Comment by jdevoo** [comment]
The proposed solution would work nicely! I am for the moment wrapping the IDs around sys.maxsize but it's a hack and still breaks with recent Twitter handles e.g. the following record which starts with a commented Twitter user_id
`#4356053599,twitone008,friends,0,291,4,49,Wed Nov 25 12:59:50 +0000 2015,,img/4356053599.jpg,`
