### ISSUE TITLE
Igraph does not compile with Visual Studio 2015

### ISSUE THREAD

**Issue by nvanbalen** [igraph/igraph#909]
I tried to build the igraph c library with Visual Studio 2015 and got the following error:

`fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration'`

I was able to build it by reverting back to Visual Studio 2013, but I feel that this is an issue that should be addressed.

**Comment by ntamas** [comment]
Just a reminder for myself (or anyone else who attempts to fix this): Visual Studio 2013 and earlier versions did not support `sprintf` so we came up with our own implementation (`igraph_i_snprintf`) and then used `#define snprintf igraph_i_snprintf` in `msvc/include/config.h` to pretend that we have `snprintf`. Furthermore, `src/types.c` has its own MSVC-specific workaround that should not be needed now that we have `msvc/include/config.h`, and `src/plfit/platform.h` also brings its own replacement to `snprintf` (because `plfit` is a different library that just happens to be included in igraph).

I think what we need here is to update `msvc/include/config.h` and `src/plfit/platform.h` to test for Visual Studio's version number and include the replacement only if the user is compiling with Visual Studio 2013 or earlier. I don't have access to MSVC so I cannot implement a patch - pull requests are welcome.

**Comment by janschulz** [comment]
This SO might help: http://stackoverflow.com/a/27754829/1380673

It suggests using 

```
#if _MSC_VER>=1900
#  define STDC99
#endif
```

**Comment by janschulz** [comment]
The same happens in VS2010 (python 3.4):

```
"c:\data\external\python-igraph\tmp\igraph.cu8r5jz0\igraph-0.7.1-msvc\igraph.vcxproj" (Standard ziel) (1) ->
(ClCompile Ziel) ->
  c:\data\external\python-igraph\tmp\igraph.cu8r5jz0\igraph-0.7.1-msvc\src\prpack.cpp(66): erro r C2065: 'prpack_igraph_graph' : undeclared identifier [c:\data\external\python-igraph\tmp\igra ph.cu8r5jz0\igraph-0.7.1-msvc\igraph.vcxproj]
  c:\data\external\python-igraph\tmp\igraph.cu8r5jz0\igraph-0.7.1-msvc\src\prpack.cpp(66): erro r C2146: syntax error : missing ';' before identifier 'prpack_graph' [c:\data\external\python-i graph\tmp\igraph.cu8r5jz0\igraph-0.7.1-msvc\igraph.vcxproj]
  c:\data\external\python-igraph\tmp\igraph.cu8r5jz0\igraph-0.7.1-msvc\src\prpack.cpp(66): erro r C3861: 'prpack_graph': identifier not found [c:\data\external\python-igraph\tmp\igraph.cu8r5j z0\igraph-0.7.1-msvc\igraph.vcxproj]
  c:\data\external\python-igraph\tmp\igraph.cu8r5jz0\igraph-0.7.1-msvc\src\prpack.cpp(67): erro r C2065: 'prpack_graph' : undeclared identifier [c:\data\external\python-igraph\tmp\igraph.cu8r 5jz0\igraph-0.7.1-msvc\igraph.vcxproj]
```

**Comment by janschulz** [comment]
Oh d**m: 2.7 errors out with this problem (probably a problem with the VS for python tools vs a real VS install):

```
Failed to load system project defaults file 'C:\Users\jschulz\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\VCProjectDefaults\CoreWin.vsprops'.
The project cannot load without this file installed.
Please re-install the product.

Failed to load system project defaults file 'C:\Users\jschulz\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\VCProjectDefaults\CoreWin.vsprops'.
The project cannot load without this file installed.
Please re-install the product.

Failed to load system project defaults file 'C:\Users\jschulz\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\VCProjectDefaults\CoreWin.vsprops'.
The project cannot load without this file installed.
Please re-install the product.

Failed to load system project defaults file 'C:\Users\jschulz\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\VCProjectDefaults\CoreWin.vsprops'.
The project cannot load without this file installed.
Please re-install the product.
```

**Comment by szhorvat** [comment]
@janschulz Did you (or anyone else) manage to built the development version of the C library with MSVC 2015?  I'm not talking about the Python interface, which still uses an older version of the C library.

**Comment by janschulz** [comment]
See above: all three available VS versions errored in code which is unchanged in current master... I'm currently setting up appveyor to do automatic tests: https://github.com/igraph/igraph/pull/951 

The biggest problem I see is that the VS for python tools is not able to build due to the missing default config, and AFAIK there is no other full VS for python 2007 anymore so IMO igraph on windows for python 2.7 is not easily buildable anymore...

[On the other hand appveyor still has the full version installed]

**Comment by ntamas** [comment]
I'm not that familiar with Windows and MSVC so I cannot contribute anything useful here, but I was wondering how [Christoph Gohlke](http://www.lfd.uci.edu/~gohlke/pythonlibs/#python-igraph) is creating his python-igraph builds for Python 2.7 - surely there must be a way around. (Or is the solution simply to use a "full" VS and not "VS for Python", whatever that may be?).

**Comment by janschulz** [comment]
I suspect he (nd probably others) still have the full VS for py27 around... 

(Just for the record: I've also no problem for removing py27 :-))

**Comment by janschulz** [comment]
@ntamas: would you be able to fix the errors in https://github.com/igraph/igraph/issues/909#issuecomment-230940229 That looks like some undeclared variables https://github.com/igraph/igraph/blob/master/src/prpack.cpp

**Comment by ntamas** [comment]
That's not an error; you either need to define `PRPACK_IGRAPH_SUPPORT` in the compiler flags (which will define `prpack_igraph_graph in `prpack/prpack_igraph_graph.h`) or exclude `prpack.cpp` from the build. (It is a bit convoluted this way but I preferred a flag so I can leave most of the PRPACK source code untouched - makes it easier to merge any changes in upstream).

**Comment by janschulz** [comment]
So who/where should that be declared? IN the msvc project file?

**Comment by szhorvat** [comment]
Just to make it clear, is this discussion about 0.7.1 or about the dev version?  As I remember I did manage to build 0.7.1 with MSVC, though my memory may serve me wrong.  I would have to look again.

There are lots of changes in the dev version.

**Comment by janschulz** [comment]
The above errors come from a build try on 0.7.1...

**Comment by ntamas** [comment]
> So who/where should that be declared? In the msvc project file?

Maybe the easiest is to put it in `msvc/config.h` near the end. On Linux or Mac OS X, the makefile in `src/` defines it for the part of the build process when PRPACK is being built, but I guess it does not hurt to have it defined during the whole build.

**Comment by janschulz** [comment]
Ok, I added `#define PRPACK_IGRAPH_SUPPORT 1` and at least build with msbuild v14 compiled... Will add that to the PR in #951

**Comment by mvackel** [comment]
Hello,
I've did the following for VS2015:
- Automatic solution conversion by opening the solution with VS2015.
- On file config.h:
  change line 173:       #define snprintf igraph_i_snprintf
  to:  
#if _MSC_VER<1900
#define snprintf igraph_i_snprintf
#endif

- Defined  PRPACK_IGRAPH_SUPPORT  at:
  Project/igraph Properties...  -> Preprocessor  -> Preprocessor Definitions
  (for both configurations:  Debug and Release)

Now the project (0.7.1) compiles (with 749 warnings) and generates a  .lib file at folder "Debug" (or "Release).

The question is: how do I use this  .lib file with the Python interface? Shouldn't the file be a DLL -- and than manually rename the extension to .PYD? The target extension at the "Configuration Properties"/General is indeed as .lib.

**Comment by flying-sheep** [comment]
I got as far as @mvackel. How can we proceed from there?

**Comment by ntamas** [comment]
Okay, so the .lib file that you have compiled is probably a static library version of igraph. (I cannot say for sure because I am not using Windows and I have not tried compiling stuff with MSVC recently). That's not the same as the .pyd file; the .pyd file is the "glue code" between Python and igraph, plus the contents of the .lib file as well.

The next logical step would be to get the source code of the Python interface (make sure to use the source code of 0.7.1post6 if you were compiling igraph 0.7.1; if you compiled the dev version of igraph straight from Github, then you'll also need the head revision of python-igraph from Github). Extract it somewhere, launch a shell and try running `python setup.py build`. Most likely it will complain about not being able to find igraph's header files (which are in `include/`) and the compiled library (which is wherever VSCode put it), and tell you which environment variables should be set to let it find them. I cannot tell you more about the exact procedure on Windows, but if you manage to compile it, feel free to send me a summary and I'll publish it somewhere on the wiki.

**Comment by flying-sheep** [comment]
yes it is a static library:

|   | win | linux |
|---|---|---|
| static lib | .lib | .a |
| dynamic lib | .dll | .so[.?] |
| object | .obj | .o |

it would be good to know how to make the headers and library findable on windows

**Comment by szhorvat** [comment]
Perhaps this information will help someone:

I am still unable to compile igraph (dev version) with the MSVC tools. What I do instead is that I compile igraph with MinGW, and use the produced DLL from MSVC.  I have not yet run into ABI incompatibility issues.  However, I do need to take care to only use `igraph_malloc` and `igraph_free` (instead of `malloc` and `free`) when dealing with igraph om the MSVC side. This is so as not to try to use MSVC's `free` on something allocated with MinGW's malloc or vice-versa.

It is also unclear to me if the current Appveyor setup includes all recent changes. When adding a new file to igraph, we usually need to modify `Makefile.am`. Is there no such requirement for the build files used by MSVC, to ensure that everything is included?

It would be nice to maintain a "Building on Windows" guide, perhaps in the GitHub Wiki.

**Comment by vtraag** [comment]
Given that `igraph` builds correctly on Windows in AppVeyor, can we simply close this issue? Or is there some specific issue still here that does not play on AppVeyor, but does play in other contexts?

The point about improving instructions is already a separate issue https://github.com/igraph/igraph/issues/969.

**Comment by ntamas** [comment]
Closing this; I think AppVeyor does the job well now. Anyone is free to reopen this issue if they think otherwise.
