### ISSUE TITLE
triad.census returning negative values for first triad count

### ISSUE THREAD

**Issue by dalburez** [igraph/igraph#997]
igraph's triad.census will occasionally return a negative value for the first triad (003) if its incidence is particularly high. Take, for example:

library(igraph)
gr <-  erdos.renyi.game(10000, 0.001, directed = T)
triad.census(gr)
[1] -1164826850   991152717      468094      494363      494021      987907         920         889         969
[10]         307 

It was suggested in SO that this might be an integer overflow problem. Could you please look into it?

**Comment by szhorvat** [comment]
This is no doubt an integer overflow problem.  There are in total `10000 choose 3` = 166,616,670,000 triads.  This function uses 32-bit integers (`igraph_integer_t` is an `int`), whose maximum value is `2^31 - 1` = 2,147,483,647.  This value simply doesn't fit in a 32-bit int.

As a workaround, you can subtract the rest of the values from the total number of triads:

    166616670000 - (991152717 + 468094 + 494363 + 494021 + 987907 + 920 + 889 + 969 + 307)

    165623069813

This is the number of empty triads (and this is exactly how `igraph_triad_census` computes them internally: it subtracts the rest from the total).

I guess this could be fixed on 64-bit computers by using a `long` instead of an `int` for counting.

**Comment by szhorvat** [comment]
@ntamas  Would you mind also using a real type in `igraph_triad_census_24` (for `res2` and `res4`) for consistency?  I was just about to suggest this when you closed the issue.

`igraph_triad_census_24` does not appear to be used anywhere else.

The motif finder already uses a real type for counting, so only the 2nd and 4th elements need to be updated.  Then everything will have an effective 53-bit precision (number of binary digits in a `double`).

**Comment by ntamas** [comment]
It's done in commit 46100215
